### ISSUE TITLE
Missing thread title

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#1001]
![image](https://user-images.githubusercontent.com/1217271/51196523-e7951d80-18b4-11e9-9472-c71a8599acf9.png)

![image](https://user-images.githubusercontent.com/1217271/51196533-ec59d180-18b4-11e9-8096-66ebc82d45da.png)

**Comment by Ian-Hitt** [comment]
Xlink issue, already resolved
