### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#1007]
Server error log
Less_Exception_Chunk: ParseError: missing opening `{` in anonymous-file-0.less on line 2784, column 1 2782| -moz-osx-font-smoothing: grayscale; 2783| 2784| } 2785| 2786| .m-faContent(@content, @width: false, @direction: false) 2787| { src/vendor/oyejorge/less.php/lib/Less/Parser.php:677
Generated by: Unknown account Jan 28, 2019 at 8:55 AM
Stack trace
#0 src/vendor/oyejorge/less.php/lib/Less/Parser.php(621): Less_Parser->GetRules(NULL)
#1 src/vendor/oyejorge/less.php/lib/Less/Parser.php(449): Less_Parser->_parse()
#2 src/XF/CssRenderer.php(394): Less_Parser->parse('// Note that th...')
#3 src/XF/CssRenderer.php(342): XF\CssRenderer->renderToCss('public:widget_E...', '// Note that th...')
#4 src/XF/CssRenderer.php(250): XF\CssRenderer->renderTemplate('public:widget_E...', NULL)
#5 src/XF/CssRenderer.php(116): XF\CssRenderer->renderTemplates(Array, Array, Array)
#6 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#7 css.php(30): XF\CssWriter->run(Array, 58, 1, '4897eb74cb3b245...')
#8 {main}
Request state
array(4) {
  ["url"] => string(308) "/css.php?css=public%3AEWRporta.less%2Cpublic%3AEWRporta_articles.less%2Cpublic%3Aalnb_navigation.less%2Cpublic%3Amessage.less%2Cpublic%3Anotices.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Awidget_EWRporta_features.less%2Cpublic%3Aextra.less&s=58&l=1&d=1519483161&k=4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  ["referrer"] => string(30) "https://www.gnonline.net/home/"
  ["_GET"] => array(5) {
    ["css"] => string(200) "public:EWRporta.less,public:EWRporta_articles.less,public:alnb_navigation.less,public:message.less,public:notices.less,public:share_controls.less,public:widget_EWRporta_features.less,public:extra.less"
    ["s"] => string(2) "58"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1519483161"
    ["k"] => string(40) "4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by Ian-Hitt** [comment]
Fixed in commit 6f827a507
