### ISSUE TITLE
UIX email template buttons are odd

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#102]
<img width="508" alt="screen shot 2017-10-30 at 11 55 03 am" src="https://user-images.githubusercontent.com/1217271/32184137-4a04c2ac-bd69-11e7-97a6-268f6042f0c9.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer is this even theme specific?

**Comment by mikecreuzer** [comment]
I believe so yes.

**Comment by mikecreuzer** [comment]
I guess I would find where that button is getting its CSS from (its all inline afaik so likely a template) and see what value that is. We may not even be able to change it which means we may need to submit a bug to XenForo that they need to give us that ability.
