### ISSUE TITLE
[Nodes] Unnecessary colon after stats

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#1023]
As per title:
![image](https://user-images.githubusercontent.com/34864926/51085488-f30c0b80-1731-11e9-8e39-cf874b07c27c.png)

**Comment by BigIron5** [comment]
@Ian-Hitt 

With node stats icons turned off and viewing on mobile, the numbers are to the left of Threads and Messages _unless_ the node has subforums. Should I create a new issue?
