### ISSUE TITLE
Can't install IO 2.1.0.2

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#1027]
Style Name:
iO

Style Version:
2.1.02
UI.X Add-on Version:
2.1.0
XenForo Version:
XF 2.1

Summary of issue:
`
XF\Db\Exception: MySQL query error [1364]: Field 'th_iau_profile_id' doesn't have a default value src/XF/Db/AbstractStatement.php:217
Generated by: nik Feb 7, 2019 at 11:33 PM
Stack trace
INSERT  INTO `xf_style` (`title`, `description`, `parent_id`, `user_selectable`, `style_id`, `parent_list`, `properties`, `last_modified_date`, `designer_mode`, `th_product_id_uix`, `th_product_version_uix`, `th_primary_child_uix`, `th_child_style_xml_uix`, `th_child_style_cache_uix`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
------------

#0 src/XF/Db/Mysqli/Statement.php(196): XF\Db\AbstractStatement->getException('MySQL query err...', 1364, 'HY000')
#1 src/XF/Db/Mysqli/Statement.php(77): XF\Db\Mysqli\Statement->getException('MySQL query err...', 1364, 'HY000')
#2 src/XF/Db/AbstractAdapter.php(89): XF\Db\Mysqli\Statement->execute()
#3 src/XF/Db/AbstractAdapter.php(169): XF\Db\AbstractAdapter->query('INSERT  INTO `x...', Array)
#4 src/XF/Mvc/Entity/Entity.php(1452): XF\Db\AbstractAdapter->insert('xf_style', Array, false)
#5 src/XF/Mvc/Entity/Entity.php(1184): XF\Mvc\Entity\Entity->_saveToSource()
#6 src/XF/Service/Style/Import.php(366): XF\Mvc\Entity\Entity->save(true, false)
#7 src/XF/Service/Style/Import.php(117): XF\Service\Style\Import->getTargetStyle(Object(SimpleXMLElement))
#8 src/addons/ThemeHouse/UIX/Service/Style/Installer.php(107): XF\Service\Style\Import->importFromXml(Object(SimpleXMLElement))
#9 src/addons/ThemeHouse/UIX/Service/Style/Installer.php(42): ThemeHouse\UIX\Service\Style\Installer->importStyle('/home/nginx/dom...', NULL, Array)
#10 src/addons/ThemeHouse/UIX/XF/Admin/Controller/Style.php(453): ThemeHouse\UIX\Service\Style\Installer->install('/home/nginx/dom...', Array, Array)
#11 src/addons/ThemeHouse/UIX/XF/Admin/Controller/Style.php(277): ThemeHouse\UIX\XF\Admin\Controller\Style->installUpgradeStyle(Array, Array)
#12 src/XF/Mvc/Dispatcher.php(321): ThemeHouse\UIX\XF\Admin\Controller\Style->actionThemehouseInstall(Object(XF\Mvc\ParameterBag))
#13 src/XF/Mvc/Dispatcher.php(244): XF\Mvc\Dispatcher->dispatchClass('XF:Style', 'ThemehouseInsta...', Object(XF\Mvc\RouteMatch), Object(ThemeHouse\UIX\XF\Admin\Controller\Style), NULL)
#14 src/XF/Mvc/Dispatcher.php(100): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(ThemeHouse\UIX\XF\Admin\Controller\Style), NULL)
#15 src/XF/Mvc/Dispatcher.php(50): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#16 src/XF/App.php(2177): XF\Mvc\Dispatcher->run()
#17 src/XF.php(390): XF\App->run()
#18 admin.php(13): XF::runApp('XF\\Admin\\App')
#19 {main}
Request state
array(4) {
  ["url"] => string(61) "/community/admin.php?styles/themehouse/install&product_id=237"
  ["referrer"] => string(82) "https://mysite.com/community/admin.php?styles/themehouse/install&product_id=237"
  ["_GET"] => array(2) {
    ["styles/themehouse/install"] => string(0) ""
    ["product_id"] => string(3) "237"
  }
  ["_POST"] => array(3) {
    ["version_id"] => string(4) "1454"
    ["step"] => string(11) "ftp_details"
    ["_xfToken"] => string(8) "********"
  }
}
`
Detailed steps to reproduce the issue:

Attempt to install theme via UIX

**Comment by ichpen** [comment]
The culprit was having Install and Upgrade present (disabled). Completely uninstalling Install and Upgrade got me past the error.

**Comment by Ian-Hitt** [comment]
Apologies, yes this is a bug in install and upgrade. There is a duplicate issue in the addons repo for this.
