### ISSUE TITLE
UI.X Dark (XF 2.1) - Nav Profile Pulldown Menu Avatar Size & Alignment

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#1030]
Style Name: UI.X Dark for XF 2.1

Style Version: 2.1

UI.X Add-on Version: Latest

XenForo Version: 2.1.0

Operating System (and Version): Windows 10 64 Bit (Stable)

Browser Name (and Version): Chrome 72 64 Bit (Stable)

Does this issue happen in the default XenForo style? No.

Summary of issue: Alignment of profile pulldown menu "card" doesn't look attractive. It somehow changed recently in the 2.1 ui.x update. Avatar appears way too small. Used to look better.

Detailed steps to reproduce the issue: Click on username/avatar in top right navbar on any page, avatar is small and not to the left of the stats as well as it does in the XF default.

Upload any screenshots related to the issue below

![profile_xfdefault](https://user-images.githubusercontent.com/35111972/52494532-3e340580-2b9c-11e9-9fed-858adda54dfe.png)

![profile_uix21](https://user-images.githubusercontent.com/35111972/52494541-43915000-2b9c-11e9-9585-d299ed91b618.png)

**Comment by Ian-Hitt** [comment]
This is intentional, and has been this way since version 2.0.5. The change is made to separate the "user indetity" content from the statistics.

**Comment by lilalien** [comment]
While its nice to have them separate I suppose, it seems like a solution in search of a problem... It *looked* better with the larger avatar visible to me. :) Those stats are for the user, so while I get what you're saying I miss the large avatar.. We actually had it until our 2.1 switchover, we definitely lost a couple of odd things that never somehow overwrite when we updated our styles... If this was a change from may 2018 I have no idea how we lost that change given that I am very careful with the updates.

Oh well, no big deal either way.. Just looked nicer to me previously...

**Comment by lilalien** [comment]
To be specific, the large avatar spaces/flows better to me with the "Your account" text above the avatar nice and aligned, as a column there... With the UI.X version, the avatar seems unnecessarily small and squeezed. :) Either way though its OK.

**Comment by lilalien** [comment]
@Ian-Hitt @mikecreuzer For consistency, what about this case? I think one consistent choice should be selected. I still think it looked better represented by larger avatars for both cases of this original report AND this screenshot's example. :)

![pop-up_member_card](https://user-images.githubusercontent.com/35111972/52742664-3dd5a900-2fa6-11e9-9bfd-a75b690b5147.png)
