### ISSUE TITLE
UI.X Dark (XF 2.1) - Floating Notices are forced left instead of right!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#1034]
Style Name: UI.X 2 (Dark)

Style Version: 2.1

UI.X Add-on Version: Latest Stable

XenForo Version: 2.1.0

Operating System (and Version): Windows 10 - 64 bit - Stable

Browser Name (and Version): Chrome 72 - 64 bit - Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When creating a notice, and having it float it is supposed to appear on the lower right corner. Recently its been floating in the lower left corner. This even happened before the 2.1 update, but I forgot to report it and I'm trying to add everything to the bug tracker.

Detailed steps to reproduce the issue: Create a notice, make sure you choose floating notice (which defaults to the right), it works in default theme but NOT in ui.x 2 dark (pre-2.1 or 2.1+)

Upload any screenshots related to the issue below

![notice_floating_wrong_side](https://user-images.githubusercontent.com/35111972/52513436-c6380080-2bd8-11e9-8b18-5f6a256e0a8a.png)

**Comment by Ian-Hitt** [comment]
Floating notices are intentionally on the left because there are other components (such as jump to top/bottom buttons) that float to the right. This has been this way since the first UI.X version and is intentional.

**Comment by lilalien** [comment]
Odd, somehow my custom style (which never purposely overwrote that) had it working for a year before it stopped working.. Crazy.

For those of us that don't put the top/bottom button there I wish there was a setting or override available for it as it looks more attractive on the right.
