### ISSUE TITLE
Like button page shift

### ISSUE THREAD

**Issue by BigIron5** [Audentio/xf2theme-issues#1038]
Style Name: UI.X 2

Style Version: 2.1.0.2.0

UI.X Add-on Version: 2.1.0

XenForo Version: 2.1.0

Operating System (and Version): Windows 10

Browser Name (and Version): Tested with Chrome Version 71.0.3578.98 (Official Build) (64-bit) and Firefox 65.0.1 (64-bit) 

Can you replicate this issue on our demo for this theme? Yes, item 1 is confirmed. Need additional users to replicate item 2.

Does this issue happen in the default XenForo style? No 

Summary of issue: 

Item 1 - When liking a post liked by someone else, the reactionBar and report button icon (not the report button) shift down .5px. 

Item 2 - When liking a post liked by multiple people, many elements on the pages below the liked post to shift down .5px.

Detailed steps to reproduce the issue: 

Item 1 Like a thread. Note the shift. 

Item 2 Like a post with at least two other likes and a post below it. Note the shift of postbit avatars, badges, etc. below the post. 

Upload any screenshots related to the issue below

**Comment by Ian-Hitt** [comment]
Fixed in previous release
