### ISSUE TITLE
Forum view node stats mobile view number incorrect position

### ISSUE THREAD

**Issue by BigIron5** [Audentio/xf2theme-issues#1042]
Style Name:

Style Version:

UI.X Add-on Version:

XenForo Version:

Operating System (and Version):

Browser Name (and Version):

Can you replicate this issue on our demo for this theme?

Does this issue happen in the default XenForo style?

Summary of issue:

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by Ian-Hitt** [comment]
Duplicate issue: closing https://github.com/Audentio/xf2theme-issues/issues/1023
