### ISSUE TITLE
Original poster phrase missing

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#1044]
![image](https://user-images.githubusercontent.com/1217271/52963927-b487f300-3366-11e9-9cd9-970ea9cf8643.png)

**Comment by JakeBooher** [comment]
This phrase should be prefixed with `uix` as well, `th_uix_original_poster`.

**Comment by Ian-Hitt** [comment]
Phrase exists. @jonw316 Make sure latest UI.X release has this in it

**Comment by Ian-Hitt** [comment]
Issue moved to [Audentio/xf2addon-issues #1519](https://github.com/Audentio/xf2addon-issues/issues/1519) via [**ZenHub**](https://www.zenhub.com/)
