### ISSUE TITLE
Scrollbar impacting canvas

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#1046]
Causes everything to jump.

![image](https://user-images.githubusercontent.com/1217271/52964200-60314300-3367-11e9-834c-1d1f5b1ccf5b.png)
![image](https://user-images.githubusercontent.com/1217271/52964227-6cb59b80-3367-11e9-9686-59d5e7b48cfa.png)

**Comment by Ian-Hitt** [comment]
This is intended in the default XF theme, not an SDN or UI.X issue, and is how they handle scrolling containers throughout the platform. I've added a fix for specifically canvases in UI.X
