### ISSUE TITLE
Dark pixel bug is a UI.X bug

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#1055]
Not just SDN like I thought

**Comment by Ian-Hitt** [comment]
To replicate:

On Android actual device, when logged in as admin scroll down then back up. strange dark square appears top left corner of admin link.

**Comment by Ian-Hitt** [comment]
ETA: This is a Chrome on Android render bug specifically. Any re-rendering actions (such as adjusting any css on any element in browser) fixes the issue. It is also somewhat related to sticky kit in UI.X, which is why it does not happen in default theme.
