### ISSUE TITLE
[UIX 2.1.0.2] Manifest.json broken

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#1059]
Enabled manifest.json in UIX properties.

Added my own manifest.json to root.

Looking into Google Dev Tools under applications it says No Manifest found.

Looking into the html output in the console I see:
```
<xen:if is="">
   <link rel="manifest" href="(unknown)">
</xen:if>
```

So does not appear to be getting set correctly.

**Comment by jonw316** [comment]
@Ian-Hitt Looks like you've used <xen: instead of <xf:

**Comment by ichpen** [comment]
still broken @jonw316 @Ian-Hitt

**Comment by jonw316** [comment]
Are you sure this isn't a template edit you've made? I haven't been able to find anything like this in any of our code.

**Comment by ichpen** [comment]
100% I didn't make that edit @jonw316. What templates should I be looking at for this one?

**Comment by jonw316** [comment]
PAGE_CONTAINER

In particular, the <xen:if bit, which I can't find on our end.

**Comment by ichpen** [comment]
It's another addon that's adding this modification. Apologies and thanks @jonw316 for looking into it.
