### ISSUE TITLE
UI.X Pro Theme

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1072]
I have already UI.X Pro Theme installed. So what we need install UI.X Pro Theme? What the different UI.X 2 vs UI.X Pro Theme?

![ScreenShot00968](https://user-images.githubusercontent.com/6899856/54997383-df034680-4fcb-11e9-86e1-ccdc82b16e0d.png)

**Comment by Ian-Hitt** [comment]
@Nirjonadda This is a question, not a bug report. I have messaged you about this in Slack.

**Comment by Nirjonadda** [comment]
@Ian-Hitt I can not access via Slack because Slack login no more working for ThemeHouse workspace.
