### ISSUE TITLE
Nodes - Categories latest posts showing differently in node grid

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#1074]
As per title. For a category:
![image](https://user-images.githubusercontent.com/34864926/52130401-efcdb680-2631-11e9-9748-08eac4c78597.png)

Whereas, for a standard forum:
![image](https://user-images.githubusercontent.com/34864926/52130417-fceaa580-2631-11e9-9e77-d14ad6e1aca1.png)

**Comment by jonw316** [comment]
This seems to be a difference between the node_list_category and node_list_forum templates in UI.X.

**Comment by tom-coward** [comment]
Seems to be resolved in latest UIX update?

**Comment by Ian-Hitt** [comment]
Correct, fixed in previous release.
