### ISSUE TITLE
Server error log UI.X PRO

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#1081]
Server error log
XF\CssRenderException: Error rendering template public:widget_EWRporta_features.less: ParseError: Unexpected input in public:widget_EWRporta_features.less on line 3509, column 62 (on or near line 3509) src/XF/CssRenderException.php:87
Generated by: Unknown account Apr 15, 2019 at 12:28 PM
Stack trace
 3506 | 
 3507 | 		.porta-features-media
 3508 | 		{
*3509*| 			position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 80;
 3510 | 			margin:  auto;
 3511 | 			width: ;
 3512 | 			height: ( - ( * 2));
------------

#0 src/XF/CssRenderer.php(408): XF\CssRenderException::createFromLessException(Object(Less_Exception_Chunk), 'public:widget_E...', '// Note that th...')
#1 src/XF/CssRenderer.php(342): XF\CssRenderer->renderToCss('public:widget_E...', '// Note that th...')
#2 src/XF/CssRenderer.php(250): XF\CssRenderer->renderTemplate('public:widget_E...', NULL)
#3 src/XF/CssRenderer.php(116): XF\CssRenderer->renderTemplates(Array, Array, Array)
#4 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#5 css.php(30): XF\CssWriter->run(Array, 58, 1, '4897eb74cb3b245...')
#6 {main}

-------------

Previous Less_Exception_Chunk: ParseError: Unexpected input in anonymous-file-0.less on line 3509, column 62
3507| 		.porta-features-media
3508| 		{
3509| 			position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 80;
3510| 			margin:  auto;
3511| 			width: ;
3512| 			height: ( - ( * 2)); - src/vendor/oyejorge/less.php/lib/Less/Parser.php:677
#0 src/vendor/oyejorge/less.php/lib/Less/Parser.php(621): Less_Parser->GetRules(NULL)
#1 src/vendor/oyejorge/less.php/lib/Less/Parser.php(449): Less_Parser->_parse()
#2 src/XF/CssRenderer.php(404): Less_Parser->parse('// Note that th...')
#3 src/XF/CssRenderer.php(342): XF\CssRenderer->renderToCss('public:widget_E...', '// Note that th...')
#4 src/XF/CssRenderer.php(250): XF\CssRenderer->renderTemplate('public:widget_E...', NULL)
#5 src/XF/CssRenderer.php(116): XF\CssRenderer->renderTemplates(Array, Array, Array)
#6 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#7 css.php(30): XF\CssWriter->run(Array, 58, 1, '4897eb74cb3b245...')
#8 {main}
Request state
array(4) {
  ["url"] => string(308) "/css.php?css=public%3AEWRporta.less%2Cpublic%3AEWRporta_articles.less%2Cpublic%3Aalnb_navigation.less%2Cpublic%3Amessage.less%2Cpublic%3Anotices.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Awidget_EWRporta_features.less%2Cpublic%3Aextra.less&s=58&l=1&d=1519483161&k=4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  ["referrer"] => bool(false)
  ["_GET"] => array(5) {
    ["css"] => string(200) "public:EWRporta.less,public:EWRporta_articles.less,public:alnb_navigation.less,public:message.less,public:notices.less,public:share_controls.less,public:widget_EWRporta_features.less,public:extra.less"
    ["s"] => string(2) "58"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1519483161"
    ["k"] => string(40) "4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by LukasWieditz** [comment]
This error is coming from the XenPorta add-on.

**Comment by joyfreak** [comment]
That would have made sense if I had XenPorta installed but don't and never have done.
