### ISSUE TITLE
XF:mod_tools_menu hooks messed up

### ISSUE THREAD

**Issue by jonw316** [Audentio/xf2theme-issues#1083]
```<!--[XF:mod_tools_menu:top]-->```
 is in too many places.

```<!--[XF:mod_tools_menu:bottom]-->```
 is in too few places.

PAGE_CONTAINER template.

**Comment by jonw316** [comment]
Also, "Reports" shows twice in Admin/Moderator menu on mobile if you have reported items.

**Comment by Ian-Hitt** [comment]
@jonw316 thats how XF works, not UI.X 🤷‍♂ 
<img width="556" alt="Screen Shot 2019-04-30 at 4 18 23 PM" src="https://user-images.githubusercontent.com/15836384/56994034-95c28b80-6b63-11e9-8f75-a66115a0ca5a.png">
