### ISSUE TITLE
Reply button on thread_view

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#1097]
Seems to open in a new page rather than jump to the quick reply at the bottom.

**Comment by Ian-Hitt** [comment]
This works for me as intended (jumps to bottom of page and focuses on the input). It only opens in new page if something stops it for some reason, which is the correct backup as well.

**Comment by joyfreak** [comment]
Hi, it doesn't jump on mine and I haven't touched anything? Is there an option or setting or permission or something?

**Comment by joyfreak** [comment]
Just to confirm, it's the same when I tried it on the Parent unedited theme!

**Comment by Ian-Hitt** [comment]
@jonw316 Can you look into why this may not be working?

**Comment by LukasWieditz** [comment]
This still happening for you? If so, disable history purging on page change in your browser console and check for errors when clicking the button.

**Comment by joyfreak** [comment]
Yes it's still happening. Feel free to take a look on my site.
