### ISSUE TITLE
.notices .uix_noticeIcon disappeared (UI.X Pro)

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#1103]
The (!) notice icon is no longer there. FYI, I checked the default parent theme and the same thing.

![notice icon](https://user-images.githubusercontent.com/43339306/57969970-1ca0a200-7973-11e9-9816-d25961333999.png)

**Comment by Ian-Hitt** [comment]
We added icon support for notices, so you can set an icon class when you create the notice. by default it uses "mdi mdi-information", but that won't work if you are using font awesome instead

**Comment by joyfreak** [comment]
I am using MDI. But those notices, "currently waiting for email notification" and the cookies one and the one that asks if you want desktop notifications are all default. Where and how would I add the icons for that?

**Comment by joyfreak** [comment]
I think you've misunderstood. mdi mdi-information is not working at ALL. It's not displaying on ANY notices. This is what this bug report was about.

**Comment by joyfreak** [comment]
Ah I just checked one of my custom notices and it looks like it could be broken as its displaying the phrases raw as seen in screenshot:
![notices](https://user-images.githubusercontent.com/43339306/58663317-22f42e00-8324-11e9-9c24-d1873eda25cc.png)
