### ISSUE TITLE
Flare - No divider between posts

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#1108]
Past Version:
![Flare_Posts_Diver](https://user-images.githubusercontent.com/32306910/58042604-c3ff0f80-7b00-11e9-804a-3684dccf162a.jpg)

Present Version: 
![image](https://user-images.githubusercontent.com/32306910/58042754-1c361180-7b01-11e9-84a8-97f25f155900.png)

**Comment by Ian-Hitt** [comment]
not a bug, definitely just a design choice.
