### ISSUE TITLE
Unable to load page fully - mobile devices

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#1139]
Reported by one of our customers using the Mobile-Friendly test as mentioned in the quote below:

> I ran the Mobile-friendly Tester for that site you linked and a bunch of other sites that I use XenForo and they all came back with a minor flag "unable to load page fully" but they all passed the main "Mobile-Friendly" test, so I don't feel too bad about the speed anymore. However, all those those sites I tested showed no issues with content being out of place though, which mine is being flagged for.
> 
> As a test, I reverted my site back to the default XenForo theme and ran the Mobile-Friendly test. It came back as mobile friendly and had no speed issues.
> 
> Once I revert back to my custom UI X Dark theme, it gives me the same two errors we have been running into this whole time. I'm very confident this is a theme issue, not a server one. As another test, I reverted my theme back to the default UI X Dark 2 theme, without my custom colors, logos, etc. It still came back with the same problems from the Mobile-Friendly Tester.
> 
> I don't have any ads on my site.

**Comment by Ian-Hitt** [comment]
Issue is resolved : https://search.google.com/test/mobile-friendly?id=y3loI6Lb_PcK6q9Cw26i8Q
