### ISSUE TITLE
[Holidays] Halloween holiday read/unread icons incompatible with Boo! theme

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#1142]
Icons included with the Halloween Holiday are being shown behind the read/unread icons included in the Boo! theme instead of being removed or made transparent.
<img width="196" alt="Screen Shot 2019-10-22 at 2 33 30 PM" src="https://user-images.githubusercontent.com/32306910/67324555-97995600-f4d9-11e9-96ae-0fa459363862.png">

**Comment by wleffert** [comment]
Updated themes to play nice with both Nodes & Holidays; Nodes now properly overrides Boo & Thankful, while Boo & Thankful icons will take priority over Holidays (given they are already holiday themed).
