### ISSUE TITLE
Two different Trending Views

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#1152]
I 'think' this is a UIX issue rather than a Trending issue but you let me know.

Clicking on the trending widget takes me to: /threads/trending (this has access to filters widget)
Clicking on forum->trending takes me to: /trending/threads.1/ (this has access to proper trending features such as trending position arrows)

All is all it's messy and confusing for the user to have 2 views.

**Comment by LukasWieditz** [comment]
This is for the most part intended. The trending view of the filters add-on grabs the trending thread configuration with the highest display order, and solely displays that one. While there is a couple of improvements that'll be made with the next patch, we don't have any intentions to use the trending view for these components.
