### ISSUE TITLE
Bug with FAB button when enabled, but no button is present

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#1156]
As per screenshot on mobile view with mobile tablist enabled the scroll arrows are hiding nicely behind the tab bar on the What's New view. 

Seem to be the same issue in some conversation views. Probably broken elsewhere too. 

![20200122_073510_edited](https://user-images.githubusercontent.com/5346876/72894914-50924b00-3cea-11ea-82d7-a62d03360f18.jpg)

**Comment by Ian-Hitt** [comment]
The necessary margin is added to the button when the fab bar is active, but if no button is present, then the margin is missed.
