### ISSUE TITLE
Conversation Reply Bug with Sidebar Position Left

### ISSUE THREAD

**Issue by Ranimara** [Audentio/xf2theme-issues#1157]
**Style Name:** UI.X 2

**Style Version:** 2.1.6.0.0

**UI.X Add-on Version:** 2.1.2 Patch Level 3

**XenForo Version:** 2.1.6 Patch 1

**Operating System (and Version):** Windows 10 

**Browser Name (and Version):** Google Chrome

**Can you replicate this issue on our demo for this theme?**
No

**Does this issue happen in the default XenForo style?**
No

**Summary of issue:** 
When the sidebar location is set to Left, and you have the new_profile_posts widget in the sidebar, when you reply to a conversation the reply loads at the bottom of the new_profile_post sidebar widget.  

Upon refreshing the conversation page, the conversation appears normally.  

I tested this on UI.X 2 with all other add-ons disabled with the only property overrides being to place the sidebar on the left and to remove the sticky sidebar (so I could actually see the bottom of the new_profile_posts widget).

**Detailed steps to reproduce the issue:**
1. Change sidebar location to left
2. Place new_profile_posts widget in sidebar
3. Reply to an existing conversation.  
4. Upon hitting the "reply" button, the reply block will be placed at the bottom of the new_profile_post sidebar widget.

**Upload any screenshots related to the issue below**
![conversation bug](https://user-images.githubusercontent.com/37903989/72912328-79760880-3d09-11ea-8759-f3ffa9f36086.png)

**Comment by LukasWieditz** [comment]
I'm not able to replicate this. Switching the sidebar position to left and posting inserts the post at the end of the post container as expected.
https://gfycat.com/HarshScholarlyIncatern

**Comment by LukasWieditz** [comment]
This has been fixed by XenForo.
