### ISSUE TITLE
Multi-quotes is being inserted within the new profile posts reply box instead of thread reply box when the sidebar is set to the left

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#1158]
Style Name: UI.X 2

Style Version: 2.1.6

UI.X Add-on Version: 2.1.2 Patch Level 3

XenForo Version: 2.1.6 Patch 1

Operating System (and Version): Windows 10

Browser Name (and Version): Version 79.0.3945.130 (Official Build) (64-bit)

Can you replicate this issue on our demo for this theme? Yes

Does this issue happen in the default XenForo style? No

Summary of issue:
When multi-quoting conversations and inserting them on ThemeHouse based themes, the multi-quotes are inputted in the new profile posts reply box instead of the thread reply box.

Detailed steps to reproduce the issue:

Insert the New profile posts widget within Thread view: Sidebar. Also, have the sidebar set to left and not right.

Enable multi-quote within Messages -> Go to a conversation with a few thread posts, click +Quote, and then hit Insert Quotes. You'll then see they are not placed within the thread reply box, only the profile post box.

Upload any screenshots related to the issue below

**Comment by LukasWieditz** [comment]
This is unrelated to our styles. https://xenforo.com/community/threads/multi-quote-insert-inserts-into-first-editor-on-page-rather-than-current-editor.175744/
