### ISSUE TITLE
[UIX Pro] - SyntaxError

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1160]
SyntaxError: unexpected token: identifier

![ScreenShot00114](https://user-images.githubusercontent.com/6899856/77206966-82f8d280-6af8-11ea-873b-e55ebed7070b.png)

**Comment by Nirjonadda** [comment]
uncaught exception: Error: init not called with valid version

![ScreenShot00115](https://user-images.githubusercontent.com/6899856/77207702-5c3b9b80-6afa-11ea-9134-d0515f23f50e.png)

**Comment by LukasWieditz** [comment]
Neither of those errors appears to be coming from one of our themes.
