### ISSUE TITLE
[UI.X Pro] Subforum Node Icons lacking unread state background color

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1162]
@LukasWieditz from [previous](https://github.com/Audentio/xf2addon-issues/issues/2058) bug fix, now no more icon show for unread mark and read mark wrong icon show in forum list but forum view node icon showing correctly.

See here: https://gfycat.com/scaredjovialfantail

**Comment by wleffert** [comment]
Updated styling to default with primary color selector on unread state for sub-node icons.

**Comment by Nirjonadda** [comment]
@wleffert This issue does not fixed with UI.X Pro Version 2.1.9.0.0 update?

**Comment by wleffert** [comment]
> @wleffert This issue does not fixed with UI.X Pro Version 2.1.9.0.0 update?

I just tested it again and confirmed the changes are there; Would you mind putting through a ticket here and sending your login credentials via https://onetimesecret.com - https://www.themehouse.com/contact

I'll need to look through your styles to see what's overriding the new code.

**Comment by Nirjonadda** [comment]
@wleffert Ticket done.
