### ISSUE TITLE
[UI.X Pro] - Individual Boxed for Message user info

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#1165]
Please can you add SP option for Boxed or Individual Boxed for Message user info?

Example:

![ScreenShot00245](https://user-images.githubusercontent.com/6899856/79354601-e7af1d80-7f3c-11ea-8777-3a380846f3f0.png)

**Comment by mugua** [comment]
@Nirjonadda  your website shutdown now?

**Comment by Ian-Hitt** [comment]
This is something I would prefer to leave to customizations as it wouldn't be used frequently enough to justify a style property for it.
