### ISSUE TITLE
InlineModBar issue within conversations 

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#1169]
Reported by [Joe Link](https://xenforo.com/community/threads/ui-x-2-paid.137944/post-1424001) on XenForo

Style Name: iO/iO Dark

Style Version: 2.1.8.1.0 

UI.X Add-on Version: 2.1.2 Patch Level 4 

XenForo Version: 2.1.9

Operating System (and Version): iOS 13.4.1

Browser Name (and Version): Google Chrome - 81.0.4044.124

Can you replicate this issue on our demo for this theme? Yes

Does this issue happen in the default XenForo style? No

Summary of issue: 
Click the conversation link, select a couple conversations, and the inlineModBar doesn't appear at the bottom of the page (it's hidden behind the conversation list).

Detailed steps to reproduce the issue:
Visitor tabs location (mobile) set to tab bar and Enable sticky form submit rows enabled. Click the conversation link, select a couple conversations, and the inlineModBar doesn't appear at the bottom of the page (it's hidden behind the conversation list).

Upload any screenshots related to the issue below
![0728a535180b95691c3075d1ff14ace9](https://user-images.githubusercontent.com/32306910/81422374-7d8f3000-9118-11ea-857a-10e41232ef5c.gif)

**Comment by BigIron5** [comment]
Quick note, we use regular UI.X 2 theme, not iO. I took that screen cap using your demo site :)
