### ISSUE TITLE
Overlay Blur Effect Doesn't Blur

### ISSUE THREAD

**Issue by wleffert** [Audentio/xf2theme-issues#1171]
Style Name: All (anything based on UIX)

Style Version: 2.1.9.0.0

UI.X Add-on Version: 2.1.2 Patch Level 4

XenForo Version: 2.1.9

Operating System (and Version): Windows 10 build 18362.836

Browser Name (and Version): Chrome 81.0.4044.138, Firefox 76.0.1

Can you replicate this issue on our demo for this theme? n/a

Does this issue happen in the default XenForo style? n/a

Summary of issue: filter: blur that gets applied only blurs the overlay, and not the sub-contents (also doesn't inherit blur radius, instead blurring 1px by default)

Detailed steps to reproduce the issue: Enable blur effect on overlay.

Upload any screenshots related to the issue below

**Comment by Ian-Hitt** [comment]
XF added their own blur style property, so deleting this one.
