### ISSUE TITLE
invert success colors for dark themes

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#1193]
dark themes should use dark background, light text. especially apparent on message voting
![Screen Shot 2020-09-15 at 3 36 45 PM](https://user-images.githubusercontent.com/15836384/93262093-46392b80-f769-11ea-827a-e1d74225323a.png)

**Comment by daltonp** [comment]
This is still being experienced even with the latest theme files you sent this morning @Ian-Hitt
