### ISSUE TITLE
XF 2.2 RC1 - Border issues on some styles

### ISSUE THREAD

**Issue by wleffert** [Audentio/xf2theme-issues#1214]
Vote component needs border-left swapped to border-right.

![image](https://user-images.githubusercontent.com/54987757/93641982-eb027580-f9c2-11ea-8f40-3572ee3482b9.png)

Also, mobile looks a little odd, missing borders in some areas in threads.

![image](https://user-images.githubusercontent.com/54987757/93642419-b0e5a380-f9c3-11ea-8e72-422ae7d63b96.png)

Issues applies to: Westlake, Drift, UIX Classic

**Comment by Ian-Hitt** [comment]
- [ ] - westlake
- [ ] - drift
- [ ] - classic
