### ISSUE TITLE
Media page sidebar on right 

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#125]
Do they use like the generic sidebar classes, but wondering if we should. Then we can just use a page:container sidebar to left on that page. And make it a style property. Nice and clean.

**Comment by Ian-Hitt** [comment]
@mikecreuzer no, it is a different XF:sidenav component, and actually works quite a bit differently.

**Comment by mikecreuzer** [comment]
Can't it be placed in sidebar? Worth a try so we don't have to components doing the same thing. Moving it canvas is a separate action

**Comment by JakeBooher** [comment]
No, we can't change something like this, it'll break add-ons that do template modifications on that area

**Comment by Ian-Hitt** [comment]
Scope CSS to work with Style Property

**Comment by Ian-Hitt** [comment]
@mikecreuzer sbdear and sidenav are different components, and both can be on the same page.
<img width="1632" alt="screen shot 2017-11-15 at 10 41 35 am" src="https://user-images.githubusercontent.com/15836384/32848237-907152ac-c9f1-11e7-8975-aea4a362de7e.png">
