### ISSUE TITLE
Like bug or not idk, but not good

### ISSUE THREAD

**Issue by Rezanans-wow** [Audentio/xf2theme-issues#1254]
Style Name: Legend

Style Version: 2.2.0.2.0

UI.X Add-on Version: Lasted

XenForo Version:  v2.1.10 Patch 2

Operating System (and Version): Ubuntu 18.04

Browser Name (and Version): Firefox last & Google chrome last

Can you replicate this issue on our demo for this theme? - I see it on DEMO too.

Does this issue happen in the default XenForo style? - No

Summary of issue: I see underlining all links, and usernames! Screenshots pinned.

Detailed steps to reproduce the issue: Nothing
Upload any screenshots related to the issue below
![Screenshot_193](https://user-images.githubusercontent.com/49691442/95689670-0d329080-0c1b-11eb-9b7a-de8d79081cb6.png)

If it setting, or css can you send it here? I need resolve it faster :)

**Comment by wleffert** [comment]
@Rezanans-wow - that's actually part of the design for Legend and is intentional. You should be able to disable that via Appearance -> Style Properties -> Page Setup and unchecking "Underline" under the Links section.
