### ISSUE TITLE
UI.X - Online statistics widget needs some UI improvements

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#1263]
As reported by one of our customers on a ticket, this seems to be happening on all of our themes. It happens on the latest theme version and XenForo which is 2.2.1.0.0 
![image](https://user-images.githubusercontent.com/32306910/96595698-9304aa80-12b1-11eb-8a69-f64d2e02548a.png)

┆Issue is synchronized with this [ClickUp ](https://app.clickup.com/t/guqphy) by [Unito](https://www.unito.io/learn-more)

**Comment by Ian-Hitt** [comment]
Can't replicate, closing.
