### ISSUE TITLE
Breadcrumb - mobile view -(<480px) Additional Chevron showing

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#144]
![image](https://user-images.githubusercontent.com/6074069/32516020-d36a331a-c3f9-11e7-9a2d-d787156e8816.png)

**Comment by Ian-Hitt** [comment]
@arm5ky This is intentional (although the chevron needs to be larger.) It switches from being a breadcrumb to being a back button instead.
