### ISSUE TITLE
uix_hideSingleCrumb  not working

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#145]
ticked but still shows just home top breadcrumb

**Comment by Ian-Hitt** [comment]
This is a bit misleading in the description. If there is the sidebar collapse trigger, or there are xf:pageactions in the breadcrumb, then it will not hide. It will only hide if there is one crumb, AND there is no other content.

**Comment by arm5ky** [comment]
I'd presumed that, so had tested with no sidebar trigger:

![image](https://user-images.githubusercontent.com/6074069/32526164-d007dbc0-c41f-11e7-8a2a-19bad2792433.png)
