### ISSUE TITLE
Categories in Resource navmenu hight 

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#147]
![image](https://user-images.githubusercontent.com/6074069/32581224-e18ca5c6-c4e0-11e7-97c6-11fe28993801.png)

Far too much space between categories

**Comment by Ian-Hitt** [comment]
XenForo is structuring their markup for their add-ons incorrectly. I'm not sure why, but they aren't using the block system at all for this sidebar.

**Comment by Ian-Hitt** [comment]
One solution may to be scope all of their new markup to the block systems style properties. Another would be to replace their markup/class names with the correct block equivalent.

**Comment by mikecreuzer** [comment]
Perhaps just create a bug with XenForo, then just add some quick CSS to fix it. Just put a comment here with reasoning for why we had to add ugly CSS.
