### ISSUE TITLE
Current visitors - border around tabs

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#149]
Why a border around tabs? Other tabs do not have border.

![image](https://user-images.githubusercontent.com/6074069/32599432-6ee01d38-c534-11e7-8c5d-9678c676f9a2.png)

**Comment by Ian-Hitt** [comment]
Tabs does not have a border radius here, all block containers do. It is inside a component that has a border radius. all tabs that are within block-container have this. see search as another example.
