### ISSUE TITLE
Thread view - 8 additional queries

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#151]
Is this running more than once?

`SELECT `xf_user`.*
FROM `xf_user`

WHERE (`xf_user`.`user_id` = 0)

LIMIT 1`

**Comment by JakeBooher** [comment]
@arm5ky I can't replicate this, do you have any other add-ons installed?

**Comment by JakeBooher** [comment]
Alright, have confirmed this to be related to the new posts widget in XenForo, and was able to replicate it in a stock XF install

https://xenforo.com/community/threads/duplicated-query-on-new-posts-widget.137280/
