### ISSUE TITLE
Search Position Tablinks

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#153]
![screenshot 2017-11-09 14 11 44](https://user-images.githubusercontent.com/6074069/32609640-38084b2c-c558-11e7-9f25-cc207366297a.png)

**Comment by Ian-Hitt** [comment]
@arm5ky Although this is not ideal, it is actually intended. You have a white search input on a white background for section links. Either change the background color of search in the style property, or change the tablinks background color.
