### ISSUE TITLE
Active tab on UI.X 2 for forums doesnt look good

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#177]
<img width="302" alt="screen shot 2017-11-14 at 5 21 12 pm" src="https://user-images.githubusercontent.com/1217271/32810374-3ce96b10-c960-11e7-96bf-0369d9886622.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer this must be an old version?

**Comment by mikecreuzer** [comment]
No it's the live version

**Comment by Ian-Hitt** [comment]
@mikecreuzer I closed this because I fixed it. Don't re-open again please.

**Comment by mikecreuzer** [comment]
<img width="201" alt="screen shot 2017-11-15 at 2 15 56 pm" src="https://user-images.githubusercontent.com/1217271/32858013-8fbc22e2-ca0f-11e7-96a2-c95d6d242c70.png">
