### ISSUE TITLE
Looks like node stats are based on media query as opposed to node grid class (element query)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#178]
<img width="922" alt="screen shot 2017-11-14 at 5 28 01 pm" src="https://user-images.githubusercontent.com/1217271/32810581-388467cc-c961-11e7-9c0f-75c96d654abb.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer Not exactly, this styling is coming from default XenForo. Needs to be disabled and overwritten for nodes.
