### ISSUE TITLE
Node on hover with image shows gray, should just change shadow depth really

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#179]
<img width="602" alt="screen shot 2017-11-14 at 5 29 40 pm" src="https://user-images.githubusercontent.com/1217271/32810618-6a5fc160-c961-11e7-98cf-8d3a5841c0ac.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer this is a style property, so can be changed at that level.

**Comment by Ian-Hitt** [comment]
@mikecreuzer change of hart, i'm going to disable that style property for nodes i guess. Only way to have it nice out of the box. Will put that in the description

**Comment by mikecreuzer** [comment]
Doesnt seem to work when I enable clickable nodes

**Comment by mikecreuzer** [comment]
Nothing seems to change on hover. Please confirm before closing.

**Comment by Ian-Hitt** [comment]
@mikecreuzer it is a fix on TH Nodes, so it is not available in this update

**Comment by mikecreuzer** [comment]
Is it fixed in that product? Is that product on your install?
