### ISSUE TITLE
Scroll on account dropdown with status autofocus

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2theme-issues#180]
May want to not auto-focus the status dropdown on mobile since the menu has overflow-y: scroll and the status input may not be visible.  Alternatively, could be resolved canvas visitor tabs.

**Comment by kylerc** [comment]
https://xenforo.com/community/threads/quick-look-at-ui-x-2.126555/page-11#post-1191767

**Comment by Ian-Hitt** [comment]
@kylerc this is XF default behavior. Reporting to XenForo.
