### ISSUE TITLE
Sticky kit broken in sticky navigation

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#196]
Sticky kit breaks when the height of the sticky container is the same height as its parent container. The issue can be seen on UI.X 2 pro logged out.

After fixing, remove "uix_headerContainer--stickyFix" div in page_container, and remove styling in uix.less regarding this and ".uix_headerContainer"

**Comment by mikecreuzer** [comment]
Solved when we do https://github.com/Audentio/xf2theme-issues/issues/571 so closing
