### ISSUE TITLE
The bold Roboto font doesn't look correct

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#212]
- In Chrome bold text looks a little blurred
- In Firefox the bold Roboto font is almost unrecognizable

The reason this occurs is because the web font version of Roboto uses 700 for bold. Take a look at [the website](https://fonts.google.com/specimen/Roboto?selection.family=Roboto), set the size to 13px and look at the ninth preview. That's how Roboto bold is supposed to look.

If you want the font to look correct across all browsers then you've got to use 700. Even Google uses it across many of their own websites. Here's a few examples.

https://material.io/guidelines/ - The sidebar
https://design.google/library/design-notes-podcast-episode-2/ - Everything that's bold in the post
https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher - The author, category and any bold text in an apps description

**Firefox (Windows) without 700:**
![firefox_before](https://user-images.githubusercontent.com/26636634/33150223-711ad480-cfca-11e7-9de6-28677873308e.png)

**Firefox (Windows) with 700:**
![firefox_after](https://user-images.githubusercontent.com/26636634/33150230-74aa0b66-cfca-11e7-8e42-c0d8f0b7036d.png)

**Chrome (Windows) without 700:**
![chrome_before](https://user-images.githubusercontent.com/26636634/33150476-848c3698-cfcb-11e7-947f-2af387297bd4.png)

**Chrome (Windows) with 700:**
![chrome_after](https://user-images.githubusercontent.com/26636634/33150478-876dffe0-cfcb-11e7-8335-1646e19f6c63.png)

**Google fonts website:**
![firefox_google](https://user-images.githubusercontent.com/26636634/33150241-811fc976-cfca-11e7-9997-d2e0a9cdfc00.png)

**Comment by Ian-Hitt** [comment]
@nsaneman I'm not sure that I agree on this one. Sadly, we use Mac, and Robot looks very pretty. But on a Windows machine with less than ideal screen resolution, even 700 looks a bit blurry (equally as blurry I'd say.) Material design does say that 500 (medium) is the correct font weight

https://material.io/guidelines/style/typography.html#typography-styles

<img width="892" alt="screen shot 2017-11-24 at 1 31 04 pm" src="https://user-images.githubusercontent.com/15836384/33222312-ec01984e-d11b-11e7-8ea2-b13e8af4ac23.png">

**Comment by nsaneman** [comment]
@Ian-Hitt There's an underlying issue here though. That being that XenForo asks for 700 for bold when it should be 500 if you're targeting medium.

```
b {
	font-weight: 500;
}
```

If you add the above then you might think it'll fix the problem, but it won't. You'll quickly find out that it's difficult to see the difference between medium and regular text. Why? **Because Google never mixes medium with regular in sentences**. That's why they're using 700 in sentences on their own websites.

**Comment by nsaneman** [comment]
**The mismatch (XF setting 700 when 500 is the maximum)** 
![mismatched](https://user-images.githubusercontent.com/26636634/33224718-56ab634e-d164-11e7-9122-f4aa150f6f1c.png)

**The true version of medium (500)**
![true_medium](https://user-images.githubusercontent.com/26636634/33224735-863a4580-d164-11e7-906c-6b8d45e19e4a.png)

**The corrected bold version (Roboto supporting 300, 400, 500 & 700)**
![true_bold](https://user-images.githubusercontent.com/26636634/33224739-937157ac-d164-11e7-8c09-0fc78d597344.png)

The last one looks the best as the text is clear and you can easily see the bold font. That's why Google uses 400 (regular) and 700 (bold) in sentences.

**Comment by nsaneman** [comment]
@Ian-Hitt Here's another example.

https://www.google.com/policies/technologies/ads/

h1, h2, h3, h4, em, i = 500
b = 700

See what I mean? Bold is always 700.

**Comment by mikecreuzer** [comment]
Agreed @nsaneman

**Comment by Ian-Hitt** [comment]
@mikecreuzer @nsaneman updatedt the Style Property to use 700. Let me know @mikecreuzer if you want to change back later.
