### ISSUE TITLE
Add an option to change the FAB's behaviour

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#217]
Could an option be added to make the FAB behave exactly the same as it does in your Material theme? 

- When viewing a list of threads if I press the FAB then it should scroll up and set the focus on the title text area
- When viewing a thread or conversation if I press the FAB then it should scroll down and set the focus on the editor
- If a person isn't registered redirect them to the registration page

I really don't like the current setup as it'll redirect you away from the conversation. That means that you can't see what other people are saying at a glance.

**Comment by kylerc** [comment]
@nsaneman good suggestions, I've added this to the next update.  Thanks :).
