### ISSUE TITLE
Remove the navbar title when using a mobile device

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#218]
When at 480px or less remove the navbar title as there isn't always enough room for it.

![Navbar title](https://user-images.githubusercontent.com/26636634/33154618-66ef1766-cfe1-11e7-9be1-c22765fc3d63.png)

I'm aware that there's an option to disable this completely. Maybe it's worth adding a breakpoint to solve this issue for phones though?

**Comment by Ian-Hitt** [comment]
Removing under responsiveNarrow (480px) by default
