### ISSUE TITLE
Profile information can cause display issues

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#219]
Set a stupidly long location or website and then view a thread.

![iphone_issue](https://user-images.githubusercontent.com/26636634/33155136-adc0e120-cfe5-11e7-8c9b-adc8ab98b701.png)

The wrapping you're using here will always cause issues depending on how long a persons profile information is and how many posts, likes and trophies they've got.

The solution is simple. Remove the whole thing when you're at 650px or less. Devices at these low resolutions can access the same information by clicking or pressing on the avatar anyway, so nothing is really lost.

**Comment by Ian-Hitt** [comment]
@nsaneman that isn't a fix as much as it is a band-aid. For example, there is a Classic postbit style property that would cause the issue at desktop. Will consider other alternative fixes.

**Comment by Ian-Hitt** [comment]
The issue here is that uix_messageContent needs a max-width: 100%. However, it does not take into account its sibling elements (flexbox bug.) The fix is to add min-width: 0;
