### ISSUE TITLE
Remove rounded corners from tabs when the logo block is disabled

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#222]
**Before:**
![tab_suggestion_before](https://user-images.githubusercontent.com/26636634/33186821-a3119e14-d084-11e7-8d3f-565dc93b67dd.png)

**After:**
![tab_suggestion_after](https://user-images.githubusercontent.com/26636634/33186824-a6032ab6-d084-11e7-9a02-9fdca0e7b544.png)

Similary, you'll need to make sure #221 fits correctly.

**Comment by Ian-Hitt** [comment]
@kylerc Smart border radius function here? We only want to remove the border radius if the navtabs touch the top AND bottom of the sticky nav bar. Example:

<img width="665" alt="screen shot 2017-11-24 at 1 37 04 pm" src="https://user-images.githubusercontent.com/15836384/33222414-925021a2-d11c-11e7-9c51-a688ddf5828b.png">

We wouldn't want to remove it here.

**Comment by Ian-Hitt** [comment]
If not performant to do in JS, then should probably just leave it alone. Forcing it is worse, IMO.

**Comment by kylerc** [comment]
@Ian-Hitt wouldn't be able to use the smart border radius function unfortunately.  It isn't setup for this type of situation.  But I tend to think that removing the radius makes more sense?  I believe that's what we did for UI.X 1.  As long as the selector isn't very specific, this should still be fairly easy to customize (your rounded example already requires custom CSS, a little most isn't that much harder).

**Comment by Ian-Hitt** [comment]
Not sure the best way to handle this. can't simply remove it for sticky because it can happen on non-sticky as well. But on on-sticky, the bar height could be taller than the nav tab height, so can't remove it there either.
