### ISSUE TITLE
Select the shape of online markers

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#223]
As we can change the shape of the avatar we should also be able to change the shape of the online marker.

Personally I would prefer circular avatars with a circular online marker, much like it was in your original Material theme.

**Comment by Ian-Hitt** [comment]
@nsaneman Seems to me thats a circle here would always be best. We are also considering an add-on that would change the state for user status, which wouldn't fit here.

Updated the default styling to be a 10x10 circle.

**Comment by nsaneman** [comment]
@Ian-Hitt As it's circular again now I guess you could make the marker pulse?

https://github.com/Audentio/xf2theme-issues/issues/30
