### ISSUE TITLE
Tabs don't stay in position when resizing the browser

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#225]
![Broken tabs](https://user-images.githubusercontent.com/26636634/33190127-478af32a-d0a1-11e7-8b2f-3aba14c56aeb.gif)

Have the window small enough to display the menu icon, refresh and then resize the window.

Tabs work perfectly in your Material theme, but they seem really buggy in UI.X 2. I'm sure you'll fix it though.

**Comment by Ian-Hitt** [comment]
Replicated in Firefox 57 on Windows

**Comment by Ian-Hitt** [comment]
XF bug, reporting it with them.
