### ISSUE TITLE
TH Nodes node footer support for TH Bookmarks (stateful bookmark icon next to create thread)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#233]
Putting it here @Ian-Hitt just because Id rather you do the markup in default theme and make sure it works in UI.X as well ofc.

**Comment by Ian-Hitt** [comment]
@JakeBooher I presume this needs to be done in TH Bookmarks or in UI.X add-on?

**Comment by Ian-Hitt** [comment]
@JakeBooher says needs to be done in TH Nodes. moving to xf2addons-issues repo
