### ISSUE TITLE
Width Toggle (finish)

### ISSUE THREAD

**Issue by dprock** [Audentio/xf2theme-issues#25]
Done in the style and in the add-on. Just needs to be connected

**Comment by mikecreuzer** [comment]
This is far too buggy. @Ian-Hitt feel free to assign to @kylerc if you prefer.

A few common issues (some in UIX 1 as well)

- [ ] Sometimes doesnt save for guests
- [ ] Sometimes have to click twice
- [ ] Animation doesn't play well with other sticky components
