### ISSUE TITLE
UI.X2 - Editor Active Buttons invisible

### ISSUE THREAD

**Issue by Katsulynx** [Audentio/xf2theme-issues#267]
BB Code Buttons in the editor that have a toggle function will appear invisible when activated.
https://my.mixtape.moe/wnskkf.mp4

This is the css rule that is responsible for it:
```
.fr-toolbar .fr-command.fr-btn.fr-active,
.fr-popup .fr-command.fr-btn.fr-active {
  color: #f7f8f9;
  background: transparent;
}
```

It's located in `editor_base.less` as far as I have been able to tell and should probably be overridden.

**Comment by Ian-Hitt** [comment]
fixed
