### ISSUE TITLE
If XF branding is removed, pipe character still on our copyright

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#280]
<img width="360" alt="screen shot 2017-12-05 at 1 21 53 pm" src="https://user-images.githubusercontent.com/1217271/33626131-4fcc66aa-d9bf-11e7-8453-4a4cefe3aa3f.png">

**Comment by JakeBooher** [comment]
Not a whole lot we can do here, it's possible that other add-ons add branding that shows up before ours as well

**Comment by mikecreuzer** [comment]
@jakeb can't we just remove the pipe altogether?

**Comment by mikecreuzer** [comment]
@jakebooher

**Comment by Ian-Hitt** [comment]
@mikecreuzer fixed, now only shows if there is any copyright before ours.
