### ISSUE TITLE
UI.X 2 - Pageaction shifts page title

### ISSUE THREAD

**Issue by Katsulynx** [Audentio/xf2theme-issues#291]
The presence of a pageaction button pushes the page title a bit to the bottom.
https://my.mixtape.moe/fayxbf.mp4

**Comment by Ian-Hitt** [comment]
The titlebar component is centered, and since the button is larger than the text, the text shifts to be centered with the button. This is intended behavior, but can be overwritten by custom CSS if you do not desire it.
