### ISSUE TITLE
UI.X 2 - Default Image Path not relative

### ISSUE THREAD

**Issue by Katsulynx** [Audentio/xf2theme-issues#292]
It appears the default image path is not set relative to the current page. Turning on "Use full friendly URLs" in the XenForo options breaks images on all pages except the homepage in Chrome for Win10.

I fixed it by appending a slash at the beginning of the image path in the style properties, but I have a feeling that this might not work for users that don't have their XenForo installation on their URL root.

**Comment by Ian-Hitt** [comment]
Duplicate, closing.
