### ISSUE TITLE
 Latest profile posts

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#310]
Latest profile posts In the whats new,.. looks rather gappy as seen in the screenshot (IN IE and Chrome)
![gappy](https://user-images.githubusercontent.com/34584920/34059727-1ca8bf64-e1d8-11e7-871e-ca74b88a5cef.png)

**Comment by Ian-Hitt** [comment]
This is simply the styling of the Reactions add-on (the bar has a lot of margin/padding. Moving to the add-ons issue repo as a styling suggestion.
