### ISSUE TITLE
Text out of box

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#311]
The "There are no threads in this forum." seems out of the box. As seen in screenshot.
![out](https://user-images.githubusercontent.com/34584920/34059736-30912cf0-e1d8-11e7-91f2-c71c083e4d3b.png)

**Comment by Ian-Hitt** [comment]
Do you still have this issue. I cannot replicate on our dev demo.

**Comment by legendofmir3** [comment]
Yes still an issue.


________________________________

**Comment by Ian-Hitt** [comment]
Can you replicate this in an uncustomized version of UI.X?

**Comment by legendofmir3** [comment]
This wasn’t a style issue was an addon. Fixed now thank you!
