### ISSUE TITLE
More UIX Icons Navigation

### ISSUE THREAD

**Issue by McAtze** [Audentio/xf2theme-issues#312]
It would be great if there is a chance for more icons. If i change the navigation to insert the help tab, i must change the uix.less insert the following part.. 

`&[data-nav-id="help"]:before {<xf:macro name="content" template="uix_icons.less" arg-icon="help" />}`

**Comment by Ian-Hitt** [comment]
Hello,

Sadly at one point XenForo had a built-in way to add icons to navigation items. However, they removed it, claiming that it should be done in CSS. Therefore, adding new icons must be done in CSS custom every time.

**Comment by mikecreuzer** [comment]
@Ian-Hitt is this thoroughly covered in documentation?

**Comment by mikecreuzer** [comment]
Checked, its not. There needs to be code showing how to add custom icons to nav (with CSS I assume)

**Comment by Ian-Hitt** [comment]
@mikecreuzer will make new issue regarding documentation edits needed. Feel free to add any/all things there.

**Comment by Ian-Hitt** [comment]
https://github.com/Audentio/xf2theme-issues/issues/319
