### ISSUE TITLE
navigation alignment off when only some items have an icon.

### ISSUE THREAD

**Issue by Pacifiquateure** [Audentio/xf2theme-issues#321]
Hello,

It's not aligned:
![capture d ecran 2017-12-15 a 17 40 31](https://user-images.githubusercontent.com/34781128/34314348-0d0d4a70-e773-11e7-9592-155ed3c8036b.png)

Titles that are too long exceeds the box (and forum) which makes appear a scrollbar at the bottom of the screen:
![capture d ecran 2017-12-09 a 00 03 45](https://user-images.githubusercontent.com/34781128/34314364-3914c88c-e773-11e7-95c3-428a6c7e937a.png)

**Comment by Ian-Hitt** [comment]
We are aware of, and have fixed, the second issue. I will look into the navigation alignment.
