### ISSUE TITLE
Thread fields badly styled

### ISSUE THREAD

**Issue by tommyac** [Audentio/xf2theme-issues#322]
As per title:
![image](https://user-images.githubusercontent.com/34864926/34360507-6119556c-ea59-11e7-94bf-d56ba8f6ac8a.png)

**Comment by tom-coward** [comment]
Finding same issue in reports centre now:
![image](https://user-images.githubusercontent.com/34864926/40516262-e75a124c-5fa7-11e8-95f5-36f42577490c.png)
