### ISSUE TITLE
Remove the autofocus from login inputs

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2theme-issues#333]
Specifically in sliding panel dropdown.  Gets focused when the page loads.  See Ticket #9672.

**Comment by nsaneman** [comment]
@kylerc You don't want to completely remove autofocus, since that's just annoying. Instead you want to prevent the focus from being set until the sliding panel is displayed. This works perfectly with your XF1 Material theme.

**Comment by kylerc** [comment]
@nsaneman ya good point, that would make more sense.  When we fix this we'll make that change.

**Comment by kylerc** [comment]
Will be fixed in next public release
