### ISSUE TITLE
UI.X 2 Dark - Unreadable text when inputting tags

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#338]
![uix_bug_1](https://user-images.githubusercontent.com/32306910/34498214-3f67c94a-efc6-11e7-80d4-292cdbfdf7f2.png)

**Comment by lilalien** [comment]
I'm seeing this as already fixed, can someone confirm?

**Comment by Ian-Hitt** [comment]
Yes, this has already been fixed.
