### ISSUE TITLE
Editor toolbar isn't working correctly

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#339]
I mentioned this directly to @Ian-Hitt 12 days ago, but the bugs still in UI.X 2.0.1.1.0.

https://demo.themehouse.com/xf2/themes/index.php

Press a button on the editor toolbar and you'll see that it doesn't change the color, so you don't know for sure if a buttons enabled or not.

The issue with is with **btn-active-text** as it'll output as #F7F8F9 even though it should be #1E88E5. Manually setting "@btn-active-text: #1E88E5;", "@btn-active-hover-text: #1E88E5" and "@btn-active-selected-text: #1E88E5" totally fixes the problem.

**Comment by Ian-Hitt** [comment]
@nsaneman you are referring to the BB Code editor, correct? I am not able to replicate the issue on my demo.

**Comment by nsaneman** [comment]
@Ian-Hitt Using your own website with either Chrome or Firefox on Windows.

![editor_bug](https://user-images.githubusercontent.com/26636634/34888715-3afa4b4e-f7c3-11e7-8b91-ba9c0cc56003.gif)

**Comment by nsaneman** [comment]
@mikecreuzer Since you commented on #341, can you also replicate this one on Windows?

**Comment by nsaneman** [comment]
This isn't a problem after updating to 2.0.1.2.0.
