### ISSUE TITLE
Moving node backgrounds

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#341]
https://demo.themehouse.com/xf2/themes/index.php

Put your cursor onto something like the news & announcements node.

**Comment by Ian-Hitt** [comment]
Unable to replicate at this moment. I believe it was fixed with the  last TH Nodes update.

**Comment by mikecreuzer** [comment]
Can confirm this.

**Comment by mikecreuzer** [comment]
@Ian-Hitt @kylerc not sure on this. Happens on Windows machines

**Comment by JakeBooher** [comment]
Moved to Audentio/xf2addon-issues#119

**Comment by Ian-Hitt** [comment]
Class wasn't being added. Was fixed in last update of TH Nodes
