### ISSUE TITLE
Search position Navigation (left) broken

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#350]
My settings:

![image](https://user-images.githubusercontent.com/6074069/34613905-780cd6ba-f227-11e7-9e98-0d87448c41c0.png)

Output:

![image](https://user-images.githubusercontent.com/6074069/34613939-99d3f094-f227-11e7-81cc-bb5a159d9c84.png)

**Comment by Ian-Hitt** [comment]
position absolute issue. Probably best to add position absolute inline via JS and remove it after animation. If doing this, remove this code form uix.less

```
		<xf:if is="property('uix_searchIconBehavior') == 'expandMobile'">
			@media (max-width: @xf-responsiveMedium)  {
				position: absolute;
			}
		<xf:elseif is="property('uix_searchIconBehavior') == 'expand'" />
			position: absolute;
		</xf:if>
```
