### ISSUE TITLE
Forum Index Sidebar "Start Topic" intro message lost its styling on UI.X Dark!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#364]
Included a screenshot, the box is completely missing its previous styling!
![ui-x-start-topic-sidebar-box-bug](https://user-images.githubusercontent.com/35111972/34794580-203a27ae-f61d-11e7-8030-8352abc7dd16.png)

**Comment by Ian-Hitt** [comment]
This is a bug in XenForo and is supposed to be fixed in the next release.

**Comment by lilalien** [comment]
May I ask where this might be stated?

I don't see any upcoming fix for this:
https://xenforo.com/community/threads/add-on-style-properties-arent-kept.138913/

As of yet. Just a vague reference to a possible bug here (and that they'd have to confirm it):
https://xenforo.com/community/threads/add-on-style-properties-arent-kept.138913/post-1202530

However, it got marked as "As Designed" and such, so I'm not seeing where it was confirmed a fix would be forthcoming?

Just curious...
Thanks!
