### ISSUE TITLE
UI.X Pro: Logo too large, max-height should be 30-32px

### ISSUE THREAD

**Issue by nikkiradloff** [Audentio/xf2theme-issues#366]

**Comment by Ian-Hitt** [comment]
@nikkiradloff Which logo? screenshot

**Comment by nikkiradloff** [comment]
Was referencing UI.X Pro
<img width="379" alt="screen shot 2018-01-16 at 12 32 52 pm" src="https://user-images.githubusercontent.com/15836402/35005568-716cd66c-fab9-11e7-8bc6-a24571f48189.png">

**Comment by Ian-Hitt** [comment]
logo is smart, defaults to the height of the bar minus the top and bottom padding. changing this would short-circuit the function.
