### ISSUE TITLE
Exception while trying to delete or move a thread

### ISSUE THREAD

**Issue by jOOc** [Audentio/xf2theme-issues#401]
`An exception occurred: [Error] Call to a member function canSendModeratorActionAlert() on null in src/XF/Entity/Thread.php on line 395
#0 [internal function]: XF\Entity\Thread->canSendModeratorActionAlert()
#1 src/XF/Template/Templater.php(920): call_user_func_array(Array, Array)
#2 internal_data/code_cache/templates/l10/s1/public/thread_move.php(32): XF\Template\Templater->method(Object(XF\Entity\Thread), 'canSendModerato...', Array)
#3 src/XF/Template/Templater.php(1230): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#4 src/XF/Template/Template.php(24): XF\Template\Templater->renderTemplate('thread_move', Array)
#5 src/XF/Mvc/Renderer/Json.php(81): XF\Template\Template->render()
#6 src/XF/Mvc/Renderer/Json.php(65): XF\Mvc\Renderer\Json->renderHtmlFallback('XF:Thread\\Move', 'public:thread_m...', Array)
#7 src/XF/Mvc/Dispatcher.php(332): XF\Mvc\Renderer\Json->renderView('XF:Thread\\Move', 'public:thread_m...', Array)
#8 src/XF/Mvc/Dispatcher.php(303): XF\Mvc\Dispatcher->renderView(Object(XF\Mvc\Renderer\Json), Object(XF\Mvc\Reply\View))
#9 src/XF/Mvc/Dispatcher.php(44): XF\Mvc\Dispatcher->render(Object(XF\Mvc\Reply\View), 'json')
#10 src/XF/App.php(1880): XF\Mvc\Dispatcher->run()
#11 src/XF.php(328): XF\App->run()
#12 index.php(13): XF::runApp('XF\\Pub\\App')
#13 {main}`

Tested with default XenForo theme and got the same error (refering to ThemeHouse\UIX\XF\Template\Templater)

**Comment by Ian-Hitt** [comment]
This is unrelated to the UI.X theme/addon
