### ISSUE TITLE
Tactical > [TH] Nodes 2 icon change

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#403]
[TH] Nodes 2 icon change are not showing in Microsoft Edge Browser.

**Comment by Nirjonadda** [comment]
@Ian-Hitt font awesome icons

**Comment by Ian-Hitt** [comment]
Which font awesome icons

**Comment by Ian-Hitt** [comment]
@Nirjonadda Does this also occur in the default theme, or only in UI.X?

**Comment by Ian-Hitt** [comment]
@Nirjonadda are you adding the icons via Tactical style property, or the TH Nodes add-on?

**Comment by Nirjonadda** [comment]
Adding via TH Nodes add-on.
