### ISSUE TITLE
Tactical > Go with post no

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#405]
Post are not full visible when go with post ID url. reading post need to scroll down.

`/threads/199778/page-25#post-1723603`

https://image.prntscr.com/image/9YH1vl0STo2ANv3Kgbrr-g.png

**Comment by kylerc** [comment]
@Nirjonadda Thanks for the bug report.  I've created issue #540 to track the specific issue that's causing this.  I'll be closing this to consolidate issues, but hoping to have this resolved in our next release or the one after (You'll see updates on #540).
