### ISSUE TITLE
Connected Accounts

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#414]
Discord does not show like the rest as seen in screenshot.
![discord](https://user-images.githubusercontent.com/34584920/34964102-ce89ec52-fa43-11e7-85f7-3f4400999dd1.png)

**Comment by Ian-Hitt** [comment]
@legendofmir3 is this being added by an add-on? that would make sense if so

**Comment by legendofmir3** [comment]
By Jaxel’s discord add-on but isn’t it in the connected accounts section by default?

**Comment by legendofmir3** [comment]
Really could do with the discord icon added to icon list for mdi too as i wanted to add it to the navlink

**Comment by Ian-Hitt** [comment]
No it's not in connected accounts by default. He does not appear to be adding any styling, he is just using the ".button" class.

**Comment by legendofmir3** [comment]
Every time I mention something he gets all defensive and rude about it saying it’s a stylish issue and stop asking styling questions though it happens in the default theme too. Please can you tell him it hasn’t anything to do with your theme so his ignorance can pipe down.

**Comment by legendofmir3** [comment]
https://xenforo.com/community/threads/xf2-8wr-discord-integration-paid.140836/page-3#post-1213494

His reply saying it’s a style issue.
