### ISSUE TITLE
Categories Node

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#416]
In the categories nodes, you can seen in the screenshot its not aligned properly on the right side >>>> and looks like the middle bit between the two nodes looks cramped.
![categories](https://user-images.githubusercontent.com/34584920/34990141-e06d4558-fabc-11e7-867d-91407576b54f.png)

**Comment by Ian-Hitt** [comment]
Looks like Node Grid is adding the wrong class names here. moving to the addons issues repo
