### ISSUE TITLE
Suggestion - UI.X Canvas View (Mobile) - Add Social Icons

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#424]
Style Name: UI.X 2

In Canvas menu, I'd like to see the social icons at the bottom/footer of the whole menu (centered), similar to how vice.com does it in their canvas menu.

Screenshot attached.

Thank you.

![uix_2_canvas_menu_suggestion](https://user-images.githubusercontent.com/35111972/35021757-56dbabe2-fb00-11e7-9e18-e0bb3cc119ff.png)

**Comment by Ian-Hitt** [comment]
See https://github.com/Audentio/xf2theme-issues/issues/457
