### ISSUE TITLE
Tactical: Inline code text

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#425]
Style Name: Tactical

Style Version: 2.0.1.2.1

UI.X Add-on Version: 2.0.5

XenForo Version: 2.0.1

Inline code text very small and hard to reading.

Tactical: https://image.prntscr.com/image/ORgbckxNS4KYNON5yYXELw.png

Xenforo: https://image.prntscr.com/image/5Kogj9pxS6ydlxyenLH9dw.png

**Comment by Ian-Hitt** [comment]
What is this component, and how can I replicate? Not familiar.

**Comment by Nirjonadda** [comment]
Use Inline code: https://image.prntscr.com/image/fkcigqstRvGpXYsb4C5rpQ.png
