### ISSUE TITLE
Align Last post please

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#428]
As seen in screenshot.

![align](https://user-images.githubusercontent.com/34584920/35068367-c04e19ec-fbce-11e7-99be-db59e657fa0d.png)

**Comment by daltonp** [comment]
I am able to confirm this with the latest version of [TH] Last Post Avatar on UI.X 2 Dark. Thank you for your submission.

**Comment by Ian-Hitt** [comment]
sadly this is currently working as intended. the only fix causes a different bug.
