### ISSUE TITLE
UI.X Dark - Cannot view unhighlighted tab text in smiley chooser

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#432]
Style Name: UI.X Dark

Style Version: Latest Available

UI.X Add-on Version: Latest Available

XenForo Version: 2.0.1

Operating System (and Version): Win 10 Fall Creators Update, latest stable

Browser Name (and Version): Chrome (latest stable)

Does this issue happen in the default XenForo style? No.

Summary of issue: When creating a thread, or replying to a thread, when you have multiple categories of smiles the tabs that are NOT selected/highlighted are not visible. Screenshots show it all.

Upload any screenshots related to the issue below

![uix-smiley-chooser-selections-bug](https://user-images.githubusercontent.com/35111972/35163960-6e96c7a4-fd16-11e7-8ab3-4150b4b85b6f.png)

**Comment by daltonp** [comment]
I am able to confirm this on the latest version of UI.X 2 Dark. Thank you for your submission.

**Comment by lilalien** [comment]
Shouldn't this be a bug? ;)
