### ISSUE TITLE
MDI Icons

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#433]
Suggestions to add Xbox Live, Ps4, Gaming controller, Discord please.

**Comment by daltonp** [comment]
Such icons can be found here if you are wanting to use them on your nodes: https://materialdesignicons.com/cdn/2.0.46/

**Comment by legendofmir3** [comment]
It is not for nodes. I wanted to add it to the navigation bar for one of the add-ons I am using. I have this in my extra.less:
.p-navEl-link[data-nav-id="EWRdiscord"]:before {<xf:macro template="uix_icons.less" name="content" arg-icon="messages" />}

But I was looking for the mdi-discord icon instead of messages which I have temporarily put there until a solution.

**Comment by Ian-Hitt** [comment]
Hello,

The UI.X Icons style properties are for UI components specifically. I would suggest simply not using the macro to add the icon, and instead add it normally.
