### ISSUE TITLE
UI.X Dark - Cannot view media gallery photo descriptions - Invisible text!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#449]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Win 10  64bit (latest stable)

Browser Name (and Version): Chrome 64 (latest)

Can you replicate this issue on our demo for this theme? Yes.

Does this issue happen in the default XenForo style? No.

Summary of issue: When viewing a photo in the XF Media Gallery, the description has a white background and invisible text. See screenshot.

Detailed steps to reproduce the issue: See Screenshot

Upload any screenshots related to the issue below

![uix-bug-6](https://user-images.githubusercontent.com/35111972/35707921-b607cb66-0779-11e8-9b50-01711f4005c6.png)

**Comment by lilalien** [comment]
Apparently this is only because quotes is now broken in the latest version...

So its not media-specific.

![uix-bug-7](https://user-images.githubusercontent.com/35111972/35708272-44669d5a-077b-11e8-9e9e-1e364c80dedd.png)

**Comment by lilalien** [comment]
Hard coded value slipped in here somehow... When its removed, its fixed.

In bb_code.less:

.bbCodeBlock-content
{
	position: relative;
	padding: @_bbCodeBlock-paddingV @_bbCodeBlock-paddingH;
	background-color: #fff;
}

**Comment by daltonp** [comment]
This has been confirmed on our demo board as well, thank you for the report.

**Comment by Ian-Hitt** [comment]
Re-scoped to Code component only.
