### ISSUE TITLE
Suggestion - Add "ButtonGroup" to your Style Properties for UI.X

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#450]
Sort of related to here:
https://github.com/Audentio/xf2theme-issues/issues/447

You have standard buttons, primary buttons, and call-to-action buttons in the UI.X style properties selection for users to easily edit. Would be nice to add this additional type of button to easily edit from the front end instead of having to use extra.css overrides!

![uix-suggestion-1](https://user-images.githubusercontent.com/35111972/35708087-6ac1dfc4-077a-11e8-91a8-ef69311d1921.png)

Thanks!
-Jason

**Comment by Ian-Hitt** [comment]
@lilalien The button groups actually use the Button (Small) SP so you can use that :)

**Comment by lilalien** [comment]
@Ian-Hitt What if you want to have a different look for regular buttons, call-to-action buttons, and grouped buttons?
