### ISSUE TITLE
UI.X Dark - Left side header/nav area shifts rightward when popup menus occur

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#452]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Win 10 / 64-Bit (Latest stable)

Browser Name (and Version): Chrome 64 (Latest Stable)

Can you replicate this issue on our demo for this theme? Yes.

Does this issue happen in the default XenForo style? No.

Summary of issue: When clicking on anything that brings up a pop-up menu (Post Preview, other functions like the "Show All" link with Reactions" it shifts the upper left hand corner of the header and nav bar over when it should not do that.

Detailed steps to reproduce the issue: Watch attached video.

Upload any screenshots related to the issue below

![upper-left-corner-oddness-when-popup_displays](https://user-images.githubusercontent.com/35111972/35751256-d20f7122-0825-11e8-8446-08c1f9fd54bf.gif)

**Comment by nsaneman** [comment]
This also occurs with the normal version of UI.X. I've noticed it happen with the theme chooser.

**Comment by lilalien** [comment]
I can confirm that too.. Anything that uses that type of pop-up it seems.

**Comment by Ian-Hitt** [comment]
Unable to replicate on our current dev version. what browser are you using?

**Comment by lilalien** [comment]
I always include that info in the reports, as requested. ;)

Chrome 64, 64-bit (latest stable version - no blockers)..

9/10 I can also reproduce these issues on both Firefox and Edge as well.

**Comment by lilalien** [comment]
Happens in UI.X dark official demo here as well:
https://demo.themehouse.com/xf2/themes/index.php

Just click to change a style in the footer of the page. The whole header/nav shifts over.

**Comment by nsaneman** [comment]
This issue occurs on Windows, Mac and Linux as long as you're using a WebKit based browser e.g. Chrome, Edge or Safari.

If I use Firefox then the header is hidden when an overlay is displayed.

**Comment by nsaneman** [comment]
This issue occurs on Windows, Mac and Linux as long as you're using a WebKit based browser e.g. Chrome, Edge or Safari.

If I use Firefox then the header is hidden when I open the theme chooser.

**Comment by daltonp** [comment]
I'm able to confirm this as well @lilalien @nsaneman

**Comment by lilalien** [comment]
Just wanted to note that this only occurs when sticky nav is activated and you've scrolled a little.. If you bring up a overlay/pop-up and the screen is on its top-most position the shifting does not occur.

**Comment by lilalien** [comment]
Anything near this code? The only way I could toy around using Chrome devtools was deleting the overlay code, which left me with adjusting this:

<div class="p-navSticky p-navSticky--primary uix_stickyBar is-sticky" data-top-offset-min="0" data-top-offset-max="0" data-top-offset-breakpoint="100%" style="position: absolute;top: auto;width: 1338px;bottom: 0px;">

Not sure if that code is relevant as I'm still somewhat of an amateur, but I've gotten lucky from time to time. ;)

**Comment by lilalien** [comment]
This one drives me crazy! lol
