### ISSUE TITLE
UI.X - Canvas Menu Improvements

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#457]
I'd like to see some simple enhancements to the canvas menu...

1) I'd like to see the horizontal separators/borders returned between the area selections (as default) (seen in screenshot).
2) I'd like to see the vertical line return next to selections with a down arrow (as default) (seen in screenshot)
3) Add Material Icons next to node selections (not sub-nodes), as seen in non-canvas menu. (seen in screenshot)
4) I'd like to see a separation of background color between an OPEN menu, and the closed menu (seen in screenshot)
5) (Already a suggestion, but listed here for convenience): Social Network Icons centered at bottom of canvas menu. (screenshot 2)

I think this would make a nice tweak to it!

Thank you.

![uix-canvas_menu_suggestions](https://user-images.githubusercontent.com/35111972/35783087-fe6f3774-09cf-11e8-9647-8d34e2933e80.png)

![uix-canvas_menu_suggestions-social](https://user-images.githubusercontent.com/35111972/35783891-89a87cf8-09dd-11e8-9df7-7ea6e1e57a26.png)

**Comment by Ian-Hitt** [comment]
1-4 are duplicates of another issue. We plan to add quite a few style properties in regards to canvas styling :)

5. I would suggest doing as a customization, but it's possible we may consider in the future. For now, It is not something we would plan on.
