### ISSUE TITLE
UI.X Dark - Deleted Profile Messages CSS Issue

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#458]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: 2.0.2

Operating System (and Version): Win 10/64 Bit (Latest)

Browser Name (and Version): Chrome 64 (latest)

Can you replicate this issue on our demo for this theme? Yes.

Does this issue happen in the default XenForo style? No.

Screenshot 1 - Default looks good...

![uix-bug-deleted_profile_messages_default](https://user-images.githubusercontent.com/35111972/35784703-82f5c31a-09e8-11e8-9c7e-cc6017abbf66.png)

Screenshot 2 - Not so good... When collapsed it needs improvement.

![uix-bug-deleted_profile_messages_broken](https://user-images.githubusercontent.com/35111972/35784709-88413e30-09e8-11e8-8cd6-fa3bbcb9a85d.png)

**Comment by Ian-Hitt** [comment]
Must already be fixed, as I am unable to replicate. Check to make sure you are on the latest version.

**Comment by lilalien** [comment]
I'm always on the latest version. :)

Its happening on my unmodified UI.X Dark, on Chrome 64 (latest stable).

![uix_deleted_profile_messages_bug](https://user-images.githubusercontent.com/35111972/36157387-a8f9601a-10a7-11e8-9d76-b3008aa481bc.png)

**Comment by lilalien** [comment]
Happening on latest Firefox as well.

**Comment by lilalien** [comment]
...and Microsoft Edge.

I'm on latest UI.X dark.

**Comment by lilalien** [comment]
Happens in UI.X dark here as well:
https://demo.themehouse.com/xf2/themes/index.php

Just click to change a style in the footer of the page. The whole header/nav shifts over.

**Comment by lilalien** [comment]
@daltonp Are you able to reproduce this on the demo site (as I do not have access to delete and view profile comments)! You were able to reproduce another report that I was experiencing, so I figured I would ask. :)

**Comment by lilalien** [comment]
@mikecreuzer Are you able to reproduce this?

**Comment by mikecreuzer** [comment]
Sorry, will get to this one asap @lilalien
