### ISSUE TITLE
Notice custom icon support

### ISSUE THREAD

**Issue by gnonline** [Audentio/xf2theme-issues#463]
As seen in screenshot.
![floating](https://user-images.githubusercontent.com/34584920/35997284-e8c3e2a0-0d10-11e8-8c35-39bc438186e4.png)

**Comment by mikecreuzer** [comment]
@Ian-Hitt can we make it a setting that floating notices may or may not get the icon? Also did we ever add custom icon support for notices in UIX add-on?

**Comment by Ian-Hitt** [comment]
Not able to replicate this issue. @legendofmir3 check to see if its happpening in uncustomized UI.X

<img width="535" alt="screen shot 2018-02-13 at 8 51 52 am" src="https://user-images.githubusercontent.com/15836384/36155890-30d0f686-109b-11e8-8f82-994f999f7bcc.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer no, but i can add an issue for jake

**Comment by Ian-Hitt** [comment]
Moving to add-on repo: https://github.com/Audentio/xf2addon-issues/issues/1445
