### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#468]
As seen on the screenshot, no ':' after the Joined, Posts etc.

![profile](https://user-images.githubusercontent.com/34584920/36118738-fcd25e5c-1035-11e8-9c42-e788449c1bda.png)

**Comment by lilalien** [comment]
I can confirm this as well.

**Comment by Ian-Hitt** [comment]
XF doesn't add them in because they are stacked in the default theme.This means that add-on developers won't add them either, causing inconsistencies. Unfortunately, cannot use pseudo elements on dl, dt, dd tags, so cannot add it in that way either. Likely just needs to stay this way unfortunately.
