### ISSUE TITLE
Mobile Home xenporta 2 for XF2 bad View

### ISSUE THREAD

**Issue by CoZmicShReddeR** [Audentio/xf2theme-issues#472]
Style Name: Tactical 

Style Version: Tactical 2.0.2.1.0

UI.X Add-on Version: [TH] UI.X 2.0.5 Patch Level 1

XenForo Version: out v2.0.2

Operating System (and Version): iOS 11.2.5 

Browser Name (and Version): Mobile Chrome 64.0.3282.112, Safari Mobile 

Can you replicate this issue on our demo for this theme? No, because you do not have xenporta 2 installed

Does this issue happen in the default XenForo style? No

Summary of issue: Mobile using xenporta 2 Home page

Detailed steps to reproduce the issue: visit my website

Upload any screenshots related to the issue below

**Comment by CoZmicShReddeR** [comment]
![Image](https://i.imgur.com/i1IeN88.jpg)

**Comment by CoZmicShReddeR** [comment]
Visit with your mobile device https://www.cozworld.com

Everything is squeezing together. With default XF2 theme it scrolls normally

**Comment by CoZmicShReddeR** [comment]
I made a ticket on main site

**Comment by mikecreuzer** [comment]
I think its perfectly reasonably to keep this open, for sure! Thanks for posting! Ill reopen until we have some fix. It may be best the developer do a fix, since I assume the reason it isn't working is due to some incorrect use of default XenForo components.

**Comment by Ian-Hitt** [comment]
This issue is a duplicate, and has already been fixed for our upcoming release :) See: https://github.com/Audentio/xf2theme-issues/issues/453
