### ISSUE TITLE
Hover on node/thread when entire thing is a link, background kinda breaks radius

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#488]
Not a great way to do this, but easiest way (do not do overflow hidden ofc) is just last-child in the block we round to get that bottom left/right border-radius as well. a bit janky and could be quite a bit of code, but a good improvement.

![image](https://user-images.githubusercontent.com/1217271/36508986-d01c4f0e-1723-11e8-86f8-3ea889cffbc3.png)

**Comment by Ian-Hitt** [comment]
not 100% sure if there is a smart way for this to be done. anything we do to try and calculate will still have an issue when block-container has a padding
<img width="1087" alt="screen shot 2018-02-23 at 4 50 56 pm" src="https://user-images.githubusercontent.com/15836384/36620681-da077a7e-18b9-11e8-8224-66b959557996.png">

**Comment by Ian-Hitt** [comment]
could just use the block border SP's, and thats a little bit better, but still not perfect. can check if block-container SP has a padding value, but padding could be added in a less file, or on the uix_discussionList SP as well. no real safe way to know when block container does/does not have that padding.

**Comment by Ian-Hitt** [comment]
This also isnlt a node hover issue. Occurs any time there is a bg color on the last node, whether it is an even child and even children have a bg color, or just if it has a bg color set for any other reason.
