### ISSUE TITLE
Mobile navigation bug with "sidebar navigation" enabled

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2theme-issues#49]
So if you have "sidebar navigation" enabled, and view the theme on mobile, this happens.

https://files.slack.com/files-tmb/T6E6NNDE0-F6NAH1DPY-ce7029ba77/screenshot__2__720.png

**Comment by Ian-Hitt** [comment]
Off canvas is using js to target nav items. When nav items are not in their natural location, i presume the js can't find them
