### ISSUE TITLE
Metadata Logo URL - Must include FULL url, does not pass @xf-uix_imagePath to Facebook / OpenGraph

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#490]
Style Name: UI.X Dark

Style Version: Latest Stable

UI.X Add-on Version: Latest

XenForo Version: 2.0.2

Operating System (and Version): Win 10 / 64bit (Latest)

Browser Name (and Version): Chrome 64 / 64bit (Latest)

Summary of issue: When testing at the below URL:

https://developers.facebook.com/tools/debug/sharing/

... and you attempt to use a url in Style Properties > Settings > Basic Options > Metadata Logo URL that looks like:

@xf-uix_imagePath/path/to/metadatalogo.png

It will NOT work using the tester above. It will only work if you put the entire URL, such as 

http://www.sitename.com/styles/path/to/metadatalogo.png

Anything that can be done here to fix it in this case?

Thanks!
-Jason

**Comment by Ian-Hitt** [comment]
@lilalien This would be a question to raise with XenForo, as it is not relevant to UI.X
