### ISSUE TITLE
UI.X Dark - Missing horizontal separator in side-boxes on Conversations page

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#501]
Style Name: UI.X Dark

Style Version: (Latest)

UI.X Add-on Version: (Latest)

XenForo Version: 2.0.2

Operating System (and Version): Win 10 / 64-bit (Latest stable)

Browser Name (and Version): Chrome 64 / Latest

Can you replicate this issue on our demo for this theme? Haven't tried.

Does this issue happen in the default XenForo style? No.

Summary of Issue: This was an older problem that got fixed in a couple of areas, but I caught an area the horizontal line/separator is still not showing for me.

You can see it in conversations too. Check screenshot!

![uix-bug-missing-horizontal-separator-line-convos](https://user-images.githubusercontent.com/35111972/36794882-8ece8070-1c6f-11e8-8b49-971f9a48bcdf.png)

**Comment by mikecreuzer** [comment]
@Ian-Hitt I assume these sidebar components are subtly different in markup? So maybe XF bug?
