### ISSUE TITLE
UI.X - Large Avatars styling is horrid on postbit

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#503]
Style Name:

Style Version:

UI.X Add-on Version:

XenForo Version:

Operating System (and Version):

Browser Name (and Version):

Can you replicate this issue on our demo for this theme?

Does this issue happen in the default XenForo style?

Summary of issue:

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
![screen shot 2018-03-01 at 3 36 02 pm](https://user-images.githubusercontent.com/32306910/36871423-d8c37bd8-1d67-11e8-9f8a-a1ea1906358a.png)

**Comment by mikecreuzer** [comment]
@Ian-Hitt were you able to confirm this? 

@daltonp I wasnt able to, can you provide more information/browser etc? I think I saw this at one point but long ago so may be fixed now

**Comment by daltonp** [comment]
I've been able to confirm this issue on the public demo when navigating to Appearance > Style Properties > Messages > Postbit Avatar Size > Set it to Large. This was tested on UI.X 2 and UI.X 2 Dark

Browser Information: Version 65.0.3325.162 (Official Build) (64-bit)

**Comment by Ian-Hitt** [comment]
@daltonp @mikecreuzer that's because there is a default XF style property to set the post bit width. If your avatar is larger than the postbit, then obviously you're going to have some problems. I've tried finding smart ways to limit this issue, but with no success. It is simply user error.

**Comment by Ian-Hitt** [comment]
I struggle to see why you would ever want a 192px avatar in the first place (which is why I never added it until more recently), but I got enough complaints from people that wanted the option.
