### ISSUE TITLE
Add to documentation information about our new organizational layout naming/concept

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#506]
![layout](https://user-images.githubusercontent.com/1217271/36939076-e46fb7d2-1ef0-11e8-840e-6113c3fc8e22.png)

[layout.psd.zip](https://github.com/Audentio/xf2theme-issues/files/1777870/layout.psd.zip)

**Comment by mikecreuzer** [comment]
@Ian-Hitt names may be wrong so attached psd to initial post

**Comment by mikecreuzer** [comment]
Removing suggestion since, well, I really want this added to documentation for language reasons. I want to make sure we're all using the same terms.

**Comment by mikecreuzer** [comment]
Can you add the graphic.

**Comment by Ian-Hitt** [comment]
Sure thing

**Comment by mikecreuzer** [comment]
Meh. I cannot follow the names, Ill need confirmation.
