### ISSUE TITLE
Wrong phase 'like' in account_visitor_menu

### ISSUE THREAD

**Issue by jOOc** [Audentio/xf2theme-issues#510]
Style Name: [TH] UI.X

Style Version: 2.0.5 Patch Level 1

XenForo Version: v2.0.2

Summary of issue:
Wrong phrase "like" in template: account_visitor_menu, should be "likes" as in Xenforo original template

UI.X 2
![image](https://user-images.githubusercontent.com/9382342/37243106-a28a519a-2474-11e8-9751-af66f07754df.png)

Xenforo
![image](https://user-images.githubusercontent.com/9382342/37243107-a8c7d8fc-2474-11e8-84eb-79c1e5364a21.png)

**Comment by lilalien** [comment]
I can confirm this, and it works once set to "likes".
