### ISSUE TITLE
backstretch images need base_url. will need to explode string, add, and concatenate new string

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#511]
Style Name:

Style Version:

UI.X Add-on Version:

XenForo Version:

Operating System (and Version):

Browser Name (and Version):

Can you replicate this issue on our demo for this theme?

Does this issue happen in the default XenForo style?

Summary of issue:

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by mikecreuzer** [comment]
You can do this in JS @Ian-Hitt . The style property is intended to just be a JS object anyway, so you can just do a loop through that JS object.

**Comment by Ian-Hitt** [comment]
@mikecreuzer no we cannot, base_url() needs to be parsed before run-time

**Comment by kylerc** [comment]
To expand on Ian's comment, it needs to be run through XenForo's template system with a single url.  Issue is that it doesn't know what to do with a comma separated list of urls.  JS, however, can't run the template function.  It's possible that XF provides a javascript implementation of base_url(), but I haven't found it yet.
