### ISSUE TITLE
UI.X (Dark) - Missing Chart Bar Poll Image!

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#515]
Style Name: UI.X (Dark)

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: 2.0.4

Operating System (and Version): Windows 10 / 64-bit (Latest Stable)

Browser Name (and Version): Chrome 65 / 64-bit (Latest Stable)

Can you replicate this issue on our demo for this theme? Yes.

Does this issue happen in the default XenForo style? No.

Summary of issue: Viewing a thread with a poll in it, you will see the missing poll image problem in the screenshot.

Detailed steps to reproduce the issue: View a thread with a poll, notice the missing image next to the poll title as seen in the screenshot.

Upload any screenshots related to the issue below

I've included an image of it working in default style, and not-working in UI.X (Dark) style.

Correct:
![poll_icon_working](https://user-images.githubusercontent.com/35111972/37744378-246973e8-2d45-11e8-867f-f8c1007ebfd5.png)

Not correct:
![poll_icon_not_working](https://user-images.githubusercontent.com/35111972/37744394-40f69388-2d45-11e8-80f5-28c708c7f56b.png)

**Comment by daltonp** [comment]
This has been confirmed on the public demo, thanks for reporting this.
