### ISSUE TITLE
Online indicator

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#517]
So, apparently XF2 doesn't have a good online indicator? We should add one in. 

Do not copy this we need to write our own: https://xenforo.com/community/resources/status-indicator-online-or-offline.5901/

**Comment by Ian-Hitt** [comment]
@mikecreuzer we already have one
<img width="292" alt="screen shot 2018-03-29 at 12 40 13 pm" src="https://user-images.githubusercontent.com/15836384/38104291-59f0fb4e-334e-11e8-9749-d677f3e0a367.png">
