### ISSUE TITLE
UI.X2 navbar out of place when opening popups

### ISSUE THREAD

**Issue by IgnitedKitsune** [Audentio/xf2theme-issues#518]
**Style Name:** UI.X 2
**Style Version:** 2.0.4.0.0
**UI.X Add-on Version:** 2.0.5 Patch Level 2
**XenForo Version:** 2.0.4
**Operating System (and Version):** Windows 10 Pro
**Browser Name (and Version):** Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

> Can you replicate this issue on our demo for this theme?

Yes

> Does this issue happen in the default XenForo style?

No

> Summary of issue:

Opening an overlay causes the navigation to slip a bit to the right when it is attached to the top.

> Detailed steps to reproduce the issue:

1. Pick a page long enough to scroll down and attach the page to the top of the window.
2. Open an overlay (e.g. the style picker).

> Upload any screenshots related to the issue below

https://i.imgur.com/PKWiorx.png

**Comment by lilalien** [comment]
Yeah, this looks like the issue I've reported a couple of months ago...

https://github.com/Audentio/xf2theme-issues/issues/452

**Comment by Ian-Hitt** [comment]
This is a duplicate, closing.
