### ISSUE TITLE
Error Message Box Styling...

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#524]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Bug: This box isn't very attractive... I'm sure this can be fixed up to match the theme.

![uix_bug_error_message_style](https://user-images.githubusercontent.com/35111972/38108253-373fa42e-3362-11e8-91d7-6534af9b5cfa.png)

Thanks guys!

**Comment by Ian-Hitt** [comment]
This looks like it is a product of your customized theme. The following is what it looks like in UI.X out of the box:
<img width="1276" alt="screen shot 2018-05-10 at 3 03 44 pm" src="https://user-images.githubusercontent.com/15836384/39891483-596b36f4-5463-11e8-8fec-aa45a75cbeed.png">

**Comment by lilalien** [comment]
@Ian-Hitt At some point along the way, this must have been improved.. I can no longer reproduce this on our uix dark theme as we were originally able to in our first report. If I see any other error message issues I'll post them.

**Comment by lilalien** [comment]
Actually I can still reproduce this on the default ui.x dark style.

On WTF.com, if I type "bun" in the search field up at the top of the page, I get a correct result as you posted in YOUR screenshot.

HOWEVER:

When you type "friday the 13th" into my search field, you get the odd colored background box!

Gremlins?

**Comment by lilalien** [comment]
@Ian-Hitt Hope you get these follow-up messages after a bug is closed. ;)
