### ISSUE TITLE
Text ellipsis overflow needed on meta content-row

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#535]
<img width="385" alt="screen shot 2018-04-05 at 12 30 26 pm" src="https://user-images.githubusercontent.com/1217271/38381686-3024f534-38cd-11e8-986f-41ba77c74ffc.png">

**Comment by Ian-Hitt** [comment]
<img width="375" alt="screen shot 2018-04-05 at 2 33 45 pm" src="https://user-images.githubusercontent.com/15836384/38387702-5a9e4c28-38de-11e8-95b9-72354b2c9f15.png">

**Comment by mikecreuzer** [comment]
Yeah idk why XF didnt add that in themselves, I think both lines should have it.
