### ISSUE TITLE
Flare node colors aren't passed to titlebar

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#547]
<img width="1042" alt="screen shot 2018-04-23 at 4 09 48 pm" src="https://user-images.githubusercontent.com/1217271/39153454-cabd700c-4710-11e8-846a-699cf9240e8b.png">
<img width="428" alt="screen shot 2018-04-23 at 4 09 54 pm" src="https://user-images.githubusercontent.com/1217271/39153458-cddde334-4710-11e8-8b49-10e3d5890521.png">

**Comment by mikecreuzer** [comment]
This needs to be handled/supported by Nodes

**Comment by Ian-Hitt** [comment]
moving to add-ons repo
