### ISSUE TITLE
Sidebar navigation with sticky primary navigation bug

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2theme-issues#56]
When you have sidebar navigation enabled and "primary navigation row only" for sticky navigation enabled, the sticky elements don't quote work right. As you scroll down, it'll the primary navigation will start to come down but as you scroll a little further it'll stop coming down with you.

http://imgur.com/GRxbja3 (GIF will take a while to load)

**Comment by Ian-Hitt** [comment]
@Matthew2D There is actually an issue with all of the sticky header components right now, and it is not related to the sidebar navigation. We are (I believe) planning on doing a serious re-write of the sticky header functionality, which there is already an issue for.

**Comment by Matthew2D** [comment]
Oh okay! Sorry. :)
