### ISSUE TITLE
Intrepid header alignment is poor

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#560]
Every component is out of alignment.

<img width="127" alt="screen shot 2018-04-24 at 10 00 47 am" src="https://user-images.githubusercontent.com/1217271/39195896-6ff83e40-47a6-11e8-8e40-be27ee31189f.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer any suggestions for this one? its due to the chromeless issue. check screenshot for actual alignments.

<img width="438" alt="screen shot 2018-04-24 at 11 11 50 am" src="https://user-images.githubusercontent.com/15836384/39199924-4c60dc8a-47b0-11e8-9df5-5edb938aa379.png">

**Comment by Ian-Hitt** [comment]
just depends on what may or may not have chrome

**Comment by Ian-Hitt** [comment]
could remove paddings, but then hover states but they would have to be added back in on customizations. and also the hover states and ripples would be broken.)

**Comment by mikecreuzer** [comment]
Well as this is a theme, perfection with style property values is less important. I mean do it if we can, but Id rather it look good than have perfect code. As at the end of the day, clean code does no one any good but us. The client needs quality design that doesn't look ugly.

I recommend you compare with our XF1 products more often, as even though those started to lose some of their perfections they are still far cleaner than some of our 2 themes. Xenith/Intrepid/Drift for sure

**Comment by mikecreuzer** [comment]
Better, but its off just a bit, what it looks like:
<img width="240" alt="screen shot 2018-04-24 at 1 02 32 pm" src="https://user-images.githubusercontent.com/1217271/39205392-1a14d910-47c0-11e8-89dc-2ab9f268fba1.png">

Changing that padding:
<img width="270" alt="screen shot 2018-04-24 at 1 04 20 pm" src="https://user-images.githubusercontent.com/1217271/39205401-1db6c876-47c0-11e8-9699-1598d094e7bf.png">
