### ISSUE TITLE
Xenith sizing consistency

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#566]
For example, look at a forum vs a thread list:

<img width="1328" alt="screen shot 2018-04-24 at 10 15 00 am" src="https://user-images.githubusercontent.com/1217271/39196707-6b14c0cc-47a8-11e8-89d1-a8850130458c.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer there is no size inconsistency, there is just less components in that example. add a dsecription or sub nodes or w/e else and it is the same size.

**Comment by mikecreuzer** [comment]
It looks awful. Period
