### ISSUE TITLE
Footers look poor

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#568]
Im aware that there are a lot of widgets that can be placed in the footer. But from a product standpoint, its just a requirement of the product if we're going to have widgets in this location. An argument is that we don't do this by default and do what we did for XF1. 

With XF1 we had widget locations, but this was documented, and instead there were static blocks for links/menus, subscribe inputs etc.

For comparison

Xenith 1:
<img width="1219" alt="screen shot 2018-04-24 at 10 20 15 am" src="https://user-images.githubusercontent.com/1217271/39197004-1bc6fee4-47a9-11e8-928d-b68870af87e1.png">

Xenith 2:
<img width="1255" alt="screen shot 2018-04-24 at 10 19 56 am" src="https://user-images.githubusercontent.com/1217271/39196984-11dddc4a-47a9-11e8-9356-30c4efc097ad.png">

Intrepid 1:
<img width="1224" alt="screen shot 2018-04-24 at 10 21 36 am" src="https://user-images.githubusercontent.com/1217271/39197093-4ca535d0-47a9-11e8-87ca-32ca88a8f8ac.png">

Intrepid 2:
<img width="1213" alt="screen shot 2018-04-24 at 10 21 03 am" src="https://user-images.githubusercontent.com/1217271/39197079-4303d036-47a9-11e8-8cc2-4e88fe743baa.png">

The same is true for all themes

**Comment by Ian-Hitt** [comment]
@jakcreate a couple new widgets, about us, quick links, logo, and then assign them to those locations by default in the add-on.

**Comment by Ian-Hitt** [comment]
@JakeBooher  about us, quick nav, facebook, forum statistics

```
<div class="block" data-widget-definition="th_aboutUs">
    <div class="block-container">
        <h3 class="block-minorHeader">Staff online</h3>
        <ul class="block-body">
            <li class="block-row">Our community has been around for many years and pride ourselves on offering unbiased, critical discussion among people of all different backgrounds. We are working every day to make sure our community is one of the best.</li>
        </ul>
    </div>
</div>
```

```
<div class="block" data-widget-definition="th_navigation">
    <div class="block-container">
        <h3 class="block-minorHeader">Quick Navigation</h3>
        <ul class="block-body">
            <li class="blockLink"><a href="#">Home</a></li>
            <li class="blockLink"><a href="#">About</a></li>
            <li class="blockLink"><a href="#">Forums</a></li>
            <li class="blockLink"><a href="#">Contact</a></li>
        </ul>
    </div>
</div>
```

```
<div class="block" data-widget-definition="th_facebook">
    <div class="block-container">
        <h3 class="block-minorHeader">Like us on Facebook</h3>
        <ul class="block-body">
            <li class="block-row">
                <div class="fb-page" data-href="https://www.facebook.com/ThemeHouse/" data-tabs="timeline" data-height="130px" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/ThemeHouse/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/ThemeHouse/">ThemeHouse</a></blockquote></div>
            </li>
        </ul>
    </div>
</div>
```
