### ISSUE TITLE
UIX Search dropdown styled wrong

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#570]
Default XenForo:
<img width="455" alt="screen shot 2018-04-24 at 10 30 38 am" src="https://user-images.githubusercontent.com/1217271/39197641-a2ad38e6-47aa-11e8-9eb9-04e420bca48c.png">

UIX:

<img width="375" alt="screen shot 2018-04-24 at 10 30 48 am" src="https://user-images.githubusercontent.com/1217271/39197637-9d0b7772-47aa-11e8-98a5-8a1c9fd46ce0.png">

Few obvious things to note:

- [x] 1. Sizes of inputs especially here is noticeable - Im OK taking inputs down a fix px again
- [x] 2. Search/select is wonky
- [x] 3. Height of footer bar is compounded with size of buttons
- [ ] 4. Note the margin around `search only titles` for example, ours has far too much

**Comment by Ian-Hitt** [comment]
this is part of a larger issue i think, which is poor form input styling in general, not just this specific dropdown
