### ISSUE TITLE
Reimplement sticky bars without sitickykit

### ISSUE THREAD

**Issue by kylerc** [Audentio/xf2theme-issues#571]
Sticky kit has quite a few issues it's causing.  Will (eventually) need to implement our own, but likely will need to have the same public api as stickykit for addon compatibility.

**Comment by mikecreuzer** [comment]
What about this? https://github.com/wilddeer/stickyfill

**Comment by mikecreuzer** [comment]
Or: https://github.com/dollarshaveclub/stickybits

**Comment by kylerc** [comment]
Whatever we do settle on will likely need to have the same public api as stickykit for addons, so will likely end up being at least partially custom.  For example, addons might fire a `stick_kit:recalc` event if they change the size of something and our sticky code will need to correctly respond to that (and the rest of stickykit's api) to not cause issues with the addon but will look into other options and see if we can borrow as much of their code as possible.

**Comment by mikecreuzer** [comment]
At this time, its super unlikely we'll ever do this. Buggy or not, I think we're stuck with it.
