### ISSUE TITLE
I think search dropdown is too rounded

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#581]
Perhaps wrong var was used? I havent seen this larger radius anywhere.

<img width="318" alt="screen shot 2018-04-27 at 1 37 19 pm" src="https://user-images.githubusercontent.com/1217271/39379204-32e73052-4a20-11e8-9aa0-e294fbb98826.png">

**Comment by Ian-Hitt** [comment]
It was 4px before and you made an issue saying it needed to be more round. Should I switch back to 4?
