### ISSUE TITLE
UI.X Dark - Threadlist Font Color Wierdness

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#586]
Style Name: UI.X Dark

Style Version: 2.0.5

UI.X Add-on Version: Latest Update

XenForo Version: 2.0.5

Does this issue happen in the default XenForo style? No.

Summary of issue: On thread list, instead of bold on threads that have new posts (as in XF default - like "Dead Thread", "Pew Research Center" as examples), it has a different font color entirely instead? This never happened before, including 2.0.4. Did the UI.X update change anything? It happens on dark unmodified for me, and obviously my custom style which is based on it.

Upload any screenshots related to the issue below

![different_colors_threadlist](https://user-images.githubusercontent.com/35111972/39541562-21e580cc-4e14-11e8-83e8-b27593a89178.png)

**Comment by daltonp** [comment]
I am not able to verify this on the public demo. The test itself should be showing as a blue color when a thread had new posts @lilalien

**Comment by lilalien** [comment]
Just wanted to include a pic of the default dark uix, didn't want to confuse with our custom child style...

![uix_color_bug](https://user-images.githubusercontent.com/35111972/39542005-52f46880-4e15-11e8-971f-5413a5ecb299.png)

**Comment by lilalien** [comment]
Something around here new at all?

.structItem-title a {
 color: inherit; 
}

When commenting out the color:inherit bit in Chrome devtools, the problem seems to vanish?

**Comment by lilalien** [comment]
The font weight seems liked it was changed too.. So all threads used to appear blue, and were bold when there was new posts.

Can't figure out what has happened...

**Comment by lilalien** [comment]
Here's a pic of the style properties of ui.x dark:

![uix_bug](https://user-images.githubusercontent.com/35111972/39640308-92fe0e0c-4f98-11e8-94e5-3c5be22c81bf.png)

**Comment by lilalien** [comment]
So:

Read threads show blue, and proper normal font weight.
Unread threads show white (FFFFFF) with normal font weight -- Should be blue with bold font weight?

**Comment by Ian-Hitt** [comment]
What is intended here is normal white text for read, and blue text for unread. The style properties should allow you to change that if you so choose. Are the style properties not allowing you to change this?

**Comment by lilalien** [comment]
This seems like a change for change sake?

It was working perfectly before the new update.

I can't imagine the default in a custom style would have such a mishmash of colors?

The node list now is devoid of color, as now the forum titles are just white.
The discussion list now is a mishmash of color, with white titles for read content and blue unbolded text for unread content, plus when you hover over a white title it shows a different blue, and when you hover over a date on the right-side column it shows blue and you hover over other links like username, or even "edit" and it keeps it grey. It's really a mishmash. I don't recall this every being an issue in 2.0.4 and earlier?

What XF has as a default works perfectly well, and that's what you had in the style up until this point.

With numerous bugs to fix, I find it odd that this was even toyed with?

**Comment by lilalien** [comment]
@Ian-Hitt What was the resolution on this? I mean the screenshots that help sell the style are not even accurate anymore, and will look much worse with this change.

My site looks terrible with this change, I would have expected a rush out with this fixed and can't believe I'm the only one who doesn't like it using the ui.x dark theme.
