### ISSUE TITLE
UI.X Dark - Nodelist lost font color on thread titles?

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#588]
Style Name: UI.X Dark

Style Version: 2.0.5

UI.X Add-on Version: Latest Update

XenForo Version: 2.0.5

Does this issue happen in the default XenForo style? No.

Summary of issue: In previous UI.X Dark, the thread titles were blue on the nodelist page. Now they only appear blue if you hover over them?

Was this changed to be by design, or a bug?

Upload any screenshots related to the issue below:

![uix_nodelist_font_color_question](https://user-images.githubusercontent.com/35111972/39544408-f49bd0aa-4e1b-11e8-8f90-b0bb5fdad9e7.png)

**Comment by Ian-Hitt** [comment]
@lilalien this is intentional. same change on node list as well
