### ISSUE TITLE
UI.X - Post Options missing on mobile view

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2theme-issues#589]
I'mma missing these tiny little dot fellas since the last update.
![timovxo](https://user-images.githubusercontent.com/38475165/39641653-524e5010-4fcf-11e8-959c-1c8b072f0cac.png)

**Comment by lilalien** [comment]
I can confirm this.

**Comment by Ian-Hitt** [comment]
Confirmed, thanks.
