### ISSUE TITLE
Overflow-y scroll on quick thread create on forum_view

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#603]
<img width="928" alt="screen shot 2018-05-14 at 10 19 42 am" src="https://user-images.githubusercontent.com/1217271/40006675-98b84234-5760-11e8-92cb-0b8e5d8f78a3.png">

Creates a scrollbar on the right of the input, probably just due to some incorrect padding/height calculation somewhere. Does not happen on default style

**Comment by Ian-Hitt** [comment]
@kylerc some JS adding CSS inline

**Comment by mikecreuzer** [comment]
The JS is probably doing this due to some styling.

**Comment by Ian-Hitt** [comment]
@mikecreuzer correct, but no way to know why without looking at the JS

**Comment by mikecreuzer** [comment]
Id assume int has something to do with the fixed height issue we're discussing in slack>?
