### ISSUE TITLE
Default nav icon (for those nav items that do not have an icon)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#605]
It is reasonable to assume all add-ons will not get an icon. I'd rather there be a default icon (folder, arrow, circle, etc.) than nothing at all.

<img width="262" alt="screen shot 2018-05-14 at 10 34 14 am" src="https://user-images.githubusercontent.com/1217271/40007448-6afa2f5e-5762-11e8-87f5-1205fa683925.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer sadly doing this removes the users ability to easily add an icon to nav items the way that XF intends. XF suggests you use the navigation manager to add the classes "mdi mdi-whatever." there is no css we can write thats going to be less specific than what that is.

**Comment by LukasWieditz** [comment]
Is that element insered via CSS or via an actual HTML element? Because if it's the latter, you could surely write a template mod or make template changes to achieve that behavior.

**Comment by mikecreuzer** [comment]
^^ Im thinking the same, theres a way to do this since they give us a variable system. Lets discuss, dont want to close just yet

**Comment by Ian-Hitt** [comment]
Its CSS not html

**Comment by Ian-Hitt** [comment]
The limitations would be:

1. users shouldnt need to write custom css to add an icon
2. needs to support our add-ons out of the box
3. our add-ons can't add an icon by default in themes outside of UI.X (because XF doesnt have icons by default)

**Comment by Ian-Hitt** [comment]
Fixed by https://github.com/Ian-Hitt/xf2/commit/2e55baf6b058cb0611e689f5ef914ab342a59ab6
