### ISSUE TITLE
Threadbit given much more emphasis and quality

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#612]
I think Flarum's is idealistic. At least as a style property.

<img width="876" alt="screen shot 2018-05-16 at 9 52 41 am" src="https://user-images.githubusercontent.com/1217271/40124778-e75908da-58ee-11e8-8d89-377be991ff8c.png">

**Comment by mikecreuzer** [comment]
<img width="1244" alt="screen shot 2018-05-16 at 9 53 13 am" src="https://user-images.githubusercontent.com/1217271/40124813-f87bb5a4-58ee-11e8-800f-e96171777ae3.png">

This is just not pretty

**Comment by Ian-Hitt** [comment]
@mikecreuzer check to see if my solution is sufficient. If so, close, if not, re-assign.

**Comment by mikecreuzer** [comment]
Close, but the number of replies is just a floating number. It needs a comment bubble and moved somewhere else (even if just to the right)
