### ISSUE TITLE
Template out of Date

### ISSUE THREAD

**Issue by Mondrethos** [Audentio/xf2theme-issues#62]
![chrome_2017-08-12_02-54-28](https://user-images.githubusercontent.com/9123069/29238779-9dd0c186-7f09-11e7-8538-4b3014441f17.png)
![chrome_2017-08-12_02-55-06](https://user-images.githubusercontent.com/9123069/29238782-b50038aa-7f09-11e7-9c71-8fbd43f5b560.png)

It won't dismiss it self even after I save it.

**Comment by Ian-Hitt** [comment]
@Mondrethos This can be ignored for now. It is simply an issue with there not being versioning yet in XF, which will be done for XF beta release.
