### ISSUE TITLE
Footer links only clickable on text

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#623]
Yet the entire area has a ripple effect. Padding is off as well.
<img width="584" alt="screen shot 2018-05-17 at 10 27 07 am" src="https://user-images.githubusercontent.com/1217271/40187333-e925ca26-59bc-11e8-8d5a-ba26ccfdfbe6.png">

**Comment by Ian-Hitt** [comment]
Can you plz update the markup for me. Should resemble this:
```
<div class="block-body">
<a class="blockLink rippleButton" href="/xf2/members/audentio.1/">profile</a></li>
</div>
```

remove the change <ul> to <div>, remove <li> and add `blockLink rippleButton` classes to anchor

**Comment by LukasWieditz** [comment]
Please do keep in mind that this is not being pushed to existing customers.

**Comment by mikecreuzer** [comment]
Thats fine, thanks @LukasWieditz 

THat markup looks goofy @Ian-Hitt but if thats right then OK I can close then
