### ISSUE TITLE
UI.X - Sticky navigation shadow flashing on overlay open/close

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2theme-issues#628]
https://gfycat.com/PointedRaggedIcelandicsheepdog

**Comment by Ian-Hitt** [comment]
@LukasWieditz we're aware of this, and it can only be fixed by replacing the sticky functionality (which is already an issue)

**Comment by Ian-Hitt** [comment]
@mikecreuzer Shadow is only when sticky. But sticky kit "forgets" that it is sticky, and re-renders.

**Comment by Ian-Hitt** [comment]
So we don't get the sticky class util after it is added back.

**Comment by mikecreuzer** [comment]
It's unlikely we will be replacing sticky kit.

**Comment by LukasWieditz** [comment]
Does adding an animation delay may stop this from happening?

**Comment by mikecreuzer** [comment]
I don't think so as it would still flash, after the delay.

**Comment by LukasWieditz** [comment]
But then the class would be already back? Dunno about the css specifics, was just a thought that we might be able to bridge the time it takes for stickykit to remember it's sticky.

**Comment by Ian-Hitt** [comment]
@LukasWieditz it would also delay the shadow from appearing after sticky, so that would be a no go.

**Comment by Ian-Hitt** [comment]
@LukasWieditz it would finish the animation before going to its new state. so doesn't matter that the class is back, it doesn't stop the animation form happening.

**Comment by LukasWieditz** [comment]
Well, css is annoying I guess.
