### ISSUE TITLE
"Remove selected tab sublinks" doesn't remove the tab sublink bar

### ISSUE THREAD

**Issue by Matthew2D** [Audentio/xf2theme-issues#63]
The option removes the links, but it doesn't remove the tab sublink bar.

![screenshot 4](https://user-images.githubusercontent.com/1912461/29239415-e4b67a3c-7f13-11e7-980a-c841c596fa18.png)

**Comment by Ian-Hitt** [comment]
@Matthew2D It will only remove the bar if there is nothing else in the tablinks. This is likely related to your other issue https://github.com/Audentio/xf2theme-issues/issues/57 in that the search bar is there.
