### ISSUE TITLE
UI.X 2 - Emojis not properly showing

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#630]
As per title:
![image](https://user-images.githubusercontent.com/34864926/40270259-8476fd5e-5b81-11e8-9096-875986d1a444.png)

**Comment by JakeBooher** [comment]
This is something that happens in the default style as well, and XenForo has labelled it as a browser issue:

https://xenforo.com/community/threads/chrome-66-smilies-broken-when-using-browser-zoom.144739/
