### ISSUE TITLE
UI.X 2 - Editor z-index issue

### ISSUE THREAD

**Issue by nsaneman** [Audentio/xf2theme-issues#631]
Style Name: UI.X 2

Style Version: 2.0.6.0

UI.X Add-on Version: 2.0.7

XenForo Version: 2.0.6a

Operating System (and Version): Windows 10

Browser Name (and Version): Firefox 60.0.1 and Chrome 66.0.3359.181

Can you replicate this issue on our demo for this theme? Yes

Does this issue happen in the default XenForo style? No

Summary of issue: Floating buttons are hidden behind the editor

Detailed steps to reproduce the issue: Switch to a mobile device and scroll down to the editor

Upload any screenshots related to the issue below
![zindex](https://user-images.githubusercontent.com/26636634/40319317-a6a72dd2-5d1f-11e8-8ac4-f155181c9b01.png)

**Comment by nsaneman** [comment]
@mikecreuzer That probably wouldn't work well because the floating buttons would remain hidden until you press on something else. The editor doesn't lose focus when you're scrolling either.

If you're wanting to be true to the Material design language then floating action buttons are always displayed above everything else.

**Comment by mikecreuzer** [comment]
@nsaneman perhaps, but if you are composing its unlikely you will want this floating button. On any Google platform, it takes you to a modal that does not have the FAB. So I still think hiding makes some sense.

**Comment by nsaneman** [comment]
@mikecreuzer I agree that people might not want the buttons displayed over the editor, but if they were hidden then second I start to scroll away from the editor I'd expect to see the buttons again. Maybe with a quick but smooth fade in/out animation.

It just seems like a lot of extra work when `.fr-box {z-index: 0;}` would fix the issue. I've also never received a single complaint while using your XF1 Material theme.

**Comment by Ian-Hitt** [comment]
Chose to hide floating actions when input is focused
