### ISSUE TITLE
UI.X Dark - Navbar Search Popup Button Alignment Issue (Still Exists)

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#634]
Style Name: Latest

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

This bug still exists (and the alignment bug that occurred 2 versions back may also affect other areas as well):
https://github.com/Audentio/xf2theme-issues/issues/587

**Comment by Ian-Hitt** [comment]
@lilalien This is because one button has a border and one does not. I've just added a fix in UI.X, but you may need to adjust yours as well if you have customized buttons.

**Comment by lilalien** [comment]
OK Thanks!
