### ISSUE TITLE
Is .p-nav .uix_activeNavTitle hidden intentionally for desktop?

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#636]
It like shows up for ipad or something then hides for mobile again? Id love to see it stick around for the active main nav tab. 
<img width="182" alt="screen shot 2018-05-21 at 2 41 27 pm" src="https://user-images.githubusercontent.com/1217271/40326493-0dc5674c-5d05-11e8-8f13-6de0afd39277.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer yes there is a breakpoint. It appears intentionally once the navigation is hidden in the canvas (because you can no longer see the active tab at that point.)

**Comment by mikecreuzer** [comment]
Is there a way we can show it even with sidensv visible
