### ISSUE TITLE
Postbit button icons

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#639]
Personally I dont care much for them, to me the icon here should either replace the text or just not exist. Im OK with a setting to allow both at the same time. But meh, your call @Ian-Hitt just my 2 cents.

This issue however is to point out though that reply/like do not have icons but the left side does.
<img width="1092" alt="screen shot 2018-05-21 at 2 51 20 pm" src="https://user-images.githubusercontent.com/1217271/40326914-965b6d44-5d06-11e8-88b8-8783d351c57b.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer @LukasWieditz That's because TH Post Comments replaces the default Reply button with a Comment button apparently :) Probably want to keep the class the same, unless there is js relying on it @LukasWieditz ?

**Comment by mikecreuzer** [comment]
We as this solved?
