### ISSUE TITLE
Navigation is flashing when clicking the 'Spoilers' action button

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#640]
![spoilernavigationbug](https://user-images.githubusercontent.com/32306910/40368394-50c6d19c-5da1-11e8-86a7-a263a37d0023.gif)

**Comment by daltonp** [comment]
It doesn't happen on the default style, no.

**Comment by nsaneman** [comment]
This looks very similar to #558 and #628. Kyler said it was due to the implementation details of Sticky-Kit.

**Comment by Ian-Hitt** [comment]
We keep adding these issues about sticky kit. This is a repeat like @nsaneman said.
