### ISSUE TITLE
UI.X Dark - Navbar link underline on hover issue...

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#641]
Style Name: UI.X Dark

Style Version: Latest Stable

UI.X Add-on Version: Latest Stable

XenForo Version: Latest Stable

Operating System (and Version): Win 10 / 64-Bit (Latest Stable)

Browser Name (and Version): Chrome 66 (Latest Stable)

Upload any screenshots related to the issue below

![navbar_underline_bug](https://user-images.githubusercontent.com/35111972/40443535-a49664ce-5e94-11e8-9c5d-745a61aa641a.gif)

**Comment by lilalien** [comment]
No, not on UI.X Dark. I customize on my child style.

**Comment by mikecreuzer** [comment]
Ah! Can confirm now gotcha.

**Comment by mikecreuzer** [comment]
@Ian-Hitt with popup open, hover the trigger. Inheriting all the way from `a:hover` funny enough
