### ISSUE TITLE
Collapse sidebar improvements

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#645]
1. Simply logic on trigger to be IF sidebar, show sidebar trigger
2. Instead of moving sidebar to the bottom, convert it to a canvas (always, no option to put it below)
3. Consider icons/phrases

**Comment by mikecreuzer** [comment]
<img width="449" alt="screen shot 2018-05-29 at 12 34 18 pm" src="https://user-images.githubusercontent.com/1217271/40675182-9f2a370c-633c-11e8-9de6-9b6d59aa33b3.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer may be an issue with advertisements in the sidebar, since they wouldn't be visible for mobile (without opening canvas)

**Comment by mikecreuzer** [comment]
Lets chat about this before closing./

**Comment by mikecreuzer** [comment]
Im getting an added line on pro, reopening and calling sec
