### ISSUE TITLE
Social media icons missing

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#647]
Some social media icons aren't showing when links are added under the social media links menu. 
The following icons include:
- Google Plus
- Youtube

I am able to experience this on the beta/public theme demo.
![screen shot 2018-05-25 at 10 17 19 am](https://user-images.githubusercontent.com/32306910/40552375-1230715c-6005-11e8-9164-a35e8eff464d.png)
![screen shot 2018-05-25 at 10 19 27 am](https://user-images.githubusercontent.com/32306910/40552410-2e428bfa-6005-11e8-926a-7cc8527bd425.png)

**Comment by Ian-Hitt** [comment]
This is false lol :)
