### ISSUE TITLE
Page jump arrows not appearing

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#648]
Style Name: UI.X 2

Style Version: 2.0.6

UI.X Add-on Version: 2.0.7

XenForo Version: 2.0.6

Operating System (and Version): Windows 8.1

Browser Name (and Version): Version 66.0.3359.181 (Official Build) (64-bit)

Can you replicate this issue on our demo for this theme? Yes

Does this issue happen in the default XenForo style? No

Summary of issue: When attempting to display jump buttons up or up/down. They aren't able to be seen no matter the setting or the direction you scroll. This was replicated on the beta and demo forum.

Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below

**Comment by Ian-Hitt** [comment]
Duplicate of a closed issue

**Comment by LukasWieditz** [comment]
Buttons are only appearing on forum home page for me, on all other pages, they're still missing @Ian-Hitt .
