### ISSUE TITLE
Welcome block on forum list -> should be on homepage

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#653]
The issue is that with new posts/trending/etc as nav tabs, welcome block still only shows on forum list. Can we genericize this to home page route instead of forum list? Maybe by default (assuming you built something for this already)

**Comment by LukasWieditz** [comment]
We have a style property that shows the welcome section on forum list only @Ian-Hitt, might want to disable that for UI.X Pro?

**Comment by LukasWieditz** [comment]
Add forum overview wrapper to trending page and rename style property.
