### ISSUE TITLE
Width collapse overlap jump during animation

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#654]
<img width="313" alt="screen shot 2018-05-30 at 3 24 03 pm" src="https://user-images.githubusercontent.com/1217271/40745617-89aa1578-641d-11e8-9d1a-b8439d6cc684.png">

This is halfway through the animation. It jumps back.

**Comment by LukasWieditz** [comment]
Probably some clash between min-width and max-width again, @Ian-Hitt . Issue is permanent on 1661px width.
