### ISSUE TITLE
Category widget missing (default or custom) icon

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#658]
<img width="379" alt="screen shot 2018-05-31 at 3 03 08 pm" src="https://user-images.githubusercontent.com/1217271/40805400-c62ed4f4-64e3-11e8-916e-1c54af5885d8.png">

and

<img width="446" alt="screen shot 2018-05-31 at 3 04 19 pm" src="https://user-images.githubusercontent.com/1217271/40805446-ec8b3c8c-64e3-11e8-8d63-5ef795d16e79.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer category widget for some reason is not a widget? no
