### ISSUE TITLE
Add meta name="theme-color" meta tag/style property

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#664]

**Comment by Ian-Hitt** [comment]
@mikecreuzer this has always been a thing
<img width="1155" alt="screen shot 2018-06-04 at 10 34 16 am" src="https://user-images.githubusercontent.com/15836384/40926835-d732f224-67e2-11e8-98ee-3de96ce26ba4.png">

**Comment by Ian-Hitt** [comment]
Its a XenForo default thing.
