### ISSUE TITLE
Improve mobile navigation handling

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2theme-issues#665]
Closing the mobile navigation is currently only possible if you're on the navigation tab. If you're on the visitor, conversation or alert tab, you have to switch back to the navigation tab in order to close the navigation. This should be improved. Best thing would be to offer swipe closing, as with android native apps (swiping left will close the navigation).

**Comment by kylerc** [comment]
Good point about the `X` only being on the first menu.  Some of the other tabs don't have quite the same title area to have the X but think we should add it anyways @Ian-Hitt ? You are at least able to click anywhere outside the menu (the rgba overlay over the rest of the page) to close the modal from any tab on the canvas.  Swiping tends to be hard to capture on web pages, but would feel more native, I agree.  I haven't specifically looked into that in a little while, I'll see if it's simpler to support now than it used to be.

**Comment by LukasWieditz** [comment]
There used to be jQuery mobile back when I experimented with swipe support. Idk if that's still a thing and if it's viable, maybe there are more lightweight solutions.
