### ISSUE TITLE
Remove FB Pixel 

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#666]

**Comment by mikecreuzer** [comment]
Can you be more specific?

**Comment by JakeBooher** [comment]
Ian already knows about this, it's from the facebook feed widget, and I don't think there is a way to remove this without removing the widget

**Comment by mikecreuzer** [comment]
This seems to be a XF issue not a theme issue?

**Comment by JakeBooher** [comment]
It's the footer widget we add by default:

<img width="305" alt="screen shot 2018-06-04 at 4 42 01 pm" src="https://user-images.githubusercontent.com/179180/40943325-3d381c74-6816-11e8-976c-10934fd57651.png">

Nothing we can do AFAIK other than tell them to disable the widget if they don't want the facebook tracking pixel

**Comment by mikecreuzer** [comment]
Yeah, thats fine with me? So this issue we can close correct @JakeBooher ?

**Comment by daltonp** [comment]
I went ahead and added an FAQ on the UI.X 2 documentation which explains how to remove this widget and the others on the extended footer if they don't want them.
