### ISSUE TITLE
On create topic, random color is automatically selected from a set so people don't have to (chances are they wont care the color)

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#668]
Can be auto-done or some random button. That set will be material icon palette. I think this would be good on nodes as well.

**Comment by LukasWieditz** [comment]
There is a button for random color, it just doesn't work cause there's some javascript error @kylerc

**Comment by mikecreuzer** [comment]
Ah OK. Can it be automatically done on page load as well?

**Comment by mikecreuzer** [comment]
Uh, sorry for wrong git issue repo too :P

**Comment by LukasWieditz** [comment]
Yeah, pretty sure the field can be auto populated on script load if empty.

**Comment by LukasWieditz** [comment]
Generating random material colors on page load now, and random button is working as it should.
