### ISSUE TITLE
ripple button causing scrolling side effects

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#67]
When used on an XF component with XF tab overflow (such as navigation, tabs, etc..) it causes an overflow scroll-x issue, and an overflow-scroll y issue on windows.

**Comment by kylerc** [comment]
Report of it https://xenforo.com/community/threads/quick-look-at-ui-x-2.126555/page-10#post-1191694

**Comment by nsaneman** [comment]
@kylerc This is still an issue in RC3 with Firefox.

![72cb0aa6b4](https://user-images.githubusercontent.com/26636634/33152013-5402b7ca-cfd2-11e7-8563-4dcd751a1736.gif)

**Comment by nsaneman** [comment]
@kylerc This is still an issue in RC3 when using Firefox.

![72cb0aa6b4](https://user-images.githubusercontent.com/26636634/33152013-5402b7ca-cfd2-11e7-8563-4dcd751a1736.gif)
