### ISSUE TITLE
Post thread widget changes

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#674]
<img width="332" alt="screen shot 2018-06-07 at 3 17 06 pm" src="https://user-images.githubusercontent.com/1217271/41123925-e6ffbf5e-6a65-11e8-895f-783cc6a7fbc4.png">

- [x] Remove ellipses on post thread button (and pencil icon means edit normally? maybe change that?)
- [x] Default title 'Start a thread'
- [x] Default description 'Ask a question, post a suggestion, start a discussion'
- [x] Default button title 'Create thread
- [x] I think button padding is off

**Comment by Ian-Hitt** [comment]
@mikecreuzer I think it should probably stay "post thread." This is the phrase that Xf uses everywhere for posting a thread. Would be weird to change it in one place. Either that or we change the phrase itself for UI.X. The ellipses for some reason is part of the phrase.

XF uses pencil icon to denote creating a thread. I suppose I don't care either way, but I think the pencil is fine to leave alone.

**Comment by mikecreuzer** [comment]
<img width="301" alt="screen shot 2018-06-08 at 9 33 18 am" src="https://user-images.githubusercontent.com/1217271/41163934-989c3be0-6aff-11e8-8b12-ad0b3845cfab.png">

Paddings are off. THere is more space between text than there is the widget padding itself. it should be reversed if anything or at least the same
