### ISSUE TITLE
Flare - 'Contact us' modal input styling issue

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#688]
As per title, on the email address & subject inputs (name input also misaligned):
![image](https://user-images.githubusercontent.com/34864926/41420623-d35fbc24-6fec-11e8-88b5-78a5916da3d2.png)

**Comment by Ian-Hitt** [comment]
@tom-coward Looks to be the intended styling by XF (for some reason.) Bug in default theme as well.
