### ISSUE TITLE
UI.X Pro - Visitor tabs position and  Search position

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#699]
Visitor tabs position are sub-navigation are not work. also not work for  Search position.

**Comment by mikecreuzer** [comment]
What specifically isn't working?

**Comment by Nirjonadda** [comment]
I have set sub-navigation but its still in place navigation.

**Comment by Ian-Hitt** [comment]
@Nirjonadda Is the sub navigation bar appearing at all? Those location SPs only work above the breakpoint for the bar. Refer to the `  Viewport width to remove the sub-navigation` style property

**Comment by Nirjonadda** [comment]
You can check out in my demo site.

**Comment by Ian-Hitt** [comment]
@Nirjonadda remind me again where your demo is :)

**Comment by Nirjonadda** [comment]
check in xenforo, yesterday i have send demo info.

**Comment by Ian-Hitt** [comment]
@Nirjonadda I enabled sub navigation on your UI.X Pro C theme, and it is working as intended. You did not have sub navigation enabled on any themes
<img width="1206" alt="screen shot 2018-06-23 at 9 59 16 am" src="https://user-images.githubusercontent.com/15836384/41810926-29baa65c-76cc-11e8-81bd-1a16591554b2.png">

**Comment by Nirjonadda** [comment]
@Ian-Hitt where can enable sub navigation?
