### ISSUE TITLE
UI.X Pro - Navigation position

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#700]
add support navigation can be place under the logo when Navigation type is default.

![screenshot00035](https://user-images.githubusercontent.com/6899856/41605140-1d7b8ea8-73e1-11e8-9588-595414647f5c.png)

**Comment by mikecreuzer** [comment]
This is supported. It won't go next to the tab bar, but you can set the navigation to be on its own line. I believe the setting actually is in UI.X Logo and involves moving it to the LogoBlock.

**Comment by Nirjonadda** [comment]
not find out, do you a preview?

**Comment by Ian-Hitt** [comment]
@Nirjonadda SP `Minimum viewport width to show logo block` controls that.
