### ISSUE TITLE
UI.X Pro - Logo text

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#701]
Logo text are not working, i have removed Logo URL but still are not show logo text valve.

**Comment by Ian-Hitt** [comment]
Unable to replicate this issue. You removed logo AND 2x logo urls, correct?

**Comment by Nirjonadda** [comment]
Yes.

**Comment by Ian-Hitt** [comment]
<img width="648" alt="screen shot 2018-06-23 at 10 12 40 am" src="https://user-images.githubusercontent.com/15836384/41811056-f9b5bc9c-76cd-11e8-9fe6-367b0d05aca2.png">

This is working properly on your demo.
