### ISSUE TITLE
[UI.X] Collapsible extra info

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#703]
Can not open Collapsible extra info after the post reply.

![screenshot00036](https://user-images.githubusercontent.com/6899856/41606767-bb0a7456-73e4-11e8-92f5-b1c065f311af.png)

**Comment by Ian-Hitt** [comment]
@Nirjonadda unable to replicate. can you provide more info?

**Comment by Nirjonadda** [comment]
https://giant.gfycat.com/BlindSorrowfulAfricanharrierhawk.webm

**Comment by Ian-Hitt** [comment]
<img width="516" alt="screen shot 2018-06-23 at 10 00 27 am" src="https://user-images.githubusercontent.com/15836384/41810930-42d284a2-76cc-11e8-8540-15eab079e3af.png">

This is working properly for me on your site. Is there any other information you can provide regarding this?

**Comment by Nirjonadda** [comment]
Does you checked after post, without reloading this page?

**Comment by Ian-Hitt** [comment]
Ah apologies, I see the problem and can now replicate.

**Comment by mikecreuzer** [comment]
Assigning back to you as this has been many months.

**Comment by Ian-Hitt** [comment]
Fixed in https://github.com/jonw316/xf2/commit/a011904815219f4ee2713adde3de410d96915324
