### ISSUE TITLE
UI.X Pro - edit avatar

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#704]
edit avatar full text are not showing.

![screenshot00037](https://user-images.githubusercontent.com/6899856/41606920-184fafc8-73e5-11e8-93f0-50023825acf8.png)

**Comment by daltonp** [comment]
I am able to confirm this on the UI.X Pro Beta demo as well
![editavatarui xprobug](https://user-images.githubusercontent.com/32306910/41678346-77b30ea0-7490-11e8-8e20-f211d75333da.gif)
