### ISSUE TITLE
UI.X Pro - Minimum viewport width to show logo block

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#708]
using Minimum viewport width to show logo block to 150% then logo will be show two time.

![screenshot00042](https://user-images.githubusercontent.com/6899856/41613812-f8f712d0-73f6-11e8-96fb-374ff9815df0.png)

from this: https://github.com/Audentio/xf2theme-issues/issues/700#issuecomment-398474677

from this: https://github.com/Audentio/xf2theme-issues/issues/702

**Comment by Ian-Hitt** [comment]
@Nirjonadda You cannot use percentages with media queries. The screen is always 100% width of itself.

**Comment by Nirjonadda** [comment]
If this so how to controls Navigation position? also why logo showing two time?

https://github.com/Audentio/xf2theme-issues/issues/700#issuecomment-398474677
