### ISSUE TITLE
UI.X Pro - 'Post thread' modal issue

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#710]
From the 'Latest' page, the following displays:
![image](https://user-images.githubusercontent.com/34864926/41653924-ff407f5a-7487-11e8-92fa-9b105298c7ac.png)

Assuming this is because I have no topics created. Should maybe include an error message, similar to how it's done here:
![image](https://user-images.githubusercontent.com/34864926/41653971-2b48fb2c-7488-11e8-97ef-4034ad3a5dfd.png)

**Comment by LukasWieditz** [comment]
Closing this. Refer to the linked issue.
