### ISSUE TITLE
Navigation on chrome for android falling out of place when scrolling up

### ISSUE THREAD

**Issue by LukasWieditz** [Audentio/xf2theme-issues#711]
Scrolling up on chrome for android hides the browsers URL bar, but the page navigation doesn't fill up the empty space, it just sticks where it was until you close and reopen it.

**Comment by LukasWieditz** [comment]
Samsung Galaxy Alpha with latest Chrome for Android. Happens when you open up the mobile navigation, then slowly scroll up so the URL bar is hidden. Even when you stop dragging the page, the navigation won't fill up the empty space.

**Comment by mikecreuzer** [comment]
How is it falling out of place, do you have screen per chance?

**Comment by LukasWieditz** [comment]
![screenshot_2018-06-30-15-04-58](https://user-images.githubusercontent.com/38475165/42125443-2a7d82ac-7c77-11e8-9794-15618c0ad2f9.png)
![screenshot_2018-06-30-15-05-08](https://user-images.githubusercontent.com/38475165/42125444-2ca07f12-7c77-11e8-9540-ae19992aa566.png)

**Comment by Ian-Hitt** [comment]
Fixed in our last release. The sticky top didn't account for the hiding/showing address bar.
