### ISSUE TITLE
UI.X Pro - Navigation type

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#714]
can not re-eanable Navigation type to sidebar navigation.

**Comment by daltonp** [comment]
I'm not able to replicate this on the beta board. I'm guessing you set it to default before setting it back to sidebar navigation? Did you get any errors after doing so?

**Comment by Nirjonadda** [comment]
Yes but no error, @Ian-Hitt can look into in my demo forum.

**Comment by Ian-Hitt** [comment]
@Nirjonadda It is only applicable with a covered style theme

**Comment by mikecreuzer** [comment]
@Ian-Hitt do we state this on documentation?
