### ISSUE TITLE
Footer getting rounded border calculated

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#718]
<img width="113" alt="screen shot 2018-06-26 at 10 50 43 am" src="https://user-images.githubusercontent.com/1217271/41924135-d3a8fb6e-792e-11e8-8f58-7c0137ca2703.png">

**Comment by mikecreuzer** [comment]
Not sure if this is an issue with the calculation function. Im on pro.

**Comment by Ian-Hitt** [comment]
@mikecreuzer Unable to replicate. may have just rendered incorrectly

**Comment by mikecreuzer** [comment]
Its a bug. We screenshared so not sure why the label, it is indeed happening, the reason is why. It happens on Firefox and incognito window, on your board. We can try to replicate it after the release, but would rather not. Your machine is offline or I would try to debug it.

**Comment by LukasWieditz** [comment]
This is happening on all UI.X based styles. The `p-footer-inner` wrongly gets the `uix_smartBorder--default` class assigned by some JavaScript @kylerc . We can either counter this by explicitly overriding this in the css or trying to fix this on JS side, although I'm not sure if that's feasible.

**Comment by LukasWieditz** [comment]
Yeah, Subnav gets the bottom border. Essentially the same script that applies it here I assume.

**Comment by mikecreuzer** [comment]
<img width="1093" alt="screen shot 2018-07-03 at 4 00 24 pm" src="https://user-images.githubusercontent.com/1217271/42244336-416d3e98-7eda-11e8-9885-2b21c72e8d8a.png">

Its all components.

**Comment by Ian-Hitt** [comment]
The issue here was that the option was reversed in 2.0 (add radii vs remove radii). Therefore, the topion should be disabled on covered themes, and it was not. It was behaving as intended. It should only be enabled for wrapped and fixed page styles, not covered (default.) This has been disabled in UI.X, but I just now realized this was the issue. My bad :0
