### ISSUE TITLE
Ability to add welcomeblock to custom pages

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#730]
In XF1 we could just do `<xen:container var=“$uix_showWelcomeBlock”>1</xen:container>` on a specific route or index template, and this would set welcome block (which had code in page_container) show up.

@Ian-Hitt says @JakeBooher set it up in a way where this cannot be done. Would like a solution for this.

**Comment by LukasWieditz** [comment]
```<xf:page option="uix_showWelcomeSection" value="{{true}}" />```

**Comment by mikecreuzer** [comment]
Does this currently work?

**Comment by Ian-Hitt** [comment]
@LukasWieditz that ignores user permissions though. He wants to add a welcome block to a page that still respects user permissions

**Comment by LukasWieditz** [comment]
Should've been more specific then...

**Comment by Ian-Hitt** [comment]
@LukasWieditz this done on your end?
