### ISSUE TITLE
UI.X 2 - Horizontal rule showing for guests (with no options underneath)

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#738]
As per title:
![image](https://user-images.githubusercontent.com/34864926/42736366-b6ec3d40-885d-11e8-9cb1-80fcfe6cac61.png)

Same issue in posts, resource reviews etc...

**Comment by Ian-Hitt** [comment]
This appears to be a bug in the default theme (although they do not have as much padding or a border.) The issue is that the same container div is used for child replies, so it cannot be hidden.

**Comment by Ian-Hitt** [comment]
@kylerc would like your suggestion next time you have a free moment to spare.

**Comment by Ian-Hitt** [comment]
Found a fix

**Comment by mikecreuzer** [comment]
Reference commit so I can see what it was
