### ISSUE TITLE
UI.X 2 - Inconsistent buttons

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#739]
There is some inconsistent button styling, for example here on a resource listing page:
![image](https://user-images.githubusercontent.com/34864926/42736402-22bb6ae6-885e-11e8-9b63-acb5cc4596ef.png)

**Comment by Ian-Hitt** [comment]
This button is missing the pre-requisute `button--link` class. It may work in some themes (including the default), but it is specifically missing the required button link class intended to add this styling.
