### ISSUE TITLE
UI.X - Conversation recipients styling issue

### ISSUE THREAD

**Issue by tom-coward** [Audentio/xf2theme-issues#749]
As per title:
![image](https://user-images.githubusercontent.com/34864926/43367093-94312008-933f-11e8-8da6-7b4e5493d4bf.png)

**Comment by daltonp** [comment]
I'm not able to replicate this on the public demo or our beta forum. Are you using the latest version of UI.X?

**Comment by tom-coward** [comment]
Yep, running 2.0.7.2.0
