### ISSUE TITLE
Icon shows when someone posts in a forum/thread

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#759]
This is a feature suggestion that came from one of our tickets. #11546
Said customer suggests that an option is added if said forum doesn't use avatars, that an icon is shown to the user so that they know if they've posted in that forum or thread.

**Comment by Ian-Hitt** [comment]
Hmm? Forum doesn't use avatars? Is that a thing...?

**Comment by Ian-Hitt** [comment]
You cant disable avatars. That must be a customization, which we obviously don't support since UI.X doesn't have a "disable avatar" feature.

**Comment by RicoGiesler** [comment]
Hello.
Please reopen the issue.
I have never said something about avatars.
I just want a user to be able to see in the list whether he has already written something in the thread or not.
If he had postet something in the thread, then theres should be a little icon. (like the "watched" icon)

**Comment by RicoGiesler** [comment]
Here is a picture to show you what i mean.
<img width="901" alt="ashampoo_snap_2018 08 21_11h32m19s_002_" src="https://user-images.githubusercontent.com/43111292/45340377-9edff780-b596-11e8-9f65-db3d89e6bb61.png">
It would be very nice if there could be a special sign if i still have posted in this thread.
Like the "watched" sign.

**Comment by Ian-Hitt** [comment]
There is no need for an icon because there is an indicator on the avatar instead. Removing the avatar isn't a feature of the default theme, or of UI.X. Generally speaking, we don't add support for features that don't exist in the theme.
