### ISSUE TITLE
Drift (Header)

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#778]
I am using Similar Thread widget and the header/bg color is missing. I notified the developer and has clarified he is using default Xenforo class as it works with the default Xenforo theme. Screenshots provided.
![st](https://user-images.githubusercontent.com/34584920/45231236-4c1aed00-b2c3-11e8-96e2-1296237503dc.png)
![st2](https://user-images.githubusercontent.com/34584920/45231237-4c1aed00-b2c3-11e8-80e8-e93483f6e074.png)

**Comment by Ian-Hitt** [comment]
The background missing here is intentional. You can add it back in Style Properties > Block > Block Header
