### ISSUE TITLE
Drift (Resources Page)

### ISSUE THREAD

**Issue by legendofmir3** [Audentio/xf2theme-issues#781]
Resources page.

Orange: Button colour is not noticeable.
Blue: The reactions are too close to the description, looks odd.
Green: the tabs are not so clear.
Red: The resource icon is not inline with the forum wrapper or whatever you call it.
Note: the wrapper is missing a border line.
![resource](https://user-images.githubusercontent.com/34584920/45231332-9308e280-b2c3-11e8-9bbd-365a18210193.png)

**Comment by Ian-Hitt** [comment]
Tabs are intentional here
