### ISSUE TITLE
Drift styling issues

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#799]
![articles are out of the wrapper](https://user-images.githubusercontent.com/43339306/45679492-aec88000-bb30-11e8-99fc-84eb953a76a7.jpg)
![articles](https://user-images.githubusercontent.com/43339306/45679493-aec88000-bb30-11e8-8d2a-c7b5f51a9f36.png)
![border still there](https://user-images.githubusercontent.com/43339306/45679496-aec88000-bb30-11e8-9599-346701409d69.png)
![breadcrumb](https://user-images.githubusercontent.com/43339306/45679497-af611680-bb30-11e8-8d2c-81dbc9b4220b.jpg)
![buttons](https://user-images.githubusercontent.com/43339306/45679498-af611680-bb30-11e8-81f5-6feb31fb1d50.png)
![downloaded resources](https://user-images.githubusercontent.com/43339306/45679500-af611680-bb30-11e8-8d6e-642646a4e762.png)
![favicon still on](https://user-images.githubusercontent.com/43339306/45679501-af611680-bb30-11e8-8422-35956f721d5b.png)
![footer padding](https://user-images.githubusercontent.com/43339306/45679503-aff9ad00-bb30-11e8-802a-9b3be06b119c.png)
![footer](https://user-images.githubusercontent.com/43339306/45679504-aff9ad00-bb30-11e8-95ce-91d18beb0a36.jpg)
![footer](https://user-images.githubusercontent.com/43339306/45679505-aff9ad00-bb30-11e8-9c08-f0e839f5b5e3.png)
![header with border still](https://user-images.githubusercontent.com/43339306/45679506-aff9ad00-bb30-11e8-82fd-014dec2dd91e.jpg)
![login](https://user-images.githubusercontent.com/43339306/45679507-aff9ad00-bb30-11e8-918d-b87d777dcb18.png)
![media icon](https://user-images.githubusercontent.com/43339306/45679508-b0924380-bb30-11e8-9fdf-b96e1dd8f7ed.png)
![media page](https://user-images.githubusercontent.com/43339306/45679509-b0924380-bb30-11e8-8629-231863862bc7.png)
![out of wrapper 2](https://user-images.githubusercontent.com/43339306/45679510-b0924380-bb30-11e8-8de0-3652e92630a9.png)
![out of wrapper](https://user-images.githubusercontent.com/43339306/45679511-b0924380-bb30-11e8-9e07-e4c41ce5e259.png)
![register](https://user-images.githubusercontent.com/43339306/45679512-b12ada00-bb30-11e8-866a-bb3e7482acdb.png)
![search](https://user-images.githubusercontent.com/43339306/45679513-b12ada00-bb30-11e8-8bc0-a93a80e013ce.png)
![sidebar links](https://user-images.githubusercontent.com/43339306/45679514-b12ada00-bb30-11e8-9a72-756653e46303.jpg)
![sidebar widgets](https://user-images.githubusercontent.com/43339306/45679515-b12ada00-bb30-11e8-8f6b-b1e854d40544.jpg)
![sidebar](https://user-images.githubusercontent.com/43339306/45679517-b12ada00-bb30-11e8-93b7-b99609b22eba.png)
![user links](https://user-images.githubusercontent.com/43339306/45679518-b1c37080-bb30-11e8-8acc-0b6245b2b837.png)
![what is this gap](https://user-images.githubusercontent.com/43339306/45679519-b1c37080-bb30-11e8-9d1c-f56b6a7670fc.png)

**Comment by joyfreak** [comment]
![notice footer](https://user-images.githubusercontent.com/43339306/45684567-a37c5100-bb3e-11e8-9f14-318ccd3a6496.jpg)

Another one

**Comment by mikecreuzer** [comment]
Closing this as there are separate issues for each now
