### ISSUE TITLE
Drift - Border line still being soon in the Media Manager

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#802]
![drift-issue-three](https://user-images.githubusercontent.com/32306910/45694322-a407ee00-bb24-11e8-8349-12f90fc3ec81.png)
![drift-issue-seven](https://user-images.githubusercontent.com/32306910/45694854-cb12ef80-bb25-11e8-8cb3-2ed4438c1712.jpg)

**Comment by Ian-Hitt** [comment]
This is a customization issue that is not apparent in the default theme
