### ISSUE TITLE
Drift - Unnecessary Padding on Footer

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#806]
![drift-issue-six](https://user-images.githubusercontent.com/32306910/45694694-6f486680-bb25-11e8-9802-0c655cadb632.png)
![drift-issue-six](https://user-images.githubusercontent.com/32306910/45694792-a9196d00-bb25-11e8-909c-26bee2e07d4c.jpg)

**Comment by Ian-Hitt** [comment]
This is because the extended footer is disabled, so margin bottom needs to be adjusted in custom theme
