### ISSUE TITLE
Drift - Profile Comment Improvements

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#808]
![drift-issue-nine](https://user-images.githubusercontent.com/32306910/45694941-fa296100-bb25-11e8-866f-e2919180bc7c.png)

**Comment by Ian-Hitt** [comment]
The missing border bottom is intentional to remove unnecessary whitespace for a condensed component.

**Comment by Ian-Hitt** [comment]
The inline text on sub comments is intentional styling in XF default theme
