### ISSUE TITLE
Drift - Search Bar Sizing

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#810]
![drift-issue-tweleve](https://user-images.githubusercontent.com/32306910/45695161-7459e580-bb26-11e8-8174-8058b5125d01.png)

**Comment by joyfreak** [comment]
![with line](https://user-images.githubusercontent.com/43339306/45712475-5a4ef000-bb84-11e8-9c4a-495932e26106.png)


make this so its inline with the line above
