### ISSUE TITLE
Cookie Notice Alignment

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#814]
![drift-issue-seventeen](https://user-images.githubusercontent.com/32306910/45695636-6d7fa280-bb27-11e8-8529-6e2eeff01289.jpg)

**Comment by mikecreuzer** [comment]
Lack of padding on mobile, and buttons get misaligned as you resize down. 

![image](https://user-images.githubusercontent.com/1217271/45760070-e0a01c00-bbee-11e8-9658-f112623df1ad.png)
