### ISSUE TITLE
SideNav Pro

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#825]
Move the SideNav to the right side, as even though it is not a widget, it sure looks like one and no one needs to know this either. It will look a lot better being on the right, makes it easy on the easy.

![sidebar](https://user-images.githubusercontent.com/43339306/45771325-b8d7a500-bc3c-11e8-9b24-fb44b4da928b.png)

**Comment by mikecreuzer** [comment]
Its handled differently. The way it works is just you can think of SideNav as being left, and sidebar being right. Only certain pages have sidenav. I get the thought process, we had thought about this and opted against it
