### ISSUE TITLE
XenPorta Article View on Pro Theme

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#826]
![articles thread view](https://user-images.githubusercontent.com/43339306/45772936-eb839c80-bc40-11e8-9bcb-02fea0417b58.png)

I have to zoom out to show it all but on article/thread view of XenPorta, it shows two duplicate posts as seen here: https://www.joyfreak.com/threads/samutale-celebrates-two-year-mark-with-free-to-play-week.18443/

**Comment by mikecreuzer** [comment]
Can you enable default style on your board? I would assume this is happening there. Not specific to Pro, as its happening on Drift as well.

**Comment by joyfreak** [comment]
Ah yes. That got me thinking so the one thing that stuck out for me was the [TH] Comments add-on. Disabled it and it disappeared. Can you move this to the add-on section? Thanks.

**Comment by mikecreuzer** [comment]
Ah yes I get why. Created the issue here https://github.com/Audentio/xf2addon-issues/issues/762
