### ISSUE TITLE
Navigation collapse on XenPorta Ui.X PRO

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#827]
![theme](https://user-images.githubusercontent.com/43339306/45773542-87fa6e80-bc42-11e8-8265-c842bc77614d.png)

This is what happens when you collapse the side navigation on the left.

**Comment by mikecreuzer** [comment]
This isnt exactly a bug. Its just those images arent large enough. I see the same thing, but thats what I would expect. Unless you have a different. Same thing happens on drift and I would assume default

**Comment by joyfreak** [comment]
It does not happen same thing with drift because drift does not have a collapsible navigation on the left side. Neither does the default. It seems fine on the default and drift styles. Only this style has the issue.

**Comment by joyfreak** [comment]
![sidenavw](https://user-images.githubusercontent.com/43339306/45774678-83838500-bc45-11e8-9dee-92a6f3dab149.png)

This is it when I click the collapse again. Refresh and it fixes. Defo to do with the sidenav/style.

**Comment by joyfreak** [comment]
@Ian-Hitt
