### ISSUE TITLE
Horizontal scrolling with UIX 2 - 2.0.10

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#829]
Style Name: UIX 2 

Style Version: 2.0.10

UI.X Add-on Version: 2.0.8. beta 1

XenForo Version: 2.0.10

Operating System (and Version):

Browser Name (and Version):

Can you replicate this issue on our demo for this theme?

Does this issue happen in the default XenForo style?

Summary of issue:

Horizontal scrolling in mobile view.

Detailed steps to reproduce the issue:

Go to any thread, for example here: https://canadiancorvetteforums.com/threads/what-to-do-with-your-c5-this-weekend-just-drift-on-by.21258/ 

On a mobile device. Scroll up and down and you'll start seeing some horizontal scrolling. This is new since 2.0.10.

Upload any screenshots related to the issue below

**Comment by teamracing** [comment]
May or maynot be related to #832 . 

I'm finding that the issue goes away if I remove .message-actionBar .actionBar in the message footer so could be related.

**Comment by ichpen** [comment]
May or maynot be related to #832 .

I'm finding that the issue goes away if I remove .message-actionBar .actionBar in the message footer so could be related.

**Comment by ichpen** [comment]
Taking out margin: -@xf-messagePadding; (which was -10) from message action bar style property seems to have resolved this issue but you may want to revisit it.

**Comment by Ian-Hitt** [comment]
This is broken in just your child theme, we made changes in UI.X message component padding for 2.0.10.0 and the child theme will need to revert or match those changes

**Comment by ichpen** [comment]
@Ian-Hitt so which templates should I revert in my child theme?
