### ISSUE TITLE
Border overflow UIX 2 - 2.0.10

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#832]
As per screenshot top border for .message-actionBar .actionBar is busting through the message container. It appears to only happen for posts where reaction buttons exist.

![border-overflow](https://user-images.githubusercontent.com/5346876/45909612-c4f46b80-bdd0-11e8-9113-1f42dc173d7e.png)

See any thread like this one for examples: https://canadiancorvetteforums.com/threads/the-rebuild-process-has-restarted-again.18536/

**Comment by Ian-Hitt** [comment]
This was changed in 2.0.10.0 and will need to be adjusted in your child theme. Remove the negative margins on the footer
