### ISSUE TITLE
UI.X - Register are not open popup

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#836]
As designed or bug? Register are not open popup.

**Comment by Nirjonadda** [comment]
![screenshot00383](https://user-images.githubusercontent.com/6899856/46228847-b9221f80-c363-11e8-93c7-caf74b74792d.png)

**Comment by Nirjonadda** [comment]
![screenshot00384](https://user-images.githubusercontent.com/6899856/46228922-f8507080-c363-11e8-8beb-fd2733ffbebf.png)

**Comment by Ian-Hitt** [comment]
This is a style property
