### ISSUE TITLE
UI.X 2 - Post Thread avatar doesn't size up to the postbit avatar

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#838]
Style Name: UI.X 2

Style Version: 2.0.10

UI.X Add-on Version: 2.0.8 Patch Level 1

XenForo Version: 2.0.10

Operating System (and Version): Windows 8.1

Browser Name (and Version): Version 69.0.3497.100 (Official Build) (64-bit)

Can you replicate this issue on our demo for this theme? Yes

Does this issue happen in the default XenForo style? No

Summary of issue: When changing the size of the postbit avatar to large, the avatar shown below it when posting a thread doesn't match the postbit avatar size.

Detailed steps to reproduce the issue: Navigate to Appearance -> Style Properties -> Messages -> Postbit Avatar Size -> Set to large

Upload any screenshots related to the issue below 
![screen shot 2018-09-24 at 12 52 52 pm](https://user-images.githubusercontent.com/32306910/45969548-9efddf80-bff9-11e8-85b4-3dd1a644245a.png)

**Comment by Ian-Hitt** [comment]
This is intentional
