### ISSUE TITLE
Compare typographical and macro level components to YouTube

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#844]
As YouTube is the best use case for comparing components, lets check what they do for certain things like:

- [x] Mobile font size
- [x] Mobile buttons
- [x] Mobile headings

- [x] Desktop font size
- [x] Desktop buttons
- [x] Desktop headings

<strike>- [ ] Dark theme color values</strike>
<strike>- [ ] Light theme color values</strike>

- [x] Hover states

- [x] Header
<strike>- [ ] Main Side Navigation</strike>
- [x] Sidebar

**Comment by Ian-Hitt** [comment]
- Youtube uses #fff as page bg color, which influences their decision on component bg colors. We dont want to copy these unless we also change to #ff page bg
