### ISSUE TITLE
Add SP to hide style chooser from footer

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#845]
Ultimately, if using TH Style Switcher or other use case, you wont want the style chooser anymore

**Comment by Ian-Hitt** [comment]
You still want the style chooser if you have the add-on because the add-on only toggles between 2 themes

**Comment by mikecreuzer** [comment]
Im referring to XF style chooser. And yah Id be referring to anytime you want public themes but not showing it in the footer.
