### ISSUE TITLE
New thread modal - Bottom Margin

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#850]
Style Name:
UIX Pro
Style Version:

UI.X Add-on Version:
[TH] UI.X 2.0.8 Patch Level 1
XenForo Version:
v2.0.9
Operating System (and Version):

Browser Name (and Version):
Chrome
Can you replicate this issue on our demo for this theme?

Does this issue happen in the default XenForo style?

Summary of issue:
Turning off "Replace new thread modal with Topics new thread modal" - Large bottom margin between node list. May be how you want it to look but looks a little too big to me?
Detailed steps to reproduce the issue:
Turning off "Replace new thread modal with Topics new thread modal" - Large bottom margin between node list
Upload any screenshots related to the issue below
![image](https://user-images.githubusercontent.com/6074069/46907177-8f8dfa00-cf06-11e8-99e8-ac4e9acdb5e0.png)

![image](https://user-images.githubusercontent.com/6074069/46907169-7b49fd00-cf06-11e8-8f81-a69bd4a26934.png)

**Comment by Ian-Hitt** [comment]
Fixed in previous release
