### ISSUE TITLE
UIX 2 2.0.10 - XFMG mobile issues

### ISSUE THREAD

**Issue by ichpen** [Audentio/xf2theme-issues#853]
Go here with a mobile viewport (or shrink browser accordingly).
https://canadiancorvetteforums.com/media/20180818_110926-jpg.1260/

You'll note some horizontal movement and less than ideal mobile friendliness. It's specific to XFMG pages. I *believe* this is a new issue since 2.0.10 but can't be certain. Had a similar issue with message view which I figured out. I'm also getting this on Default theme but I don't see it on XF's default website so logging this with you first to have a look.

**Comment by Ian-Hitt** [comment]
If this happens in default theme, then it is not theme related, but rather probably related to another add-on
