### ISSUE TITLE
UI.X 2 - Add a log button in addiction to the register button on the Welcome Block

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#854]
It was suggested that an additional button is added above or below the register button on the Welcome Block. This button in question would either be "Log" or "Login" perhaps.

**Comment by mikecreuzer** [comment]
The welcome block is mainly there as a call to action. Login doesn't quite make sense as a call to action, as the real estate should prioritize new members not existing ones. (but you can add it to the description or manually if you need)

Not something we'll add to core
