### ISSUE TITLE
UI.X - Threadview Deleted Thread Edit / Checkbox Alignment Bug

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#856]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 / 64-Bit Latest Stable

Browser Name (and Version): Chrome 70 / 64-Bit Latest Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When viewing the threadlist, you will see that the "Edit" / Checkbox is on the left, when it should be on the right instead.

These screenshots should help:

uix_dark_deleted_thread_alignment_bug

**Comment by lilalien** [comment]
I wish some of these wouldn't be rushed sometimes, @Ian-Hitt .. I'm sure I or others can assist in replicating something if needed..

I can replicate it every time with a fresh UI.X Dark using the operating system and browser listed above... I know sometimes there was past difficulty finding something because people were testing on macs...

**Comment by mikecreuzer** [comment]
Can you screenshot it? Ill see if I can replicate.

**Comment by lilalien** [comment]
I had already screenshot, but I'll add another one...

![thread_list_edit_box_alignment_bug2](https://user-images.githubusercontent.com/35111972/47383767-66722400-d6d3-11e8-9136-3adaa61c0638.png)

**Comment by lilalien** [comment]
Happens on latest stable Microsoft Edge browser as well on Windows 10.

**Comment by mikecreuzer** [comment]
Ive seen this bug before. And I know you posted a way to replicate it. Not sure where that issue went. But I know its not easy to replicate for whatever reason. Removing unable to replicate tag as that is a bit ridiculous, we need to look into it a bit further. 

That said, I cannot replicate it on our demo at the moment. 

Also we should have tagged your other issue apologies. Copied from https://github.com/Audentio/xf2addon-issues/issues/981

**Comment by mikecreuzer** [comment]
@Ian-Hitt lets do @lilalien a favor here and post whatever the issue was. Helps me out too as Im not sure what was wrong, he's reported this at least 3 times now

**Comment by Ian-Hitt** [comment]
I missed that it was for deleted threads only. For whatever reason, deleted threads use a separate macro entirely than other thread items, as opposed to just having a flag on the same macro.
