### ISSUE TITLE
UI.X Dark - Threadview Inline New Thread Vertical Button Alignment

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#857]
Style Name: UI.X Dark

Style Version: Latest

UI.X Add-on Version: Latest

XenForo Version: Latest

Operating System (and Version): Windows 10 / 64-Bit Latest Stable

Browser Name (and Version): Chrome 70 / 64-Bit Latest Stable

Does this issue happen in the default XenForo style? No.

Summary of issue: When viewing the threadview page in UI.X Dark, and using the inline new thread functionality, the "Post Thread" and "More Options" buttons are not aligning properly. This is exactly the same issue as the Search popup box that @Ian-Hitt already fixed! I don't see the issue anywhere else.

These screenshots should help:

thread_view_inline_new_thread_vertical_alignment_uix_bug

**Comment by lilalien** [comment]
Still happening in the latest UI.X Dark.

Chrome 64 + Windows 10

Have you tried applying the exact fix that handled the header search popup box button alignments?

**Comment by lilalien** [comment]
That fix was discussed in our private slack chat around August 24.

**Comment by lilalien** [comment]
I can still reproduce this in your default dark style on my Windows 10 PC using latest stable Chrome.

**Comment by Ian-Hitt** [comment]
Resolved this issue live with @lilalien
