### ISSUE TITLE
Pullout login menu improvements

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#86]
- [x] Margin far too large, in general some tidying up will be better
- [x] The animation seems choppy.
- [x] esc key should close it

<img width="1040" alt="screen shot 2017-10-30 at 10 33 21 am" src="https://user-images.githubusercontent.com/1217271/32179609-da197c40-bd5d-11e7-86b1-bff7942d8fb0.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer the margin issue is actually all form elements. closing and making a new issue regarding form styling
