### ISSUE TITLE
UI.X Pro - Full username

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#862]
Full username are not showing, I think this happened with [TH] Last Post Avatar add-on.

![screenshot00602](https://user-images.githubusercontent.com/6899856/47602922-66309c00-d9e5-11e8-9dd3-4470475f5528.png)

**Comment by Nirjonadda** [comment]
Also not showing thread full title when node grid enabled.

**Comment by Ian-Hitt** [comment]
This is from TH Nodes add-on, but is not an issue in the current release
