### ISSUE TITLE
UI.X Pro - Add SP for remove block for not Allow new messages to be posted in this forum.

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#868]
Add SP for remove block for not Allow new messages to be posted in this forum.

![screenshot00634](https://user-images.githubusercontent.com/6899856/47682617-44920900-dbcd-11e8-84ff-0fe6f1b43f83.png)

**Comment by Ian-Hitt** [comment]
This is an important message and should not be removed. I would suggest removing it with custom CSS if you think you do not need it.

**Comment by Nirjonadda** [comment]
@Ian-Hitt How can remove with CSS? Please can be give me this CSS code?
