### ISSUE TITLE
Should breadcrumb display if it only has one item? 

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#87]
For me, this depends on the view. UI.X itself looks odd, but perhaps if the breadcrumb was more centralized it might make more sense. 

Im not sure what is correct, but a style property might be a good option.

<img width="379" alt="screen shot 2017-10-30 at 10 34 32 am" src="https://user-images.githubusercontent.com/1217271/32179669-00169a90-bd5e-11e7-9ec3-696ec6c329c0.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer there is a style property to hide it on level 1 views

**Comment by Ian-Hitt** [comment]
meaning hide it if there is only 1 crumb. so yes, i agree, and done and done :)

**Comment by mikecreuzer** [comment]
Does it auto-remove if only one item or just  style property

**Comment by mikecreuzer** [comment]
if if $crumb.length <= 1
