### ISSUE TITLE
UI.X Pro - Move category strip outside wrapper

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#874]
Disabling Move category strip outside wrapper are category title out of the box. Add some margin for show below. 

![screenshot00677](https://user-images.githubusercontent.com/6899856/47956895-e25e4d00-dfac-11e8-9218-5d013a92f0f5.png)

**Comment by daltonp** [comment]
Able to replicate this on one of our demo's as well.

**Comment by Ian-Hitt** [comment]
@Nirjonadda There is padding 0 set in the style property. Remove it.

**Comment by Nirjonadda** [comment]
@Ian-Hitt Category Strip > Padding > Top?

![screenshot00688](https://user-images.githubusercontent.com/6899856/48079997-ee385200-e1ec-11e8-8b67-37358761a27a.png)
