### ISSUE TITLE
UI.X Pro - Email buttons not showing correctly for mobile

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#876]
View all your conversations are not show correctly from mobile view.

![screenshotcapture_2018_11_01_23_39_55_375](https://user-images.githubusercontent.com/6899856/47956955-dc1ca080-dfad-11e8-8b43-ae43ff2ca32e.jpg)

**Comment by mikecreuzer** [comment]
I think this is an email template?
