### ISSUE TITLE
UIX Dark - I think navigation row doesnt need to be dark, can be a color just like the light version

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#879]
This to me is not needed. Will move towards less things customized in the dark theme

**Comment by Ian-Hitt** [comment]
I'm not sure what you're suggestion specifically, but I imagine this is not a bug?

**Comment by mikecreuzer** [comment]
Dark:

![image](https://user-images.githubusercontent.com/1217271/48505563-f441ba80-e80c-11e8-8179-521956f60b6b.png)


Light:

![image](https://user-images.githubusercontent.com/1217271/48505588-002d7c80-e80d-11e8-83aa-7a7b44984dae.png)

I want almost no style properties edited between dark/light. Ideally just color palette. I felt that this was an unnecessary change and makes adding a dark theme that much more difficult. Its a small thing, just revert the navigation/header colors to be default. Reset the SPs.

**Comment by Ian-Hitt** [comment]
I personally feel like UI.X Dark has been out far too long to make such a jarring change, even if it is easy for everyone to put back. I also feel like this dark theme looks really poor with a colored header.

The only change is just the bg colors of the bars. There are no text color changes or anything. To me, these reasons outweigh having to change a couple bg colors when making a dark theme

**Comment by Ian-Hitt** [comment]
Here is a screenshot of reverting just for references sake
<img width="1486" alt="screen shot 2018-11-16 at 3 32 22 pm" src="https://user-images.githubusercontent.com/15836384/48648414-dca53600-e9b4-11e8-9dbd-076e0caec205.png">

**Comment by mikecreuzer** [comment]
Yeah Dark should really just be a color palette. The more I think about it, like with the style switcher, the more it makes sense. We shouldnt have changed the header color arbitrarily

**Comment by mikecreuzer** [comment]
This header thing is just one instance, but ultimately I feel like dark should just be UI.X with a dark palette, no other changes.

**Comment by lilalien** [comment]
I'm all for keeping it simple, just don't break WTF.com for Christmas. lol ;)

**Comment by Ian-Hitt** [comment]
Alright, I have made this change. But let it be known, I am not happy about it :(

**Comment by Ian-Hitt** [comment]
Note: To change back, change header bars to use background color value `@xf-contentAltBg`
