### ISSUE TITLE
Margin below tabs? Not sure if its all tabs

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#88]
This margin is epic.

<img width="709" alt="screen shot 2017-10-30 at 10 35 41 am" src="https://user-images.githubusercontent.com/1217271/32179713-1f5a0b8a-bd5e-11e7-9efc-227cac349f82.png">

**Comment by Ian-Hitt** [comment]
@mikecreuzer that padding is intentional as part of XF overflow scroll function. But that is not where that space is coming form (the tabs have a negative margin for the same amount. )

The issue is that the pageNav component below it doesn't have a content check. Fixed now.
