### ISSUE TITLE
Blanking out the `Staff tools bar` typography on uix dark breaks the entire theme

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#883]
Very very odd that this is the case, didnt look into why. I just wanted my theme to inherit and not have any value. Blanking the color/font-size should not do this so I assume there is some malformed CSS somewhere?

**Comment by Ian-Hitt** [comment]
@mikecreuzer this is a less compile error. XenForo default references the value for the color. This is simply an issue of using a preprocessor, and is apparent in many other places throughout the entire framework as well.
