### ISSUE TITLE
Disable Smart Breadcrumb Hide as the default and add 2 SPs

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#886]
- [ ] Disable the "hide breadcrumb if only one item thing" as being the default, Smart Breadcrumb Hide
- [ ] Smart Breadcrumb Hide should not hide if there are buttons or anything on that location
- [ ] Add SP to hide on index page (this would mean like trending, new post, anything we define as an index page. 

May even be worth formally defining certain routes with like `<xf:set var="$isAnIndexPage">1</xf:set>` so we can apply other SPs in this way

**Comment by Ian-Hitt** [comment]
@mikecreuzer Apologies, I misspoke. XenForo does in fact hide the breadcrumb by default, not UI.X
