### ISSUE TITLE
UI X (Dark) - Missing Username on Deleted Posts

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#889]
Style Name: UI.X Dark

Style Version: Latest Stable

UI.X Add-on Version: Latest Stable

XenForo Version: Latest Stable

Operating System (and Version): Windows 10 / 64-bit (Latest Stable)

Browser Name (and Version): Chrome 64-bit (Latest Stable)

Does this issue happen in the default XenForo style? No.

Summary of issue: Screenshot is easiest!

![deleted_post_missing_username_bug](https://user-images.githubusercontent.com/35111972/48138964-60ec1080-e273-11e8-80a4-8f0816604d13.png)

**Comment by daltonp** [comment]
I'm also able to replicate this on our demo as well.
![screen shot 2018-11-07 at 12 11 02 pm](https://user-images.githubusercontent.com/32306910/48151196-44a59f00-e286-11e8-9d87-d8242dccdabd.png)

**Comment by Ian-Hitt** [comment]
This is intentional by XenForo (not the theme.)
