### ISSUE TITLE
UI.X Notice close button and HTML link

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#892]
Notice close button are not show and HTML link are not working.

![screenshot00700](https://user-images.githubusercontent.com/6899856/48193449-c828c400-e34a-11e8-88bc-5c9b6efdda14.png)

**Comment by daltonp** [comment]
Did you select one of the stylings provided or using a custom class name?

**Comment by Nirjonadda** [comment]
@daltonp What do you meaning? This Xenforo core Notice and all other style working. So give more Details what we can do?

**Comment by mikecreuzer** [comment]
Ill assume its blue icon on blue text. 

@Ian-Hitt may need to use some kind of color inherit maybe on that close trigger?
