### ISSUE TITLE
User Replied 

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#895]
Style Name:
UI.X Material 2.0.10 Patch Level 1
Style Version:
UI.X Material 2.0.10 Patch Level 1
XenForo Version:
v2.0.9

Summary of issue:

Shows last post user and the word "replied."  How about making it dynamic and if 0 replies, have thread starter and word posted or started and then change to last post user and "replied" if there is a reply.
This is the  same in UI.X2 but only shows when lower res screen.
![image](https://user-images.githubusercontent.com/6074069/48317362-bd8b5a80-e5e8-11e8-9a47-4b0b69f03cae.png)

**Comment by mikecreuzer** [comment]
Its not a bad idea tbh, just not something we can easily fix. Something XenForo themselves would need to address before we could.
