### ISSUE TITLE
Fix the ugliness of the canvas

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#902]
I've brought it up a dozen times, but don't think I made an issue. So here are my suggestions:

![image](https://user-images.githubusercontent.com/1217271/48496571-ed5c7d00-e7f7-11e8-807d-5ff86a731382.png)

- [x] First of all, I would like it if the navigation/UI.X Navigation components were used, at least stylistically as a base, even if they are just mixins. As ultimately you'll want like same font-size/weight/color/active states/etc etc

- [x] If the above is a bit iffy, I just want to make sure its known that the biggest problem right now is the contrast between tablinks and the main links. They look awfully similar, see screenshot

<strike>- [ ] Style properties should work the same. If 'open by default' on active tab is set, this should also be the case on the canvas. We should not ever have to edit canvas, it should inherit everything. </strike>

<strike>- [ ] There may be some cases where it won't work, due to canvas color, so a few SPs for links/hovers/sublinks might make sense</strike>

- [x] This should be a symptom resolved by the above, but I wouldn't mind seeing widget location that was uix side navigation be moved to this canvas. Or copied. As ultimately I see this canvas component == to the on canvas uix side navigation component 100%.

- [ ] push footer to bottom

- [x] font sizes for visitor tab menus

- [x] add profile alerts and settings to canvas menu

- [x] canvas menu header reduce size

**Comment by Ian-Hitt** [comment]
```There may be some cases where it won't work, due to canvas color, so a few SPs for links/hovers/sublinks might make sense``` There are already 6 or 7 style properties to control canvas separately if needed

**Comment by Ian-Hitt** [comment]
@mikecreuzer Regarding widgets, I assume we would want them on the navigation tab only correct? Unlike side navigation, the canvas has 4 tabs (when visitor tabs are present here, as is the default)? Tagging @jonw316 who I believe would be able to add these widget locations.
