### ISSUE TITLE
List of stock avatar values

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#91]
@nikkiradloff can you get us a list of 25 color values from material that we can use isntead of XenForo's current color values? Then reassign to @Ian-Hitt

**Comment by mikecreuzer** [comment]
@JakeBooher should this be done in the add-on? 

Its just their avatar colors are hideous. No reason for it.

**Comment by nikkiradloff** [comment]
[avatar_swatches.txt](https://github.com/Audentio/xf2theme-issues/files/1428278/avatar_swatches.txt)
