### ISSUE TITLE
Scope our custom threadbit style to desktop

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#913]
- [x] Remove reaction on reactions add-on for MOBILE ONLY
- [x] Essentially on mobile, you have stock XF threadbit

**Comment by Ian-Hitt** [comment]
https://github.com/Audentio/xf2addon-issues/issues/1142

**Comment by Ian-Hitt** [comment]
https://github.com/Audentio/xf2addon-issues/issues/new
