### ISSUE TITLE
iO/iO Dark Mode - Logo pops with scrolling up and down

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#925]
Logo's on iO/iO Dark Mode have been known to pop on mobile devices when scrolling up and down.

**Comment by Ian-Hitt** [comment]
This is intentional, the entire bar is shrinking

**Comment by mikecreuzer** [comment]
As I mentioned, I need it to not do this. Its also kinda spazzing. So even if you wanted it to shrink on scroll, its still spazzing. Going to reopen for now, as Im not sure if you did the sticky on load thing I wanted.
