### ISSUE TITLE
UI.X - Search Bar search issues

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#928]
Style Name: UI.X 2/UI.X 2 Dark

Style Version: 2.0.10.0.0

UI.X Add-on Version: 2.0.11 

XenForo Version: 2.0.10

Operating System (and Version): Windows 8.1

Browser Name (and Version): Google Chrome - Version 70.0.3538.102 (Official Build) (64-bit)

Can you replicate this issue on our demo for this theme? Yes

Does this issue happen in the default XenForo style? No

Summary of issue: 

> If you want to search inside a thread and insert what you want to search and press enter it search the entire forum not inside thread, but if you click search button it goes where it should.
> 
> EG: If you try to search "Children" in that thread and select "This thread" option and then press enter will search entire forum not inside that thread.
> 
> https://imgur.com/Ws2ClwE
> 
> But if you search "Children" and select "This thread" option and then click on Search button will search only in that thread.
> 
> https://imgur.com/Ms9hJ87

Was quoted from the following [thread](https://xenforo.com/community/threads/ui-x-2-dark-paid.137958/post-1297919) but have provided screenshot links too it happening on one of our demos as well.

Detailed steps to reproduce the issue:

Following mentioned above ^^

Upload any screenshots related to the issue below

Clicking "Search" 
https://gyazo.com/611ee61b9e2f50e4d1c0159daee88563

Using the "Enter" key
https://gyazo.com/1bd95a946fded03d5c6c34fd90af7a23

**Comment by jonw316** [comment]
Temporary fix (add to bottom of PAGE_CONTAINER):
<xf:js>
	$(document).ready(function() {
		$('.uix_searchForm').submit(function(e) {
			$('.uix_searchDropdown__menu form')[0].submit();
			e.preventDefault();
		})
	});
</xf:js>

**Comment by Ian-Hitt** [comment]
This has been moved to uix_js
