### ISSUE TITLE
UI.X Pro - Spotify provider login banner

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#929]
Spotify provider login banner are not showing correctly.

![screenshot00742](https://user-images.githubusercontent.com/6899856/48924055-5dcc6380-eeb4-11e8-8c08-89b603a98437.png)

**Comment by daltonp** [comment]
I'm not able to replicate this on our demo. Are you using the latest version of Spotify and UI.X Pro?

**Comment by Nirjonadda** [comment]
Yes ! show me what you are getting.

**Comment by daltonp** [comment]
![spotify_snapshop_connected_accounts](https://user-images.githubusercontent.com/32306910/48952609-6058a880-ef08-11e8-87c8-b7b8b3efc1aa.png)
This is what I am experiencing on our demo.

**Comment by Nirjonadda** [comment]
@Ian-Hitt Please can you able to replicate this in my site?

**Comment by Ian-Hitt** [comment]
@Nirjonadda Just looked through your template mods, your spotify add-on is just outdated. Download the latest from TH to fix.

**Comment by Nirjonadda** [comment]
Already using latest version of spotify add-on. So what version you are referring?
