### ISSUE TITLE
Widgets styles using iO and XPress

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#930]
Style Name:
iO
Style Version:
Latest
UI.X Add-on Version:
[TH] UI.X 2.0.11
XenForo Version:
v2.0.10
Operating System (and Version):
win 10
Browser Name (and Version):
Chrome & Firefox
Can you replicate this issue on our demo for this theme?
N/a
Does this issue happen in the default XenForo style?
No

Summary of issue:
Widgets not styled properly when using  [TH] XPress 1.0.0 Patch Level 5

Upload any screenshots related to the issue below

![image](https://user-images.githubusercontent.com/6074069/48980536-511d5a80-f0c2-11e8-869e-29e8022f856c.png)

**Comment by Ian-Hitt** [comment]
This is an issue in XPress, and there is an open issue on it there

**Comment by arm5ky** [comment]
@Ian-Hitt I've looked through Xpress issues and can't find it as wanted to add a few other details.
