### ISSUE TITLE
iO Email buttons not able to see

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#932]
Style Name:
iO

Summary of issue:
![image](https://user-images.githubusercontent.com/6074069/48985763-5058e880-f103-11e8-9ab8-af96ff7f7460.png)

Cant see the register button. Using default email app windows 10.

**Comment by mikecreuzer** [comment]
@Ian-Hitt can you fix this in UIX it keeps happening, I assume you must be patching per theme then?
