### ISSUE TITLE
iO forum shown in what's new when on resposive

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#933]
Style Name:
iO
The forum is shown in New Posts when responsive but not when turning phone landscape

**Comment by Ian-Hitt** [comment]
Would you mind providing a bit more detail on what is happening here? A screenshot would be helpful as well.

**Comment by arm5ky** [comment]
sorry, was on on mobile.

Here's desktop
![image](https://user-images.githubusercontent.com/6074069/49041932-8c04b880-f1be-11e8-9d80-d20672faca09.png)
Here's mobile
![image](https://user-images.githubusercontent.com/6074069/49041969-ac347780-f1be-11e8-853e-1f7baa5a6d45.png)
