### ISSUE TITLE
Documentation for top bar

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#936]
https://xenforo.com/community/threads/th-ui-x-pro-paid.155353/page-4#post-1301147

**Comment by Ian-Hitt** [comment]
Currently planning on extending the public navigation system to cover both this, as well as mega menus. Will write documentation once we have settled on, and implemented, a final system for managing these tabs.

**Comment by Ian-Hitt** [comment]
No longer applicable
