### ISSUE TITLE
UI.X Pro - Close button should in right side for Fixed

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#942]
Close button should in right side for Fixed Notice type.

![screenshot00777](https://user-images.githubusercontent.com/6899856/49401991-f4b4dd80-f748-11e8-954e-5e9c296d3dd7.png)

**Comment by daltonp** [comment]
Able replicate this myself on one of our demos, thanks @Nirjonadda the report!

**Comment by Ian-Hitt** [comment]
Fixed in a previous release
