### ISSUE TITLE
UI.X Dark (Latest) - Wrong Icons Path (assumes UIX not UIX dark dir structure)

### ISSUE THREAD

**Issue by lilalien** [Audentio/xf2theme-issues#943]
Style Name: UIX Dark

Style Version: Latest released today!

UI.X Add-on Version: Latest

XenForo Version: Latest Stable

Operating System (and Version): Windows 10 - 64 Bit (Latest)

Browser Name (and Version): Chrome 64-bit (Latest)

Summary of issue:

I noticed when merging templates with today's new release, that it changed the below hard-coded paths to use a directory that doesn't exist in UIX-DARK standalone.. Code in uix_icons.less:

`src: url("styles/uix/fonts/icons/material-icons/materialdesignicons-webfont.eot?v=3.0.39");
	src: url("styles/uix/fonts/icons/material-icons/materialdesignicons-webfont.eot?#iefix&v=3.0.39") format("embedded-opentype"), url("styles/uix/fonts/icons/material-icons/materialdesignicons-webfont.woff2?v=3.0.39") format("woff2"), url("styles/uix/fonts/icons/material-icons/materialdesignicons-webfont.woff?v=3.0.39") format("woff"), url("styles/uix/fonts/icons/material-icons/materialdesignicons-webfont.ttf?v=3.0.39") format("truetype"), url("styles/uix/fonts/icons/material-icons/materialdesignicons-webfont.svg?v=3.0.39#materialdesigniconsregular") format("svg");`

Obviously those paths wouldn't exist in UI.X Dark standalone.. There is ONLY uix_dark directory structure!

Should I just alter them and add the _dark after all of them for now until this is fixed?

Thanks!

**Comment by Ian-Hitt** [comment]
These lines are commented out and deprecated now.
