### ISSUE TITLE
2 Template error logs regarding topics

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#945]
Let me start off by saying this is a clean XenForo installation. No add-ons have ever been installed before. I only have 4 add-ons installed. 3 are the official XF ad-ons and the the other is the latest UI.X add-on. I have a further two themes installed, iO and iO dark, both clean installations with minimal edits.

I keep receiving these two errors that look like they relate to topics due to the word "topics" in them.
Server error log
ErrorException: Template error: Template public:thtopics_topic_macros is unknown src/XF/Template/Templater.php:584
Generated by: Unknown account Nov 28, 2018 at 5:14 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Template public...', '/home/gnonline/...', 584, Array)
#1 src/XF/Template/Templater.php(584): trigger_error('Template public...', 512)
#2 src/XF/Template/Templater.php(552): XF\Template\Templater->getTemplateData('public', 'thtopics_topic_...')
#3 src/XF/Template/Templater.php(662): XF\Template\Templater->getTemplateMacro('public', 'thtopics_topic_...', 'assets')
#4 internal_data/code_cache/templates/l1/s7/public/thtopics_structured_list.less.php(101): XF\Template\Templater->callMacro('thtopics_topic_...', 'assets', Array, Array)
#5 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#6 src/XF/CssRenderer.php(297): XF\Template\Templater->renderTemplate('thtopics_struct...', Array, false)
#7 src/XF/CssRenderer.php(235): XF\CssRenderer->renderTemplate('public:thtopics...', NULL)
#8 src/XF/CssRenderer.php(101): XF\CssRenderer->renderTemplates(Array, Array, Array)
#9 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#10 css.php(30): XF\CssWriter->run(Array, 71, 1, '8f93f8e527f71e3...')
#11 {main}
Request state
array(4) {
  ["url"] => string(398) "/css.php?css=public%3Aalnb_navigation.less%2Cpublic%3Anotices.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Ath_covers.less%2Cpublic%3Ath_nodeStyling_nodes.71.less%2Cpublic%3Ath_topicCache_topics.less%2Cpublic%3Athtopics.less%2Cpublic%3Athtopics_structured_list.less%2Cpublic%3Athtopics_widget_topic_filter.less%2Cpublic%3Aextra.less&s=71&l=1&d=1537568912&k=8f93f8e527f71e3dde9d6ddb15dddbbff33add05"
  ["referrer"] => string(51) "https://www.joyfreak.com/tags/elder-scrolls-online/"
  ["_GET"] => array(5) {
    ["css"] => string(282) "public:alnb_navigation.less,public:notices.less,public:share_controls.less,public:th_covers.less,public:th_nodeStyling_nodes.71.less,public:th_topicCache_topics.less,public:thtopics.less,public:thtopics_structured_list.less,public:thtopics_widget_topic_filter.less,public:extra.less"
    ["s"] => string(2) "71"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1537568912"
    ["k"] => string(40) "8f93f8e527f71e3dde9d6ddb15dddbbff33add05"
  }
  ["_POST"] => array(0) {
  }
}

and

Server error log
ErrorException: Template error: Macro public:thtopics_topic_macros:assets is unknown src/XF/Template/Templater.php:558
Generated by: Unknown account Nov 28, 2018 at 5:14 PM
Stack trace
#0 [internal function]: XF\Template\Templater->handleTemplateError(512, 'Macro public:th...', '/home/gnonline/...', 558, Array)
#1 src/XF/Template/Templater.php(558): trigger_error('Macro public:th...', 512)
#2 src/XF/Template/Templater.php(662): XF\Template\Templater->getTemplateMacro('public', 'thtopics_topic_...', 'assets')
#3 internal_data/code_cache/templates/l1/s7/public/thtopics_structured_list.less.php(101): XF\Template\Templater->callMacro('thtopics_topic_...', 'assets', Array, Array)
#4 src/XF/Template/Templater.php(1250): XF\Template\Templater->{closure}(Object(ThemeHouse\UIX\XF\Template\Templater), Array)
#5 src/XF/CssRenderer.php(297): XF\Template\Templater->renderTemplate('thtopics_struct...', Array, false)
#6 src/XF/CssRenderer.php(235): XF\CssRenderer->renderTemplate('public:thtopics...', NULL)
#7 src/XF/CssRenderer.php(101): XF\CssRenderer->renderTemplates(Array, Array, Array)
#8 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#9 css.php(30): XF\CssWriter->run(Array, 71, 1, '8f93f8e527f71e3...')
#10 {main}
Request state
array(4) {
  ["url"] => string(398) "/css.php?css=public%3Aalnb_navigation.less%2Cpublic%3Anotices.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Ath_covers.less%2Cpublic%3Ath_nodeStyling_nodes.71.less%2Cpublic%3Ath_topicCache_topics.less%2Cpublic%3Athtopics.less%2Cpublic%3Athtopics_structured_list.less%2Cpublic%3Athtopics_widget_topic_filter.less%2Cpublic%3Aextra.less&s=71&l=1&d=1537568912&k=8f93f8e527f71e3dde9d6ddb15dddbbff33add05"
  ["referrer"] => string(51) "https://www.joyfreak.com/tags/elder-scrolls-online/"
  ["_GET"] => array(5) {
    ["css"] => string(282) "public:alnb_navigation.less,public:notices.less,public:share_controls.less,public:th_covers.less,public:th_nodeStyling_nodes.71.less,public:th_topicCache_topics.less,public:thtopics.less,public:thtopics_structured_list.less,public:thtopics_widget_topic_filter.less,public:extra.less"
    ["s"] => string(2) "71"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1537568912"
    ["k"] => string(40) "8f93f8e527f71e3dde9d6ddb15dddbbff33add05"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by Ian-Hitt** [comment]
@jonw316 Is this because some topics templates are edited in UI.X, but some that they are using (such as macro definitions) are not?
