### ISSUE TITLE
Template error log 

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#946]
This is another separate error log. No idea where it is coming from. Again, it's an error log on the clean installation of XenForo. Clean database. No unofficial add-ons other than UI.X add-on and two clean theme installations iO and iO dark with minimal edits.

Server error log
Less_Exception_Chunk: ParseError: Unexpected input in anonymous-file-289.less on line 1626, column 62 1624| .porta-features-media 1625| { 1626| position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 80; 1627| margin: auto; 1628| width: ; 1629| height: ( - ( * 2)); src/vendor/oyejorge/less.php/lib/Less/Parser.php:677
Generated by: Unknown account Nov 29, 2018 at 11:54 PM
Stack trace
#0 src/vendor/oyejorge/less.php/lib/Less/Parser.php(621): Less_Parser->GetRules(NULL)
#1 src/vendor/oyejorge/less.php/lib/Less/Parser.php(449): Less_Parser->_parse()
#2 src/XF/CssRenderer.php(363): Less_Parser->parse('// Note that th...')
#3 src/XF/CssRenderer.php(311): XF\CssRenderer->renderToCss('public:widget_E...', '// Note that th...')
#4 src/XF/CssRenderer.php(235): XF\CssRenderer->renderTemplate('public:widget_E...', NULL)
#5 src/XF/CssRenderer.php(101): XF\CssRenderer->renderTemplates(Array, Array, Array)
#6 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#7 css.php(30): XF\CssWriter->run(Array, 58, 1, '4897eb74cb3b245...')
#8 {main}
Request state
array(4) {
  ["url"] => string(308) "/css.php?css=public%3AEWRporta.less%2Cpublic%3AEWRporta_articles.less%2Cpublic%3Aalnb_navigation.less%2Cpublic%3Amessage.less%2Cpublic%3Anotices.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Awidget_EWRporta_features.less%2Cpublic%3Aextra.less&s=58&l=1&d=1519483161&k=4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  ["referrer"] => string(30) "https://www.gnonline.net/home/"
  ["_GET"] => array(5) {
    ["css"] => string(200) "public:EWRporta.less,public:EWRporta_articles.less,public:alnb_navigation.less,public:message.less,public:notices.less,public:share_controls.less,public:widget_EWRporta_features.less,public:extra.less"
    ["s"] => string(2) "58"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1519483161"
    ["k"] => string(40) "4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by joyfreak** [comment]
Here is a thread on XF with the error log reported and everyones in take: https://xenforo.com/community/threads/error-log.157349/

**Comment by Ian-Hitt** [comment]
This is a bun in xenporta css

**Comment by Ian-Hitt** [comment]
Fixed in latest commit
