### ISSUE TITLE
UI.X Pro - Bug on Sticky category strips

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#947]
Still bug on Sticky category strips: https://giant.gfycat.com/ImpracticalCheerfulChameleon.webm

**Comment by daltonp** [comment]
I'm able to confirm this on one of demos as well, thanks @Nirjonadda!

**Comment by Ian-Hitt** [comment]
The category strips just dont have a background color. You can set a background color in category strips in Style Properties > Node/forum list.
