### ISSUE TITLE
RM thread item margin issue

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#948]
![image](https://user-images.githubusercontent.com/1217271/49536376-f2a76780-f88b-11e8-8c93-19dc4c8bfb1f.png)

**Comment by Ian-Hitt** [comment]
Looks like it was actually a white text issue. there is text between those two lines that you can't see

**Comment by Ian-Hitt** [comment]
<img width="999" alt="screen shot 2019-01-17 at 2 00 29 pm" src="https://user-images.githubusercontent.com/15836384/51345317-41861680-1a60-11e9-9ca3-8bccd80c052a.png">
