### ISSUE TITLE
iO - Select for moderation opens thread

### ISSUE THREAD

**Issue by arm5ky** [Audentio/xf2theme-issues#950]
Style Name:
iO
XenForo Version:
v2.0.10

Does this issue happen in the default XenForo style?
No
Summary of issue:
Selection for moderation opens thread.
Detailed steps to reproduce the issue:

Upload any screenshots related to the issue below
https://i.imgur.com/SQJn6GK.gifv

**Comment by Ian-Hitt** [comment]
Duplicate of https://github.com/Audentio/xf2theme-issues/issues/966, closing
