### ISSUE TITLE
iO Dark and probably iO Light too

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#951]
When on forum list, and you click on a thread.. the loading/navbar seems to have a spasm and then randomly the navigation bar would sit where it wants, sometimes above the post, or on the tip of the post or overlapping the post.  Its random on each click. Hard to explain, if need more clarification, feel free to ask.

**Comment by Ian-Hitt** [comment]
We are aware of this one, it is due to sticky kit and the fix would require the removal of sticky kit, and the implementation of a new sticky system. there is a generic issue on this already, so closing this one.
