### ISSUE TITLE
UI.X Pro - Add a style property to make the top bar sticky

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#954]
Why not allow users to sticky the top bar that shows on UI.X Pro as right now it disappears when users scroll down.
https://gyazo.com/d02a040e7afd957321cd64358974eb41

**Comment by kylerc** [comment]
Add support for multiple breakpoints

**Comment by Ian-Hitt** [comment]
Need to add offset breakpoints for tabbar sticky after Kyler's fix for adding multiple offset breakpoints

**Comment by jonw316** [comment]
Required code is something like:
```<xf:set var="$topOffsetBreakpoints">[{"breakpoint": "{{ property('someProperty')|escape('json') }}", "offset": "{$someVariable|escape('json')}"}]</xf:set>
<div class="uix_stickyBar" data-top-offset-breakpoints="{$topOffsetBreakpoints|for_attr}">```
