### ISSUE TITLE
UI.X Pro - Add new posts page in top bar

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#955]
Add new posts page in top bar.

![screenshot00797](https://user-images.githubusercontent.com/6899856/49666897-b164b280-fa59-11e8-853c-3c42b5fe1f1c.png)

**Comment by jonw316** [comment]
New posts link was removed from Topics add-on.

@Ian-Hitt Can you add a simple style property to allow the new posts link to be shown even if it is not set as the forum homepage?

**Comment by Ian-Hitt** [comment]
The new posts page does not exist unless it is set as default. You can use whats new, but that is just redundant. Closing this issue as it's not applicable.
