### ISSUE TITLE
Online indicator status

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#968]
- [x] Default (same as now in xf 2.1)
- [x] Dot
- [x] Pulsing dot? Its just css from xf1
- [x] "Online now" user banner
<strike>- [ ] MySpace (https://media.giphy.com/media/EU2pucC5YT20g/200.gif)</strike>

**Comment by Ian-Hitt** [comment]
Myspace didn't make the cut :(

**Comment by Ian-Hitt** [comment]
Added in https://github.com/Ian-Hitt/xf2/commit/641518374ae2865ecd685e757597408bc0fc855a
