### ISSUE TITLE
Support for ctrl + click on clickable area nodes/threads

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#974]
My recommendation is either actually bind clicks to a real link (which not sure if thatll work) or just add support manually for ctrl: https://stackoverflow.com/questions/26823884/jquery-javascript-allow-ctrl-click-to-open-link-in-new-tab

**Comment by Ian-Hitt** [comment]
- [ ] threads

- [ ] nodes
