### ISSUE TITLE
 UI.X Pro - Pofiles find button should be Sticky

### ISSUE THREAD

**Issue by Nirjonadda** [Audentio/xf2theme-issues#978]
Pofiles find button should be show under Last seen but this changing, not place for all time.

![screenshot00858](https://user-images.githubusercontent.com/6899856/50356746-7c755700-0553-11e9-9edb-b546061561a8.png)

This position are changing:

![screenshot00856](https://user-images.githubusercontent.com/6899856/50356743-767f7600-0553-11e9-95c4-a903bbd9ffd8.png)

Add one line for separate, like Xenforo style does.

![screenshot00857](https://user-images.githubusercontent.com/6899856/50356796-aaf33200-0553-11e9-9781-64b3b0c811f1.png)

**Comment by Ian-Hitt** [comment]
This is intentional and preferred. No need to waste an entire extra line unless the content doesn't fit.
