### ISSUE TITLE
Tooltip on share buttons off alignment

### ISSUE THREAD

**Issue by mikecreuzer** [Audentio/xf2theme-issues#98]
<img width="270" alt="screen shot 2017-10-30 at 10 55 59 am" src="https://user-images.githubusercontent.com/1217271/32180812-f4997a22-bd60-11e7-968a-7ab2efeec8e6.png">

Not sure what to do here, since it could be related to a render issue with whatever plugin they use. Worth noting and taking a look at at some point. Worst case removing. We will likely want some style properties for labels anyway.

**Comment by Ian-Hitt** [comment]
duplicate, closing
