### ISSUE TITLE
Approval Queue Styling - Spam clean styling

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#982]
A red outline is seen when assigning an unapproved thread too "Spam clean" on some themes. The following themes include:

- Class
- Drift
- Drift Dark
- Tactical
- UI.X Classic
- UI.X Classic Dark

![approval_queue_spam_clean_red_highlight](https://user-images.githubusercontent.com/32306910/50454510-a8a32600-090d-11e9-9b76-4d43f5937041.jpg)

Is this intentional? If not, the following themes don't have this styling:

- UI.X 2
- UI.X 2 Dark
- iO
- iO Dark
- UI.X Material
- UI.X Pro
- UI.X Pro Dark
- Xenith
- Abyss
- Flare
- Intrepid

**Comment by Ian-Hitt** [comment]
This is intentional. Changes border to red if there is one, and does not add one if there is not.
