### ISSUE TITLE
Mobile spacing issues between post title/prefix and posting information on What's New page

### ISSUE THREAD

**Issue by daltonp** [Audentio/xf2theme-issues#987]
![img_1852](https://user-images.githubusercontent.com/32306910/50487939-cb911100-09c5-11e9-990f-74bfcd269ebc.JPG)
![img_1847](https://user-images.githubusercontent.com/32306910/50487940-cb911100-09c5-11e9-9fac-3ae4d2bff572.JPG)
![img_1848](https://user-images.githubusercontent.com/32306910/50487941-cb911100-09c5-11e9-9de4-406ffe9b52bb.JPG)
![img_1849](https://user-images.githubusercontent.com/32306910/50487942-cb911100-09c5-11e9-9445-e70252e351cd.JPG)
![img_1851](https://user-images.githubusercontent.com/32306910/50487943-cb911100-09c5-11e9-9fc9-5946d51711a5.JPG)

**Comment by Ian-Hitt** [comment]
This is a side effect of putting the node stats on their own line for a long as possible. In the default theme, these stats are always on their own line.
