### ISSUE TITLE
Error log

### ISSUE THREAD

**Issue by joyfreak** [Audentio/xf2theme-issues#993]
Server error log
Less_Exception_Chunk: ParseError: missing opening `(` in anonymous-file-0.less on line 842, column 34 840| // UI.X browser query variables 841| 842| @isIe: ~"(-ms-high-contrast: none), (-ms-high-contrast: active)"; 843| 844| @uix_sidebarNavBreakpoint: 1660px; 845| src/vendor/oyejorge/less.php/lib/Less/Parser.php:677
Generated by: Unknown account Jan 10, 2019 at 6:08 AM
Stack trace
#0 src/vendor/oyejorge/less.php/lib/Less/Parser.php(621): Less_Parser->GetRules(NULL)
#1 src/vendor/oyejorge/less.php/lib/Less/Parser.php(449): Less_Parser->_parse()
#2 src/XF/CssRenderer.php(363): Less_Parser->parse('// Note that th...')
#3 src/XF/CssRenderer.php(311): XF\CssRenderer->renderToCss('public:widget_E...', '// Note that th...')
#4 src/XF/CssRenderer.php(235): XF\CssRenderer->renderTemplate('public:widget_E...', NULL)
#5 src/XF/CssRenderer.php(101): XF\CssRenderer->renderTemplates(Array, Array, Array)
#6 src/XF/CssWriter.php(53): XF\CssRenderer->render(Array)
#7 css.php(30): XF\CssWriter->run(Array, 58, 1, '4897eb74cb3b245...')
#8 {main}
Request state
array(4) {
  ["url"] => string(308) "/css.php?css=public%3AEWRporta.less%2Cpublic%3AEWRporta_articles.less%2Cpublic%3Aalnb_navigation.less%2Cpublic%3Amessage.less%2Cpublic%3Anotices.less%2Cpublic%3Ashare_controls.less%2Cpublic%3Awidget_EWRporta_features.less%2Cpublic%3Aextra.less&s=58&l=1&d=1526217854&k=4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  ["referrer"] => string(30) "https://www.gnonline.net/home/"
  ["_GET"] => array(5) {
    ["css"] => string(200) "public:EWRporta.less,public:EWRporta_articles.less,public:alnb_navigation.less,public:message.less,public:notices.less,public:share_controls.less,public:widget_EWRporta_features.less,public:extra.less"
    ["s"] => string(2) "58"
    ["l"] => string(1) "1"
    ["d"] => string(10) "1526217854"
    ["k"] => string(40) "4897eb74cb3b245b7f4cd2eec0d8060e549b72be"
  }
  ["_POST"] => array(0) {
  }
}

**Comment by Ian-Hitt** [comment]
This issue is resolved.
