### ISSUE TITLE
Add support for web app (A2HS) support, with style properties to control options

### ISSUE THREAD

**Issue by Ian-Hitt** [Audentio/xf2theme-issues#996]

**Comment by Ian-Hitt** [comment]
ios swipe support
https://developer.apple.com/documentation/uikit/touches_presses_and_gestures/handling_uikit_gestures/handling_swipe_gestures

install banners android
https://developers.google.com/web/fundamentals/app-install-banners/

ios pitfalls/solutions
https://www.netguru.com/codestories/few-tips-that-will-make-your-pwa-on-ios-feel-like-native

https://medium.com/@firt/progressive-web-apps-on-ios-are-here-d00430dee3a7

general PWA setup
https://developers.google.com/web/fundamentals/web-app-manifest/

**Comment by GH-Rake** [comment]
Would love to see an option to have a popup asking the user to add to homescreen when they are logged in - also made a post on the xenforo forums, cheers

**Comment by Ian-Hitt** [comment]
XF added in core, closing.
